### ISSUE TITLE
Can't access some pages

### ISSUE THREAD

**Issue by timoteius** [Codewars/codewars.com#1003]
I am Timotei Satmarean on codewars and I can't acces https://www.codewars.com/trainer/setup, https://www.codewars.com/kumite, https://www.codewars.com/trainer/setup, https://www.codewars.com/dashboard. Every time I try to access one of these I get "Aw, snap! Something went wrong while displaying this webpage."

**Comment by DonaldKellett** [comment]
@timoteius Consider including the following information in your Issue Report:

- The browser in which you are encountering this Issue in
- A suitable screenshot, ideally containing any error logs from the browser (e.g. use "Inspect Element" on Safari)

**Comment by timoteius** [comment]
![2017-06-22_08-08-54](https://user-images.githubusercontent.com/26526328/27418240-697f319c-5722-11e7-9c8c-7e9caf0f5dd5.png)
view-source:https://www.codewars.com/trainer/setup
I use only Google Chrome, but I downloaded Opera to try it.

**Comment by gmaksim** [comment]
In Chrome 58.0.3029.110 (64-bit) and Firefox 54 same trouble.

**Comment by jamsna3** [comment]
Has this been resolved already?

**Comment by gmaksim** [comment]
Just now checked, all work correctly!
Thanks.

**Comment by dmz9** [comment]
the problem still exists on older versions of windows os (at least win7 x64)
after a hour of trial&error i figured out that there is something wrong with stylesheet file (app*.css)
more exactly - the "ico-moon" font is crashing the tab of a browser (no matter which one)
i tried this - i found request blocker extension for chrome and installed it
then i added block rule like this one
`https://www.codewars.com/assets/icomoon*`
and viola - the tab is working OK now
but all font-icons are not rendered anymore

i tried another solution - i have installed free version of icomoon font on pc, but it didnt work - the name of the font, used in stylesheet is "ico-moon", not "icomoon-free", which is "free version" one's name, so it is requested by browser anyway. 
looks like there are some incorrect symbols inside the font's file, because the crash happens only when some exact symbols of the font are required by css-engine via .ico-moon-(*):before{content: "{symbol-reference-here}" } declarations

**Comment by elmerptuazon** [comment]
It works! Thanks dmz9
