### ISSUE TITLE
Missing recommended Kata

### ISSUE THREAD

**Issue by aishwaryapradhan** [Codewars/codewars.com#1014]
I got this kata in my newsletter. http://www.codewars.com/kata/esolang-ticker. It states, "NOTE: It is recommended you complete Introduction to Esolangs or MiniBitFlip before solving this one." Out of which MiniBitFlip (https://www.codewars.com/kata/esolang-minibitflip/) is not available and showing a server error. 

Please resolve this. Thank you so much for your work. :)

**Comment by kazk** [comment]
I think "MiniBitFlip" was renamed to "MiniBitMove" (http://www.codewars.com/kata/esolang-minibitmove).
You can let the author know about this so s/he can update the description on the [discourse](http://www.codewars.com/kata/esolang-ticker/discuss/) of "Esolang: Ticker".

---

I'm closing this because this issue is specific to that kata and can be resolved by the author.

**Comment by aishwaryapradhan** [comment]
Thanks for your help :)
