### ISSUE TITLE
New language BF's rank progress is not shown inside user profiles

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1044]
![image](https://user-images.githubusercontent.com/14909989/28426529-f934a436-6da5-11e7-8866-e3907ad0447e.png)

It's not shown below the language per-se breakdown list too.

**Comment by jhoffner** [comment]
BF is only in preview and is not ready for production use yet. If you saw a BF kata, then someone must have published one from preview. We have not fully finished loading the new language onto all runner clusters since I have been working through some performance issues all week with the code runner engine.
