### ISSUE TITLE
Fackebook Linking

### ISSUE THREAD

**Issue by CaptainSpalding** [codewars/codewars.com#1070]
I am sure it is not a huge issue, But I can not link my CW account to my FB account, I am trying to get some friends to come "play with me" and join my little group, which I am apparently in a group but I just wrote Hobby (0)_(0) cause it is a hobby of mine, but yeah anyway, it is just not linking accounts that's all my good sirs, and madams.

**Comment by DonaldKellett** [comment]
I can testify to that.  Every time I try to link my Facebook account on Codewars I get this error message:

![2017-08-13 1 02 14](https://user-images.githubusercontent.com/7777884/29246300-a507d1d2-8027-11e7-8098-05a1874fe71d.png)

I've tried it multiple times over the past few months with the same results every time.

**Comment by TomaszSowa** [comment]
The same here.

**Comment by AndrewKeene** [comment]
I am also running into this issue.  Attempted on Chrome and Safari.

**Comment by Leucazolitmine** [comment]
I'm having the same problem (Chrome). Just hope it's going to be fixed one day ;)

**Comment by kazk** [comment]
Facebook linking is fixed (#2183) so the error shouldn't be shown anymore, but the link to your Facebook profile won't be added to your profile because we can no longer get the profile URL. This is because getting your Facebook profile URL requires additional scope that needs to be reviewed and approved by Facebook.
We'll be removing this feature if we cannot get approved.
