### ISSUE TITLE
Forked translations credit their solutions to the original author, and not the forker

### ISSUE THREAD

**Issue by Souzooka** [Codewars/codewars.com#1073]
If a user were to fork a translation to a Kata and make several changes, and then have their Kata approved, their solutions would be credited to the original author of the translation and not to the person who forked the translation.

This also means that the forker does not get credit for solving the Kata in that language and has to resolve the Kata.

**Comment by jhoffner** [comment]
This is by design. We can only apply credit to one person. All we can really do is try to make the most-likely scenario assumption. If someone writes a translation and puts an hour into it, then someone realizes a bug, forks it and takes 1 minute to fix a typo - shouldn't the original translator get the credit? Did the forker really do enough to get credit?

In what case would the forker deserve more credit. Did a translator take 5 minutes writing a terrible translation and the forker took an hour rewriting it into a good one? Then they should deserve credit but to how far would we need to go to try to determine that automatically, and how accurate would that method really be?

We could try to let the approver pick which person should get the credit, but that has its own host of issues and shortcomings. 

In the end the most likely case is that the original translator did most of the work and the forker is just fixing an issue or two.

**Comment by jhoffner** [comment]
Wait - I completely misread the issue. Translators should be getting the credit, I will look into if this is not the case (I know its coded to be the case) and if so fix the bug.
