### ISSUE TITLE
Proposals to make kata editing/translation approval privilege less potentially destructive, and better

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1102]
As @dinglemouse pointed out in multiple issues, currently the kata edit and translation approval privilege is very powerful. Perhaps too powerful.

With great power comes great responsibility. And responsibility does not solely equal to honor, which is an vanity trait that cannot be measured reliably.

Here are a few proposed additions to make them greater but not so great they become potentially destructive:

# Users registered for less than 2 weeks old are not allowed to perform the abovementioned 2 operations
- 2 weeks should be enough to weed out impatient, malicious people (unless they're *really* determined to sabotage CW, but I don't think the possibility for someone that'd consider that as cost-effective would be remotely high)
- Users need time to get along with how CW works. You definitely don't want someone who got 75 honor the first day to write a bunch of katas (as they'd likely to be pretty horrible and hits every pitfall of bad katas!). So similarly, users shouldn't even be able to do the above task until he's familiar with how all the translation and beta process works, which 2 weeks should be good enough. Some very powerful users are able to get to 6k in just a few days.
# Only the kata author should be allowed to delete any language version
- I don't see any reasons for anyone else to delete any language versions. It's already very destructive and blunt (even kata authors might hit it accidentally and blow himself up with it), so let's keep it safe and secure from everyone else.
# Kata translations that are over 1 month ago should be able to be approved regardless of kata author's status
- Let's be honest, there are quite some kata authors that are active but nevertheless *never* approves any kata translations that are published under their katas. If they're not resolving the translations, power users might as well take over it.
- If a translation is not up to quality, you should put in on hold, and reject it if the translator is not taking action. Leaving it around is not a very good practice.

**Comment by jhoffner** [comment]
Thanks for the suggestions. 

> 2 weeks should be enough to weed out impatient, malicious people (unless they're really determined to sabotage CW, but I don't think the possibility for someone that'd consider that as cost-effective would be remotely high)

Do we have any evidence of people sabotaging anything? If so I could see us flagging users who gain a crazy amount of honor too quickly, or some other solution that is more direct to the underlying issue.

> You definitely don't want someone who got 75 honor the first day to write a bunch of katas

I'm not sure how getting 75 honor in 1 day vs 75 honor over the course of 14 changes much. In fact, you might earn more honor over time by doing less purely from up votes, comments and referrals. I could see an argument for raising the honor limit, but making privileges honor + time based will increase the complexity of the system quite a bit. 

> users shouldn't even be able to do the above task until he's familiar with how all the translation and beta process works, which 2 weeks should be good enough.

This seems arbitrary and makes a lot of assumptions. I would rather focus energy on making the beta process better or making it less likely that someone will create a poor kata to begin with (like with documentation, context help, dup detection, etc). 2 weeks isn't some sort of magical timeframe that will fix anything. 

> Only the kata author should be allowed to delete any language version

Only admins and kata authors can delete anything. If that's not the case, its a bug.

> Kata translations that are over 1 month ago should be able to be approved regardless of kata author's status

The logic is "if author is inactive for > 1 month or translation was published over a week ago", so this is already covered. 

Active kata authors who do not wish to approve a translation will need to actively reject it within the first week. A rejected translation can be forked and re-published in order to fix the issues.

**Comment by Voileexperiments** [comment]
Thanks for the clarification. The new system definitely needs to be documented (currently it's not very clear what the criteria is and it doesn't help that the approve button is shown at all times even when you can't approve a translation, i.e #1093).
