### ISSUE TITLE
Kumite consistently produces "rare issue"

### ISSUE THREAD

**Issue by Souzooka** [Codewars/codewars.com#1103]
[This kumite](http://preview.codewars.com/kumite/59a7100607157aea7a0000d7?sel=59a7100607157aea7a0000d7) consistently produces the error message "The server attempted to execute your code but there was an issue with the request. This should be a rare issue. Please try running your code again. If the issue persists, please contact us." when run.

**Comment by kazk** [comment]
The linked kumite works if I comment out the random tests and the second one doesn't produce this error. I also see partial outputs until it reaches random tests. So this looks like the issue is in random tests, but the server is showing this error message.

@Souzooka can you explain the changes you made? Did you find that the random tests in the first kumite was causing this?

**Comment by Souzooka** [comment]
@kazk It's something involving `Console.WriteLine`, specifically if you keep line 52 and 53 in Test Cases this error will occur with even one test.

**Comment by kazk** [comment]
I commented out those lines and now it's not producing those errors.

![image](https://user-images.githubusercontent.com/639336/29899283-4425aa44-8d9f-11e7-8270-fb9f2882210c.png)

So 
```csharp
Console.WriteLine(node);
Console.WriteLine(expected);
```
prints out ~154 KB (2*78898/1024)?

I'm pretty sure we have some limits on output size so the issue is most likely caused by that. I'll look into why this causes the whole execution to fail. Thanks for the information.

**Comment by kazk** [comment]
The original kumite no longer crashes on the new runner and shows the long string.

![image](https://user-images.githubusercontent.com/639336/37758108-47a1f642-2d6c-11e8-9c16-cadd5b711b42.png)


I don't know what was causing the error in the old one, but both has output limit of 1.5 MB which should be more than enough.
