### ISSUE TITLE
Someone has been voting lots of beta katas `somewhat satisfied` without solving them

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1174]
I recently have found that apparently there is someone (disgruntled?) who went on a spree to vote lots of beta katas `somewhat satisfied` without solving the kata at all. These votes weren't there at all until this week. It looks like a somewhat semi-targeted act:

- Other power user's katas
  - https://www.codewars.com/kata/number-triangle
  - https://www.codewars.com/kata/numbers-with-collatz-starting-patterns
  - https://www.codewars.com/kata/solomons-quest-for-the-temporal-crystal
  - https://www.codewars.com/kata/seat-allocation-double-dutch

- @myjinxin2015's katas
  - https://www.codewars.com/kata/simple-fun-number-359-cut-the-number
  - https://www.codewars.com/kata/algorithm-fun-find-the-unknown-number-part-iii
  - https://www.codewars.com/kata/find-the-max-sum-of-submatrix-in-a-matrix-simple-version
  - https://www.codewars.com/kata/simple-fun-number-357-show-the-digits
  - https://www.codewars.com/kata/simple-fun-number-354-lonely-frog-iii/discuss
  - https://www.codewars.com/kata/one-line-task-date-of-solar-calendar/discuss
  - https://www.codewars.com/kata/happy-coding-dont-break-my-heart/discuss

- my katas
  - https://www.codewars.com/kata/computing-the-complex-gamma-function
  - https://www.codewars.com/kata/spinning-rings-fidget-spinner-edition
  - https://www.codewars.com/kata/become-immortal
  - https://www.codewars.com/kata/unicode-madness-dong-fang-ming-que-ren-~-eastern-title-validator
  - https://www.codewars.com/kata/a-kata-is-a-kata-you-cant-say-its-only-a-half
  - https://www.codewars.com/kata/ascii-games-warning-ice
  - https://www.codewars.com/kata/xiang-qi-xiangqi-slash-chinese-chess-board-validator

(and probably many more, but you get the idea so I'm not gonna list them all)

Proof: look at the number of ranking votes vs. satisfaction votes, and number of solves. They all exhibit the pattern of `n solves, n-1 rankings (one of the solves comes from the the author) but n votes, with all very satisfied except one`.

The damage has been done. The thing we've conjectured some day to happen HAS BEEN HAPPENED. WE NEED TO DEAL WITH IT ASAP, i.e REMOVE THE ABILITY TO VOTE ON BETA KATAS ONE HASN'T SOLVED

(also please remove these votes)

---

Incidentally, given the final satisfaction rating, this person seems to have 2x voting power, so his honor is between 1000 and 2000.

**Comment by docgunthrop** [comment]
#1165

**Comment by jhoffner** [comment]
I've lowered white/yellow kata requirements to 80% and made it so that you can't vote unless you have completed the kata. These changes are in preview. 

Note that a certain vote threshold is needed to get out of beta. Some users may have liked the kata but just got stuck on the last few tests, deciding to forfeit honor but ultimately voting very satisfied. Without these types of votes, its going to take longer to get out of beta.

One somewhat satisfied vote isn't going to make or break the satisfaction requirement but it will help get a kata to its required vote count faster, so if anything this guy probably helped the situation. 

Regardless I've made the change and we can see how this affects things once I push it out later today.

> Incidentally, given the final satisfaction rating, this person seems to have 2x voting power, so his honor is between 1000 and 2000.

Voting power didn't have anything to do with percentages, though there was a bug with how it affected the voting minimums which I've also fixed. 

Additional, if a kata has 4 votes or more and a 0% satisfaction score, I'm going to auto retire it.

**Comment by Voileexperiments** [comment]
@jhoffner Thanks.

By the way:

> One somewhat satisfied vote isn't going to make or break the satisfaction requirement but it will help get a kata to its required vote count faster, so if anything this guy probably helped the situation.

Even when that happens, the approval process is still bound by ranking votes anyways so it only helps if someone completed the katas and only ranked it.
