### ISSUE TITLE
Wiki about cheat detection and prevention when submitting solutions

### ISSUE THREAD

**Issue by fredz0003** [Codewars/codewars.com#1211]
As I start working on my first translations and brand new katas. I am concerned about cheating solutions. Is there a wiki or any documentation about prevention methods?
How to test if your kata is cheatable?

Interested in Java, Swift and Python.

**Comment by dinglemouse2250** [comment]
0. Ensure your tests cover ever aspect of the Kata description and all edge cases. This will prevent people submitting overly simplistic solutions that pass when they should not
1. **Always** add random tests. That will prevent prevent people submitting static solutions based on known fixed input.
2. Other techniques are for thwarting malicious users. There are various strategies which I guess you are asking about at the risk of starting a flame war IMO why bother?...
* Sleep better by assuming the best in the community instead of the worst ;-)
* Know that everybody is watching and serial CW cheaters will soon be reported and banned anyway
* Spend your energy making better Kata and Test cases for the 99.9% of non-cheaters
* Whatever anti-cheat techniques you employ may not port well to other languages anyway
