### ISSUE TITLE
Test Cases displays both cases and the original author's solution when in translation mode

### ISSUE THREAD

**Issue by Naiten** [Codewars/codewars.com#1223]
Not sure it's a single kata or global problem because it's my first translation, but I believe it's the latter. I was translating https://www.codewars.com/kata/58e24788e24ddee28e000053/ from Python into Java (though it shouldn't be important, i guess).

As you can see on the screenshots, Test Cases box is also displaying the original author's solution, while Solution box displays my latest solution. I believe the former should only display actual test cases and author's solution is not necessary, or should be put into separate box. 
![default](https://user-images.githubusercontent.com/1582835/32784494-b71eab18-c99a-11e7-91f9-add8b7372d3e.JPG)
![-2](https://user-images.githubusercontent.com/1582835/32784502-bb4ffca0-c99a-11e7-8c83-8f280da46209.JPG)
![-3](https://user-images.githubusercontent.com/1582835/32784505-be221dbe-c99a-11e7-8a82-05ef92bac74c.JPG)
This isn't a big issue, but it was confusing for a new warrior and it would be nice if it was fixed.

**Comment by DonaldKellett** [comment]
The only reason the Kata author's solution appears in the actual Test Cases section is because he/she deliberately included it there for the random test cases (otherwise how is random testing even possible?).  Therefore, it is not possible to remove the Kata author's solution from the Test Cases section if he/she included it in the first place, at least not with a simple algorithm.
