### ISSUE TITLE
Author unable to approve translation with no diffs

### ISSUE THREAD

**Issue by GiacomoSorbi** [Codewars/codewars.com#126]
[This](http://www.codewars.com/kumite/559e907f83c64779f000006a?sel=559e907f83c64779f000006a) is the translation of the subject and I am just wondering what is off for it to be approved.

I could try and fork this one too with a copy&pasted description, but I preferred to report it as a possible bug.

Also: imho a smoother approving system that just asks the author if he wants to get the new description and let's him/her see the difference would help a lot.

**Comment by jhoffner** [comment]
If you fork it you will see that you have to handle the merge conflicts between python and ruby. This always happens when two translations are open at the same time, since they both edit the same original description. The first gets approved fine, but the second one now has to be merged with the changes from the first.

Some improvements could definitely be made with this, if nothing else a notification at the top indicating that there are merge conflicts, shown before you click approve. However for now I'm closing as this is working as expected.

**Comment by GiacomoSorbi** [comment]
Fine and thanks for the ultraquick reply :)

**Comment by bkaes** [comment]
> Some improvements could definitely be made with this, if nothing else a notification at the top indicating that there are merge conflicts, shown before you click approve. However for now I'm closing as this is working as expected.

How exactly does Codewars merge the descriptions? At the moment, it sounds more or less like a simple replacement with the new contents. Couldn't you use a three-way-merge as `git` does?

**Comment by jhoffner** [comment]
We do use 3 way merge. It just requires a user to handle conflicts. When viewing conflicts you will see the standard <<<<<<<, ========, >>>>>>>>> format which is used to separate the conflicting changes. 
A better auto merge algorithm could probably be implemented to cut down on the amount of manual work. 

Sent from Outlook




On Tue, Jul 14, 2015 at 6:12 AM -0700, "Benjamin Kästner" <notifications@github.com> wrote:













Some improvements could definitely be made with this, if nothing else a notification at the top indicating that there are merge conflicts, shown before you click approve. However for now I'm closing as this is working as expected.




How exactly does Codewars merge the descriptions? At the moment, it sounds more or less like a simple replacement with the new contents. Couldn't you use a three-way-merge as git does?
