### ISSUE TITLE
Auto complete

### ISSUE THREAD

**Issue by chanansh** [Codewars/codewars.com#1271]
Is it just me or does codewars lacks auto complete?
It's kind of hard to write and solve kata's without it.
Especially writing test where the Test class is propietary

**Comment by Voileexperiments** [comment]
No, that's an IDE feature, not a text editor(CodeMirror)'s feature. If you want full-fledged autocomplete, use  an IDE.

**Comment by jhoffner** [comment]
Some day there may be for some languages. C# in particular is a language that most devs can't live without auto complete. Most other languages, in all honesty, if you can't work at all without auto complete... then you might be a little bit sheltered by your IDE. But to each their own and you can't argue with productivity so... yeah auto complete would be nice.

**Comment by Unihedro** [comment]
Hope I'm not annoying anyone by bumping this thread but I saw another site (CodeFights) using CodeMirror which got this implemented:

![image](https://user-images.githubusercontent.com/5595067/36781661-7ab50572-1cb1-11e8-9441-82ad5135aab4.png) (scala)

![image](https://user-images.githubusercontent.com/5595067/36781682-8fbc4af2-1cb1-11e8-97cc-22d99be5cc79.png) (ruby) 

seems that the functionality resembles what these addons provide: http://codemirror.net/demo/complete.html

**Comment by avawda** [comment]
Sorry for thread necro, but came here to also ponder why CodeWars does not have autocomplete, while CodeSignal has implemented it perfectly.  What a pity.

**Comment by hobovsky** [comment]
Guys, do you even IDE?

**Comment by Voileexperiments** [comment]
This issue seems to have been superseded by #1870

**Comment by kazk** [comment]
Closing as duplicate of #1870.

https://github.com/Codewars/codewars.com/issues/1271#issuecomment-369192151 shows very simple completion and that should be possible to add, but I don't think that's really helpful as discussed on #1870. It's just showing keywords and variable names starting with `a`. It won't be able to suggest methods based on the context because it doesn't analyze the code. CodeMirror's JavaScript completion will suggest for browser environment (try `doc -> document`, `win -> window`) which Codewars doesn't use.

Anyways, please continue on #1870 if you have anything to add.

**Comment by Snipe3000** [comment]
I think HackerRank has auto complete, most people just switched over to that.
