### ISSUE TITLE
goodvsevil kata bug?

### ISSUE THREAD

**Issue by brodo80** [Codewars/codewars.com#1287]
the solution below works fine in Jupyter Notebook. I am using python 3 if that matters.

def goodVsEvil(good, evil):
    g_score = [1,2,3,3,4,10]
    b_score = [1,2,2,2,3,5,10]
    
    a = sum([a*b for a,b in zip(g_score,good)])
    b = sum([a*b for a,b in zip(b_score,evil)])
    
    if a > b:
        return 'Battle Result: Good triumphs over Evil', 'Good should win'
    elif a == b:
        return 'Battle Result: No victor on this battle field', 'Should be a tie'
    else:
        return 'Battle Result: Evil eradicates all trace of Good', 'Evil should win'

goodVsEvil([1,1,1,1,1,2],[1,1,1,1,1,1,1])

THE ERROR I GET IN CODEWARS IS: a type(s) error??

**Comment by DonaldKellett** [comment]
Kata Issues (i.e. issues with individual Kata not the Site itself) should not be raised on this Repo.  Please consider raising an Issue on the Discourse of the Kata concerned instead.  **But** before you do that, please make sure that the type error you're receiving is due to a problem with the Kata itself and **not** your own solution code.

**Comment by Voileexperiments** [comment]
@kazk Please close this issue.

**Comment by kazk** [comment]
Thanks, @DonaldKellett, @Voileexperiments.
