### ISSUE TITLE
Honor score for a beta/published kata should be revoked after it is approved/retired

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1316]
Apparently since the beginning the honor score you get for complete a beta kata will persist even if said beta has been approved/retired.

Obviously, this gives a disadvantage to later users - they don't have as many beta katas to do as the earlier ones because these katas have already been approved. It will also cause lots of problems if we begin taking action on #1315 or #1301 and actually start retiring lots of existing low-quality/duplicate katas (I suspect the honor score does not re-calculate there as well).

Also, related: #1112 and #1109

**Comment by dinglemouse2250** [comment]
> Apparently since the beginning the honor score you get for complete a beta kata...

The bonus points are a deliberate incentive to work with the Beta Kata:
* https://github.com/Codewars/codewars.com/wiki/Kata-Beta-Process#earning-honor-on-beta-kata

Revoking this bonus will kill off part of the reason to be bothered with Beta Katas at all. e.g.
* Why endure hassle of bugs and poor descriptions? (if get exact same reward waiting for the published Kata)
* Why risk totally wasted time/effort for zero reward? (if the Kata is ultimately retired)

We need more users to want to participate in Beta process; not less.

**Comment by Voileexperiments** [comment]
> Why risk totally wasted time/effort for zero reward? (if the Kata is ultimately retired)

A kata is retired if it has serious problems (e.g duplicate, totally broken, or abyssmal quality). It should've been our duty in the first place to catch these problems and raise issues at the kata. In this case all of us should've known that the reward is zero in the first place, so the point is moot.

Also, if everyone else is done properly, there shouldn't even be lots of katas that get retired in the first place for this to be significant.

> Why endure hassle of bugs and poor descriptions? (if get exact same reward waiting for the published Kata)

Again, the point of beta is not *to get honor points*, but to fix possible kata issues before it goes out of beta. You're not supposed to *endure* them. You're supposed to raise issues at poorly done things that are either just plain wrong, or are clearly hindering you/people from completing the kata.

Also, if a kata is like that, it'd get a low satisfaction rating highly unlikely to be able to get out of beta (and possibly even retired) anyway, so it goes back to the above. And if doesn't get a low satisfaction rating when this happens, you need to lecture the people how to do the beta process properly instead.

> We need more users to want to participate in Beta process; not less.

Not before people understand what beta process meant, and how important this is. If I (or someone else) can pick up like an average of 1 additional issue per kata, that's not enough. What the [base91 encoding/decoding kata](https://www.codewars.com/kata/base91-encoding-and-decoding) told us is that if you only focus on the honor points and not incentive, people will solve them in the fastest way, vote `very satisfied`, then run away without pointing at any of the glaring problems. Then the kata becomes approvable, and *someone will do it at some point*.

---

After all, this goes without saying, but the incentive to do beta *other than the honor points* is ultimately what's important. In fact I don't even think most of us make/do katas for the honor points. We craft katas because we know someone will solve them, and we do other's (great) katas because we know we'll learn something out of it. **This** is what CW is.

In fact, if the honor points *is* the ultimate incentive the fastest way to do is, of course, cheating, and most power users around already know like a dozen of ways to do that; and shitposting new betas too, but that's not fun either (in fact it takes lots of effort). But that's not fun at all.

By the way, if you apply the same mindset in StackOverflow it's called rep whores, and lots of people hate rep whores because they don't actually do lots of useful things besides trying to amass more reps.

**Comment by jhoffner** [comment]
> Honor score for a beta/published kata should be revoked 

Why revoked? Did they do something wrong? No, they did their job, why do they get penalized? I could maybe understand your argument more if you thought we just shouldn't give honor for this action in the first place, but why give it and then revoke it? Seems like we would be saying "thanks but no thanks" to me.

> It should've been our duty in the first place to catch these problems and raise issues at the kata. In this case all of us should've known that the reward is zero in the first place, so the point is moot.

I don't get the assumption that we should have known the reward would be zero. That's the entire point of getting honor for doing a beta kata - that you are taking time to work on something unproven, and that in the end it might never make it out of beta. So you get a very small reward for doing the honorable thing and helping us vet some content that may or may not be good. 

> Also, if everyone else is done properly, there shouldn't even be lots of katas that get retired in the first place for this to be significant.

You also mentioned approved kata. Are you saying only retired kata should be revoked?

> After all, this goes without saying, but the incentive to do beta other than the honor points is ultimately what's important.

Sure, I agree - though aren't you just kind of arguing that we just shouldn't have honor points at all then? It's not about points, it's about a sense of progression that keeps people going, and while the intrinsic value here is learning and getting better, the extrinsic value is that sense of moving forward, of seeing that you are actually getting somewhere - and CW doesn't have courses or tracks, so Ranks and Honor are what you get. Some people care about honor, some don't - but those who care, are going to feel extrinsically (honor) and intrinsically (growth) rewarded for doing beta kata.

> Obviously, this gives a disadvantage to later users - they don't have as many beta katas to do as the earlier ones because these katas have already been approved.

Isn't every new user at a disadvantage? The argument here kind of seems like starting a track race 30 minutes after someone else did and then being concerned that the starting point on the outer lane is 2 feet further back than it should be. Who cares, you are 30 minutes behind already what does an extra 2 feet matter?

Unless people suddenly stop making new kata, there is pretty much new beta content every day (sometimes lots of new kata). There is a steady stream of beta kata available to get those specific points on, and if you keep going, and someone who started before you doesn't keep it up, then you will eventually catch up.

**Comment by Voileexperiments** [comment]
> Why revoked? Did they do something wrong? No, they did their job, why do they get penalized?

It's because if honor is served as a metric that *accurately* represents the "score" of a user, like rep in StackOverflow, then it should be something that's actually accurate. It should be updated as the status of the katas are updated. The users are not really "penalized": yes, they did nothing wrong, but as the saying goes, "times change"; and since there aren't lots of katas that needs to be retired or re-ranked anyway (there *shouldn't* be, right?), it's not going to be a big deal after all.

At least, if I look at the total honor at the "completed katas" and check with the amount of actually completed katas from the user's site events, they should match up. Currently they don't because of dangling beta kata score and #1112. This makes it impossible to gauge things based on the honor score. 

Note that draft and retired katas are entirely unlisted so who knows how many of them are around. Technically someone can keep publishing non-functional beta katas briefly while another account solves them during this short time period, to gain lots of edges over everyone else. This would be a serious vulnerability (even if it's a *really* slow one).

> You also mentioned approved kata. Are you saying only retired kata should be revoked?

What I mean is the honor score for approved katas should be re-calculated if it's re-reanked, i.e #1112. This will pose a problem if we actually begin re-ranking the old katas to match up with the overall ranking of other katas.

Basically, these actions should re-calculate the honor score:

- Beta kata approved: should not leave the beta score for the kata around
- Beta kata retired/unpublished: same as above
- Published katas retired: revoke the honor score for kata, both for "finished approved kata" and "finished beta kata"
- Published katas re-ranked: re-calculate the honor score, add/subtract if necessary

Note that the authors are already getting `-1` honor for unpublishing a kata, so it *already* has been done. Why not for the solvers of the katas too?

> Unless people suddenly stop making new kata, there is pretty much new beta content every day (sometimes lots of new kata). There is a steady stream of beta kata available to get those specific points on, and if you keep going, and someone who started before you doesn't keep it up, then you will eventually catch up.

Except it doesn't: there are currently only ~2200 betas, and very old users (like smile67) has beta scores for ~3000 betas. It'll never catch up even if you finish *all* the betas.

**Comment by Blind4Basics** [comment]
doing a beta kata, the only extra points you get if the kata is published are the point for the rank estimation and the one for the satisfaction rate. Meaning, doing beta 7 kyu, you got 5 pts (iirc) with ranking and up/down vote. Then published: you gain nothing more since an approved 7 kyu is 3 pts. Same applies for other colors. 

So yes, those ones that are retired, you got extra points. But I don't see any problem with that since those that were retired, you has to suffer them, and the other should be published any way, even if in a long time. Sure, for someone like you, who do so much betas kata, that's a lot of points, though. ;)

About the "competence", I believe that any warrior know that neither honor nor kyu rank are really representative of anything if not "high/long frequentation" of CW, since one can cross path with guys 1 kyu in 1 month and other, well,  reaching the same level just be scrapping low level katas during a long period.

**Comment by jhoffner** [comment]
> Currently they don't because of dangling beta kata score and #1112

Scores should be getting updated. I haven't looked into that, but its a bug if its not working. If it isn't working, its probably because the site has grown so much recently - it definitely used to work. 

> This makes it impossible to gauge things based on the honor score 

OK but that's a separate issue. If you need to gauge things and they are hard to gauge, then that can be addressed directly. It sounds like in part this request is about trying to fix that in some sort of indirect way. They are different issues, one shouldn't be done to fix the other.

Also honor earned for completing a beta kata is its own event: "Beta code challenge completed". It doesn't get combined into any other event count so I don't follow why its an issue anyway.

> Beta kata approved: should not leave the beta score for the kata around

I feel like you have a different view on why points are earned for completing a beta kata. That honor is not there as some sort of placeholder for the honor you will get once we know the ranking. The beta honor is its own thing. It's there to reward you for doing a beta kata while it is in beta. It doesn't matter what happens to that kata, absolutely nothing that happens to it matters, what matters is that you got rewarded for proving that the kata could be completed, while it was in beta. 

> Note that the authors are already getting -1 honor for unpublishing a kata, so it already has been done. Why not for the solvers of the katas too?

Because you are undoing something that you did, so you get points taking away. In this case, no one is undoing the fact that you solved a kata while it was in beta. 

> Except it doesn't: there are currently only ~2200 betas, and very old users (like smile67) has beta scores for ~3000 betas. It'll never catch up even if you finish all the betas.

Sure you will, if smile67 lets up. You will do all 2200 beta kata, and then by the time that happens, there will be a bunch more, and you will do those. If smile67 keeps doing them all, then yeah, you will never catch up. Same thing goes for earning honor for ranking a beta kata. Similar thing goes for translations, there are only so many languages left to be translated and once its translated thats it for that language on that kata.
