### ISSUE TITLE
Getting 500 on kata pages loading

### ISSUE THREAD

**Issue by iCoderXXI** [Codewars/codewars.com#1332]
Hi! 

https://www.codewars.com/kata/duplicate-encoder
https://www.codewars.com/kata/take-a-ten-minute-walk
https://www.codewars.com/kata/bit-counting

These pages are loading very slowly, have to reload several times because of getting 500 http error on them.

**Comment by Swivelgames** [comment]
Yeah, there's something funky going on right now. I've been told by three different people separately that they can't access Codewars.com due to 500's. I'm running into the same issue as well.

**Comment by anter69** [comment]
It's a general issue, most probably some backend server problems.

**Comment by anter69** [comment]
@kazk how about closing all similar, earlier issues concerning general network/server problems?
#1042 #1090 #1143 #1155 #1156 #1192 #1201 #1239 #1241 #1262 #1275 #1277 #1286 #1288 
(and probably more)

---
Also, as these issues are reoccurring, it would be useful to create some kind of a "pinned" issue, with a short explanation, like:
- before creating a new issue, do a search
- make sure your code is efficient and remove all "print" statements
- just wait a little (or a bit more) and resubmit your solution
- for kata edits/updates try the preview server
- etc

**Comment by kazk** [comment]
@anter69
I'd love to close duplicate issues and most of the old issues (there're some from 2015!), but I simply don't know the Codewars codebase enough (to be sure if those are related and/or resolved).
I joined Qualified recently and became responsible for the code execution service that Qualified and Codewars uses so I don't know much about anything else. I'm just doing what I can between my tasks because I do want to improve this situation and help resolve issues that Codewars users are experiencing.

---

[ISSUE_TEMPLATE.md](https://github.com/Codewars/codewars.com/blob/master/.github/ISSUE_TEMPLATE.md) can be improved (PRs are welcomed). Maybe we can add check lists:

- [x] searched for existing issues
- [ ] ...

Many people don't read that either, so I want to eventually force consistent structure and automatically close issues that doesn't follow. But I don't have the time for it at the moment.

**Comment by anter69** [comment]
@kazk 
I scanned through most of those issues and clicked on links mentioned as "broken", "not working", etc. I could open all of them, so those must have been temporary network issues, which do happen with CW, but are not permanent (fortunately).

Others are rather vague, like "I get a server timout every time", dating from months ago, so there is no added value in keeping them.

Oh, and you could close this issue as well :wink:

**Comment by kazk** [comment]
Closing this issue as resolved.

**Comment by apollowebdesigns** [comment]
@kazk looks like this issue is still open https://www.codewars.com/kata/latest/my-languages

Currently the above link is showing this:

<img width="1223" alt="Screenshot 2019-04-23 at 06 49 15" src="https://user-images.githubusercontent.com/15857757/56557690-fe25d180-6593-11e9-8960-7a4fbe92ddee.png">

**Comment by kazk** [comment]
@apollowebdesigns that's a different issue related kata search (#1801) caused by one problematic kata.

**Comment by ggorlen** [comment]
Here's another one: `undefined method `permissible?' for nil:NilClass`.

![permissible](https://user-images.githubusercontent.com/17895165/59938491-fce51980-9409-11e9-9d85-dde12ab51083.png)

**Comment by kazk** [comment]
@ggorlen this issue was about timeouts if I remember correctly. Can you open a new issue with about `permissible?` error with a link to the kata?
