### ISSUE TITLE
Red users have double available RAM (and slightly better CPU) than non-Red users

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1343]
So, recently I discovered (via the help of @pochmann) that my own solution for [Mxyzinjin's Stream](https://www.codewars.com/kata/tap-into-mr-mxyzinjins-stream) times out pretty badly when run on non-Red users only, while Red users gets a consistent ~5s pass. Recalling that I've read about people trying to determine CPU model and total physical RAM of various OJ platforms not long ago, I tried to apply the same method on CW (runs on C++ language):

CPU model from cpuid, taken from https://zhuanlan.zhihu.com/p/28322626:
```
#include <stdint.h>
#include <iostream>
#include <cpuid.h>
static void cpuid(uint32_t func, uint32_t sub, uint32_t data[4]) {
    __cpuid_count(func, sub, data[0], data[1], data[2], data[3]);
}
void print_cpu_model() {
    uint32_t data[4];
    char str[48];
    for(int i = 0; i < 3; ++i) {
        cpuid(0x80000002 + i, 0, data);
        for(int j = 0; j < 4; ++j)
            reinterpret_cast<uint32_t*>(str)[i * 4 + j] = data[j];
    }
    std::cout << str;
}
```

Total physical RAM, code taken from http://nadeausoftware.com/articles/2012/09/c_c_tip_how_get_physical_memory_size_system:
```
/*
 * Author:  David Robert Nadeau
 * Site:    http://NadeauSoftware.com/
 * License: Creative Commons Attribution 3.0 Unported License
 *          http://creativecommons.org/licenses/by/3.0/deed.en_US
 */

#if defined(_WIN32)
#include <Windows.h>

#elif defined(__unix__) || defined(__unix) || defined(unix) || (defined(__APPLE__) && defined(__MACH__))
#include <unistd.h>
#include <sys/types.h>
#include <sys/param.h>
#if defined(BSD)
#include <sys/sysctl.h>
#endif

#else
#error "Unable to define getMemorySize( ) for an unknown OS."
#endif



/**
 * Returns the size of physical memory (RAM) in bytes.
 */
size_t getMemorySize( )
{
#if defined(_WIN32) && (defined(__CYGWIN__) || defined(__CYGWIN32__))
	/* Cygwin under Windows. ------------------------------------ */
	/* New 64-bit MEMORYSTATUSEX isn't available.  Use old 32.bit */
	MEMORYSTATUS status;
	status.dwLength = sizeof(status);
	GlobalMemoryStatus( &status );
	return (size_t)status.dwTotalPhys;

#elif defined(_WIN32)
	/* Windows. ------------------------------------------------- */
	/* Use new 64-bit MEMORYSTATUSEX, not old 32-bit MEMORYSTATUS */
	MEMORYSTATUSEX status;
	status.dwLength = sizeof(status);
	GlobalMemoryStatusEx( &status );
	return (size_t)status.ullTotalPhys;

#elif defined(__unix__) || defined(__unix) || defined(unix) || (defined(__APPLE__) && defined(__MACH__))
	/* UNIX variants. ------------------------------------------- */
	/* Prefer sysctl() over sysconf() except sysctl() HW_REALMEM and HW_PHYSMEM */

#if defined(CTL_HW) && (defined(HW_MEMSIZE) || defined(HW_PHYSMEM64))
	int mib[2];
	mib[0] = CTL_HW;
#if defined(HW_MEMSIZE)
	mib[1] = HW_MEMSIZE;            /* OSX. --------------------- */
#elif defined(HW_PHYSMEM64)
	mib[1] = HW_PHYSMEM64;          /* NetBSD, OpenBSD. --------- */
#endif
	int64_t size = 0;               /* 64-bit */
	size_t len = sizeof( size );
	if ( sysctl( mib, 2, &size, &len, NULL, 0 ) == 0 )
		return (size_t)size;
	return 0L;			/* Failed? */

#elif defined(_SC_AIX_REALMEM)
	/* AIX. ----------------------------------------------------- */
	return (size_t)sysconf( _SC_AIX_REALMEM ) * (size_t)1024L;

#elif defined(_SC_PHYS_PAGES) && defined(_SC_PAGESIZE)
	/* FreeBSD, Linux, OpenBSD, and Solaris. -------------------- */
	return (size_t)sysconf( _SC_PHYS_PAGES ) *
		(size_t)sysconf( _SC_PAGESIZE );

#elif defined(_SC_PHYS_PAGES) && defined(_SC_PAGE_SIZE)
	/* Legacy. -------------------------------------------------- */
	return (size_t)sysconf( _SC_PHYS_PAGES ) *
		(size_t)sysconf( _SC_PAGE_SIZE );

#elif defined(CTL_HW) && (defined(HW_PHYSMEM) || defined(HW_REALMEM))
	/* DragonFly BSD, FreeBSD, NetBSD, OpenBSD, and OSX. -------- */
	int mib[2];
	mib[0] = CTL_HW;
#if defined(HW_REALMEM)
	mib[1] = HW_REALMEM;		/* FreeBSD. ----------------- */
#elif defined(HW_PYSMEM)
	mib[1] = HW_PHYSMEM;		/* Others. ------------------ */
#endif
	unsigned int size = 0;		/* 32-bit */
	size_t len = sizeof( size );
	if ( sysctl( mib, 2, &size, &len, NULL, 0 ) == 0 )
		return (size_t)size;
	return 0L;			/* Failed? */
#endif /* sysctl and sysconf variants */

#else
	return 0L;			/* Unknown OS. */
#endif
}

#include <iostream>
void print_memory_size() {
    size_t memorySize = getMemorySize();
    std::cout << memorySize << '\n' << (memorySize/1048576) << "MB";
}
```

And what I got is pretty surprising:

CPU model:
- Non-Red users: `Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz`
- Red users: `Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz` or `Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz ` (it seems that both appears 50% of the time)

Total physical RAM:
- Non-Red users: `2093498368` or `1996MB`
- Red users: `4139909120` or `3948MB`

I wouldn't say it'd be a noticable advantage for Red users to have a slighter better CPU (I assume it's so), but *double availabe RAM*? This is giving Red users a huge edge over non-Red users. And as the kata mentioned above has shown, once you're in certain very memory-heavy katas, this will matter *a lot*.

**Comment by kazk** [comment]
Red users have 2 vCPU and 4 GB Mem, non-Red users have 1 vCPU and 2 GB Mem.
(I think the subscription page lists this as one of the features.)

Note that these are the numbers of the host VM and not equivalent to the amount of resources allowed in containers.

By the way, if you just want general information, you can simply do
```ruby
puts `cat /proc/cpuinfo`
puts `cat /proc/meminfo`
```

---

This is one of the reasons I refactored the entire service and rebuilt the infrastructure.

With previous design, there's no way to make much resources available to non-Red users because of the cost. Even Red users don't have dedicated CPU cores. They're shared and throttled depending on the usage history of the instances.

And those numbers alone doesn't mean much because there're many other containers running at the same time that shares resources. The amount of available memory varies significantly because of the way the system is set up.


I don't know the history since I joined this year, I'm guessing that as the number of supported language increased and more advanced Kata authored, this became a bigger problem.

The new system is much more cost effective and improves this situation. I can't guarantee the exact number at the moment because I'll be tuning it, but it currently runs on VMs with 4 dedicated cores (`cat /proc/cpuinfo` on preview should print 4 cores). The VM is dedicated to running submitted code.

**Comment by kazk** [comment]
Closing this because this is not an issue. Feel free to keep posting though.
With the new runner, both non-Red and Red users' code are executed on machines with same amount of resources. The CPU model can vary depending on the data center location, but there shouldn't be any significant performance differences.
