### ISSUE TITLE
Feature request: further deduping of kata solutions

### ISSUE THREAD

**Issue by leerssej** [Codewars/codewars.com#1399]
Would it be possible to improve the clustering of the solutions?
Maybe consolidation could help make it easier for folks to rank the solutions?

Not that I really know what I am talking about here, but could minifying the javascript solutions and mastering on that possibly be an easy way to make some fast gains on this?

Thanks again for a really great site!

**Comment by anter69** [comment]
Same as #889

**Comment by leerssej** [comment]
derp. my apologies. 
I swear I dug and searched through the issues for a good 20 mins. 😞 

Thank you!

**Comment by anter69** [comment]
You may close the issue then

**Comment by leerssej** [comment]
Is that  `help wanted`  tag applied to the #889 an open or an internal request?

**Comment by jhoffner** [comment]
We have an advanced code matching solution in the works for Qualified, but for CW IDK how far we want to go (at least for solution grouping). The reason is that there is code plagiarism, and then there are best practices. Best practice wise, someone could be grouped with another set of code that is basically the same thing, but poorly constructed. 

With that said, it would be interesting to group them and then have voting from within the group for the best example of that pattern.

**Comment by Voileexperiments** [comment]
@jhoffner Currently the displayed code for every solution groups is always the first solution inside the group, which is not ideal because the quality of the first submitted solution could range from anything. Is there any ways to change that?

**Comment by jhoffner** [comment]
> Is there any ways to change that?

@Voileexperiments Not at the moment. I'd like to introduce voting for which one best represents the best format of the group, which would also allow us to more aggressively group code.
