### ISSUE TITLE
Cannot delete account

### ISSUE THREAD

**Issue by bkaestner** [Codewars/codewars.com#140]
While I'm not interested in deleting my account at the moment, I've noticed that there's no functionality provided for this (yet). Some things that one needs to consider:

- what happens to the profile page?
- what happens to the user name? (e.g. rename to userID...)
- what happens to contributed content?

**Comment by osartun** [comment]
:+1: 
I actually just wanted to delete my account as I'm not actively using codewars and didn't find any possibility to do so

**Comment by jfmercer** [comment]
I too would like to delete my account.

**Comment by udavPit** [comment]
Yes, this is "must have" feature

**Comment by nicolaiarocci** [comment]
+1

**Comment by jhoffner** [comment]
Part of this issue with this feature is that we can't delete the solutions. It's content at that point and too embedded within everything else to pull apart. 
Best we can do is deactivate the account, prevent login and viewing of the profile page

Sent from Outlook Mobile




On Tue, Jan 12, 2016 at 9:17 AM -0800, "Nicola Iarocci" <notifications@github.com> wrote:












+1

**Comment by bkaestner** [comment]
> Part of this issue with this feature is that we can't delete the solutions

That's strange. I would have guessed that the solutions where in another table and not part of the user document. Is your whole database document driven? Apart from the forums, all content is more or less relational (and the comments are somewhat relational, given that a comments have only a one level hierarchy), so that seems kind of strange, given that all your data follows a (somewhat) fixed scheme.

Either way, I think one could tackle the issue with the following steps:

- Disable email notifications (including Intercom), either via options, or via a special flag
- Replace user name with `user<UserID>` (done by StackOverflow and others)
- Remove user profile picture
- Remove any link to external profiles
- Remove clan
- Remove skills
- Remove mailing address (or save it for some grace period, for example if there were legal issues with content; if you do this, notify the user that some of they personal data is being hold back)
- Make user's katas editable by any of the high honour users
- Remove user page (optional)
- Don't remove any solution, comment or kata

**Comment by jhoffner** [comment]
> That's strange. I would have guessed that the solutions where in another table and not part of the user document. Is your whole database document driven?

Yes we Mongo as our DB so it is all document driven. Solutions are in their own collection, thats not the problem. The solution groupings however are denormalized into the kata documents and its hard to go through and try to pick through where they are grouped and ungroup and whatever else we would have to. Thats problem one. Not unsolvable, just a lot of complexity in an area that already has too much. The 2nd problem is that deleting the solutions causes other usability issues. Deleting other user's comments, possible references, etc - so at the very least we would want to orphan those solutions from their user, but then that will likely be a good amount of work and regression testing to make sure the system can handle missing user references. 

Same issue for comments, if we delete the user, can't delete the comments because there might be an entire thread attached from other commenters. 

Everything else you mentioned sounds good. The profile page would either just be a 404 or a page that indicates the user deleted their profile. We would also remove them from the leaderboard and any ally relationships.

**Comment by jhoffner** [comment]
This has been deployed
