### ISSUE TITLE
Automate the enabling of new language versions to katas

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1421]
A follow-up to #1336:

Since the beginner of time, every time a new language version becomes available (e.g Node 6/8, Python 3.6, ...) lots of katas are not updated on this, and a republish is required before the new language version is selectable at the trainer page. But compatibility check is done before deploy anyways, so they should be compatible to the new language version without doubt (at least in theory)...

Obviously, it's infeasible to manually updating every kata every time this happens, so can it be automated at server side?

**Comment by kazk** [comment]
For the new language versions added with the new runner, this was done. The new language versions are enabled if it was compatible. Not all languages are compatible across versions though (that's why we needed the new runner that supports multiple language versions).

I think we can do something similar for Node.js and Python. But I'm not sure how it was done, so I'll assign this to @jhoffner.

> But compatibility check is done before deploy anyways

Not until the new runner. There was no test for language version compatibility for existing contents before.

**Comment by Voileexperiments** [comment]
That doesn't seem to be what's happening though, e.g someone said today that [one of the old katas](https://www.codewars.com/kata/539ee3b6757843632d00026b/discuss#5ae1e2f6442d32bee7000073) didn't have Python 3.6 available, and yet when I open the kata editor the test passes in Python 3.6 without any changes. I then need to do a dummy re-publish again to enable it.

**Comment by kazk** [comment]
That's because Python 3.6 already existed.

**Comment by kazk** [comment]
I don't know the details of the script Jake ran, but if I remember correctly, only the new language versions introduced by the new runner was targeted.

**Comment by kazk** [comment]
Most languages should now have the latest version set as the default if it's compatible.
