### ISSUE TITLE
IndentationError in pre-entered code with tabs in editor

### ISSUE THREAD

**Issue by Melanol** [Codewars/codewars.com#1490]
This applies to Python (not sure about other languages).

Some authors/translators manage to enter tabs instead of spaces when entering code in editor, This results in IndentationError. I think it would be wise to make a code that would check all existing katas for tabs and replace them with 4 spaces. Also, doing this operation on newly submitted katas would be nice as well.

**Comment by FArekkusu** [comment]
Could you please provide a link or something where I can read that you're a good programmer because you're using spaces, and other people are bad programmers because they're using tab?

Issues are for problems with the site/servers/runner, not for "they're writing code in a different way" ~~or what's worse "I don't know how the editor works"~~. If you're so keen about spaces, rewrite the initial solution yourself, and **run sample tests before submitting**!

**Comment by Melanol** [comment]
When you press Tab in the editor, it adds 4 spaces.

**Comment by FArekkusu** [comment]
> And I lost my desire to make Codewars a better portal.

Were the issues you raised any useful/helpful though?

**Comment by Melanol** [comment]
I found a flaw, I reported it, I made a suggestion how to deal with it, and now I am a bad person. Nice community Codewars has.

**Comment by FiveCrayFish973** [comment]
@FArekkusu 

According PEP8 (python's style guide) : 
> Spaces are the preferred indentation method.

> Could you please provide a link or something where I can read that you're a good programmer 

Let's not talk about whether he is good or not since an issue is an issue regardless of who submits it. As far as I can see people are here to learn and one of the the best ways to learn is from your mistakes. Remember this is an educational platform.

Now to address @Melanol 

As I said before preferred indentation method is 4 spaces and this is exactly what Code Wars provides. The tab character doesn't actually add a tab but adds 4 spaces (which saves you from having to press the space key 4 times). So it should not (and doesn't) result in an indentation error unless they write code using some other text editor (Sublime text, Atom....) and use tabs and port it here. 

Could you kindly provide some examples kata's where you have faced this problem, this will help add more authenticity (and make your issue more likely to be addressed). 

I will be waiting a response from you.

P.S 
> Nice community Codewars has.

It reminded me of [master Yoda from Starwars](https://en.wikipedia.org/wiki/Yoda). Also don't change a community solely on the actions of a single person. I am sure he didn't mean to sound rude or anything.

**Comment by error256** [comment]
You can open kata issues in these cases. I can confirm that I've seen tabs in initial solutions enough times to get tired of opening kata issues each time myself. Although it's especially noticable in Python, if I'm not mistaken, tabs in solutions are still rendered as 4 spaces in some places and as 8 spaces in others.
