### ISSUE TITLE
Cheaters versus Great Minds Think Alike

### ISSUE THREAD

**Issue by nomennescio** [Codewars/codewars.com#1500]
I fully understand the desire to combat cheaters, but please be aware that on MANY occasions, after solving a Kata without cheating, my solution was either identical or near to identical an existing solution. As the number of solutions for a Kata grows, the probability of identical solutions increases.

**Comment by nomennescio** [comment]
Have a look at some of the 1 Kyu Haskell Katas which are very technical proof-like. Usually there is even only one solution. So I understand that there are classes of Katas for which cheating can be detected, but even higher level Katas might only have a very small solution space.

**Comment by kazk** [comment]
We're not treating non-original solutions as cheating at the moment because we can never be certain how/why it ended up being a duplicate solution.

In the future, we might consider flagging users if they have unusual amount of duplicated solutions compared to their original.

I'm going to close this, but feel free to continue the discussion.
