### ISSUE TITLE
1 dan rank and progress behavior / Opening of 1 Dan katas

### ISSUE THREAD

**Issue by Blind4Basics** [Codewars/codewars.com#1510]
Hi,

2 things here:

# 1) rank progress when being 1 dan:

I noticed that the % of progress given when solving kata when you're already 1 dan suffers what could be considered as a bug. The normal observed pattern is the following for every "kyu" rank user:

A user being at the rank "N kyu":
* solving a N+1 kyu kata gives 10% of progress in the language
* solving a N kyu kata gives 5%
* solving a N-1 kyu kata gives 2.5% 
* solving a N-2 kyu kata gives 1.25% (iirc, not sure anymore about this one)

Though, being 1 dan and solving a 1 kyu, you get only something around 1% (impossible to know exactly for now, not being over 90% in 1 dan level x) ). That's due to the rank 0 kyu that doesn't exists, I'd bet. But that feels unfair to any dan user, doesn't it? ;p

# 2) 1 dan level kata:

Well, it's about time, I believe, to open that field. There are already several katas that match what jhoffner/Voile talked about in #35. To those already quoted there, one can now add, I guess:

* multisize nonogram solver
* toBrainfuck

Even if still in beta, it's almost a shame to assign only 1 kyu to those, imo.

**Comment by kazk** [comment]
There's nothing unfair and it's not a bug. Solving a kata rewards the same amount of internal score regardless of the user's rank. It's just harder to make progress once you reach higher ranks. Also, your example progress % doesn't seem correct.

The rank progress is calculated like the following:
```
(score - rank_score[rank])/(rank_score[rank + 1] - rank_score[rank])
```
where
- `score` is the internal progress score of the user
  - can be found in `.ranks.score.overall.score` in `https://www.codewars.com/api/v1/users/:user` if you're interested
- `rank_score[rank]` is the score required to reach `rank`
  - max `rank` is 8 dan

Examples:

| user | kata | diff | progress % |
|:----:|:----:|-----:|-----------:|
|3 kyu|8 kyu|-5|0.0653|
|3 kyu|7 kyu|-4|0.0980|
|3 kyu|6 kyu|-3|0.2614|
|3 kyu|5 kyu|-2|0.6861|
|3 kyu|4 kyu|-1|1.7968|
|3 kyu|3 kyu| 0|4.8677|
|3 kyu|2 kyu|+1|13.1983|
|3 kyu|1 kyu|+2|35.8380|
|2 kyu|8 kyu|-6|0.0240|
|2 kyu|7 kyu|-5|0.0361|
|2 kyu|6 kyu|-4|0.0962|
|2 kyu|5 kyu|-3|0.2525|
|2 kyu|4 kyu|-2|0.6612|
|2 kyu|3 kyu|-1|1.7913|
|2 kyu|2 kyu| 0|4.8569|
|2 kyu|1 kyu|+1|13.1883|
|1 kyu|8 kyu|-7|0.0088|
|1 kyu|7 kyu|-6|0.0133|
|1 kyu|6 kyu|-5|0.0354|
|1 kyu|5 kyu|-4|0.0929|
|1 kyu|4 kyu|-3|0.2432|
|1 kyu|3 kyu|-2|0.6589|
|1 kyu|2 kyu|-1|1.7867|
|1 kyu|1 kyu| 0|4.8514|
|1 dan|8 kyu|-8|0.0033|
|1 dan|7 kyu|-7|0.0049|
|1 dan|6 kyu|-6|0.0130|
|1 dan|5 kyu|-5|0.0342|
|1 dan|4 kyu|-4|0.0895|
|1 dan|3 kyu|-3|0.2424|
|1 dan|2 kyu|-2|0.6573|
|1 dan|1 kyu|-1|1.7847|

---

For the second part, we should have a separate issue to discuss or continue in #35. I think Jake wants to make dan levels distinct rather than continuations of the kyu ranks.

**Comment by Blind4Basics** [comment]
oh, ok, thanks for the info. I only guessed the way the % were computed, with no that much data available (and wrong souvenirs in the middle, apparently). ;)
