### ISSUE TITLE
Invalid language versions are not disabled from language selection

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1530]
From: https://www.codewars.com/kata/59568be9cc15b57637000054/discuss#5b72d61587c59b34330000b4

So a new C# language version was added and, even though the new Mono 4.2.3 fails on the test fixture because of https://github.com/Codewars/codewars-runner-cli/issues/633, it is not disabled from the language selection, which causes lots of confusion.

Shouldn't language versions that cannot pass the actual tests be disabled automatically? I tried triggering re-validation and the language version is still enabled.

**Comment by kazk** [comment]
Yeah, this has been a mess. When I added C# 7.3, I tried to update all the compatible kata to use it by default (#1421), but the database didn't get updated due to some issues. Most of the ones with 7.3 enabled at the moment are those I fixed manually and republished. I didn't realize Mono was still enabled for those.
I'll look into how this works and try again.

**Comment by kazk** [comment]
It should be disabled now. We've validated and changed the default versions to most recent one available for compatible kata.
