### ISSUE TITLE
Javassist solutions for certain Kata's don't work. 

### ISSUE THREAD

**Issue by provector** [Codewars/codewars.com#1533]
Hi,

As in the topic I've noticed that "javassist" solutions for following kata's (one already made by other users) don't work, yet the solutions run fine in my local IDE. The passed javassist solutions should be pulled back as they are no longer valid.

https://www.codewars.com/kata/hack-22/
https://www.codewars.com/kata/psychic/
https://www.codewars.com/kata/bagels/

**Comment by kazk** [comment]
Already accepted solutions are not validated unless the kata is changed. Those solutions you saw probably worked when they're submitted and are no longer working because of some changes we made _internally_. Also, those solutions are using packages that happened to exist (dependencies of dependencies).

We _try_ to keep the environment consistent as possible, but we don't guarantee that we never change. And we won't be validating submitted solutions every time we update our system because that will be too expensive for little to no gain.

**Comment by provector** [comment]
Hey guys,

I think there's an issue with the way Java is handled in codewars as I found more people having exactly same issue, and that without javassist but using reflection: https://www.codewars.com/kata/interfacing/discuss , As I'm learning reflection now I tried this kata as well and a "default" plain code (provided by kata creator) fails miserably with same error as I seen in previously mentioned katas:

Note: /workspace/java/src/ClassHelper.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
/Vector.java:1: warning: Can't initialize javac processor due to (most likely) a class loader problem: java.lang.NoClassDefFoundError: com/sun/tools/javac/processing/JavacProcessingEnvironment

It seems to affect any kata's that require the use of reflection.
