### ISSUE TITLE
Not able to submit code

### ISSUE THREAD

**Issue by ArtoisGB** [Codewars/codewars.com#1557]
Hello, I am not able to submit my code. I pass tests but random test show it's failed. 
It happend on two Kata's and in one of them I pass the tests and when I submit I have fail both test (random and basic, but basic was done few second earlier).

First Kata: 
![kata1](https://user-images.githubusercontent.com/41448015/44851726-86501300-ac61-11e8-9241-048c5b71d741.png)

Second Kata:
(this with both failed test when I try Submit)
![kata2](https://user-images.githubusercontent.com/41448015/44851798-bf888300-ac61-11e8-87a7-89a91fcaa927.png)

![kata3](https://user-images.githubusercontent.com/41448015/44851850-eb0b6d80-ac61-11e8-9d3d-c60f6f2713c7.png)

my nick is : ArtoisGB
link to first Kata: https://www.codewars.com/kata/57faf7275c991027af000679
link to second Kata: https://www.codewars.com/kata/5b728f801db5cec7320000c7

Windows 10, Chrome 68.0.3440.106, on pc I have Java wersion 1.8 also I use IntelliJ IDEA.

Thanks for helping, Artur

P.S. I try to refresh web and put again code.

**Comment by FArekkusu** [comment]
Not a CW issue. Your code is simpy wrong and doesn't pass the tests.

**Comment by ArtoisGB** [comment]
But why I pass basic test and few second later when i try submit i fail same basic test

**Comment by Voileexperiments** [comment]
@kazk Please close the issue ;-)

This repo is not for kata inquiries, it's for *site* inquiries. Also if your code isn't passing the tests, review your code and reflect on yourself where you did wrong is the best bet. Declaring it as an *issue* and asking all over the place if the *kata* has issues will only make everyone hate you ;-)

> But why I pass basic test and few second later when i try submit i fail same basic test

Because there are more tests cases in the actual tests. Sample tests is a *sample*.

**Comment by ArtoisGB** [comment]
Ah, so sorry. I spend few hours (I am just learning) and I was sure it's smth wrong with test before I wrote here. So... I go spend next few hours in my cave... I mean home lol. 
Ty
