### ISSUE TITLE
Unfinished katas list contains retired and draft katas

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/codewars.com#1565]
^

It's pointless to include them there because there's no way to finish these katas anyway.

**Comment by newlomar** [comment]
Hey everyone, can we bring this topic to the table again?

**Comment by FArekkusu** [comment]
> there's no way to finish these katas anyway

The author may turn their kata into a draft only temporarily and republish it later. If you wish to have access to it in the meantime, drafts being automatically filtered out would be an inconvenience. Instead, it'd make more sense to add a `Show Draft katas` checkbox (probably having `false` as the default value since most drafts are never republished anyway) or something similar just in case anybody needs it.
