### ISSUE TITLE
More information required if test fails when using Dart.

### ISSUE THREAD

**Issue by JRosanowski** [Codewars/codewars.com#1570]
If I use Javascript I can use console.log to output test inputs, and even if I don't I can at least see the required output. It also looks like you might get information about which tests failed (I've never tried writing a Javascript solution). When I use Dart all I can see is "Test failed" and nothing else, and I can't print out test inputs. This makes it really hard to work out test requirements, or work out what you've done wrong.

**Comment by Voileexperiments** [comment]
Some JS katas don't show anything besides "Test failed" too because the tests used `Test.expect` instead of `Test.assertEquals`.

**Comment by kazk** [comment]
The output of Dart tests is very limited. It's based on the output of [JSON reporter](https://github.com/dart-lang/test/blob/master/doc/json_reporter.md) which doesn't include details of the failure. So I don't think it's possible to improve the situation unless we use something else. This was contributed and I haven't looked at it much so I might be wrong though.

There's also https://github.com/Codewars/codewars-runner-cli/issues/481 and I don't think it's possible for the same reason. I'm going to close this since this should be filed to https://github.com/Codewars/codewars-runner-cli and similar issue is already opened there.

Possible workarounds (for kata authors) are to write tests with informative names and to write something helpful to stdout inside the test case.
