### ISSUE TITLE
The site is performing/loading extremely slow.

### ISSUE THREAD

**Issue by prusso** [Codewars/codewars.com#1571]
A few things to check first:

Is the issue you are filing related to a specific kata?

If so then please file an issue on the discourse page of the kata. You can do so by creating a comment and marking it as an issue. Only issues related to site functionality should be filed here.

Is the issue you are filing related to how a specific language behaves when being executed?

If so then it will likely be better to file the issue on our [github.com/Codewars/codewars-runner-cli/issues](https://github.com/Codewars/codewars-runner-cli/issues) repo, which is where we have our open source code execution functionality. You also may want to look into forking that repo and fixing the issue yourself if you have the means.

Otherwise delete all of this text and file your issue. Make sure to include steps to reproduce the issue, including which pages/kata you found the issue on, and your Codewars username if its related to your account.

**Comment by kazk** [comment]
Closing as duplicate of #1567. Please refer to that issue for future progress.

**Comment by astutulus** [comment]
After about four exercises, on different days, my patience is wearing out. I want to use this site but it is extremely slow and my day is wasted, watching it load / time out.

**Comment by astutulus** [comment]
After about four exercises, on different days, my patience is wearing out. I want to use this site but it is extremely slow and my days are wasted, watching it load / time out.

**Comment by Blind4Basics** [comment]
try to tackle harder katas. You'll spent hours on them without the need to load any other page. ;o

**Comment by VladimirRybalko** [comment]
+1 to the previous comments. 
@kazk the load is really slow. Could you please pay your attention?

**Comment by kazk** [comment]
Please avoid bumping an old issue that was closed as a duplicate. Especially with comments without any useful information.

Everyone knows it's been slow for years, it got even slower after a huge number of new users at the end of last month. I've explained the background in https://github.com/Codewars/codewars.com/issues/1784#issuecomment-513944396 if interested.

I'm planning to do a database upgrade (both updating database versions and increasing the resources) on 24th and hoping that will improve the performance little bit. This will be announced officially during this week because it requires at least few hours of down time.
