### ISSUE TITLE
Spoiler message can be read if they are listed in the notifications

### ISSUE THREAD

**Issue by bkaes** [Codewars/codewars.com#16]
If a user A submits a comment, and user B tracks the topic (e.g. a kata where user B has commented already), user B will get a notification with an excerpt, even if user A marked the comment as spoiler.

**Comment by jhoffner** [comment]
Yeah this was intentional. We figured its not so common that it was worth trying to add additional security around that flow (we already have so many complicated flows caused by security reasons). Generally it should be within context. If you post a root level comment, you will automatically track comments for that kata but only for a few days, then you become auto-unsubcribed to any additional notifications.

**Comment by bkaes** [comment]
Ok, this seems reasonable. Just checking whether that behaviour was intended.
