### ISSUE TITLE
Translation notifications not working so well

### ISSUE THREAD

**Issue by GiacomoSorbi** [Codewars/codewars.com#160]
I was notified with this via mail, no link or reference to the specific kata (that in my case it is not so easy to check:

![image](https://cloud.githubusercontent.com/assets/4815731/9166521/0282cf1e-3f53-11e5-8e6a-658220d9207d.png)

The notification on the site itself it is not much more useful:

![image](https://cloud.githubusercontent.com/assets/4815731/9166605/33b8dd08-3f53-11e5-843b-878f642422d6.png)

Once I click it, I get to a kata that I did NOT author and whose translations I cannot approve (I think the author would be ok with me doing it, as we formed a partnership on a series of katas, but then again I cannot do it); no idea if I have other translations pending on my own katas.

**Comment by bkaes** [comment]
So #141 isn't completely fixed at the moment?

**Comment by GiacomoSorbi** [comment]
Apparently not.

Recently I got notified about [YOUR translation](http://www.codewars.com/kumite/55c9b582f2cc70ba66000036) being approved, not mine...

**Comment by jhoffner** [comment]
Yeah I guess that doesn't make sense. I had turned on notifications for published translation to kata that users have contributed to, so that they can provide feedback on the translations (and I'm thinking that those with X amount of honor would also be allowed to approve them). However being notified about approvals doesn't really provide any value. 

I'm going to push out a fix for the approval emails and missing content soon. What are your guys thoughts on getting "published" notifications for kata you have contributed to?

**Comment by bkaes** [comment]
> What are your guys thoughts on getting "published" notifications for kata you have contributed to? 

Hm. That would probably kill @GiacomoSorbi's inbox. An option to _manually_ (un)subscribe/(un)watch a topic however would be great (also, a little bit more fine control, e.g. notify only on comments on the same comment/thread instead of kata…).

**Comment by jhoffner** [comment]
OK, I'm deploying fixes now that should do the trick. I'm going to close for now but its hard to test these things so @GiacomoSorbi please just let me know next time you get an email. I've turned off co-author notifications

**Comment by GiacomoSorbi** [comment]
Notifications work quite well, on sight, the only thing is that I get a basically empty mail (no link or author) to notify me; not sure if it wanted and in case I don't know why:

![image](https://cloud.githubusercontent.com/assets/4815731/9427723/955bf7a0-498c-11e5-8e1f-1a3a59d7055d.png)
