### ISSUE TITLE
Republishing a kata fails with 406 Not Acceptable

### ISSUE THREAD

**Issue by error256** [Codewars/codewars.com#1619]
This started happening yesterday with a specific kata: https://www.codewars.com/kata/55f8a9c06c018a0d6e000132

First I updated CoffeeScript tests and republished the kata. Everything worked correctly (except that "Please wait while we publish" didn't disappear, but that's usual now), solutions were revalidated.

Then I updated tests in all other languages at once and tried to republish. Republishing started, but in 5 or 10 minutes changes didn't appear in Revisions. Maybe the request failed immediately, but I didn't look at the response then.

Then I decided to try updating tests in languages one by one. At this point this issue appeared.
When I open the kata editor, the language selector is red:
![redlang](https://user-images.githubusercontent.com/5375100/47963582-26019700-e03f-11e8-91a8-67e89a92eed1.png)
and Python is highlighted:
![redlang2](https://user-images.githubusercontent.com/5375100/47963839-79c1af80-e042-11e8-82e3-fb9d720428e6.png)
The only message in console is "missing metadata for fortran", but it's there in every kata and looks unrelated.
Whatever I do now, republishing always fails immediately with HTTP 406 (and in UI "Please wait while we publish" never disappears).

**Comment by kazk** [comment]
> I'm not sure about JavaScript yet

![image](https://user-images.githubusercontent.com/639336/47969569-3e1cea80-e02e-11e8-9405-cf9688ddb2da.png)

This wasn't related to JavaScript. It means that at least one language in that selector has error. So the only language with the error was Python. I've fixed this by making it Python 3 compatible.

I was able to republish after fixing this error so I'm still unsure why we got 406. It doesn't seem like it's related to the fix I did because I was able to republish after fixing it. I'll see if there's any difference to submitted data if there's an error.

**Comment by kazk** [comment]
Looks like we get 406 even when the republish succeeds. This is probably why https://github.com/Codewars/codewars.com/issues/1613 started to happen.

**Comment by kazk** [comment]
> Python has `default_version` set to `2.7`, but `2.7` is not in the list of `supported_versions`.

Just to be clear, this `supported_version` only applies for Python for this specific kata. Codewars still supports 2.7.
For some unknown reason, Python's `supported_versions` for this kata only had `3.6` even though it wasn't compatible with Python 3 and made the `default_version` invalid. I made it Python 3 compatible because that was the easiest way to fix this data issue.
