### ISSUE TITLE
"Multiply" can't be opened after translation approval

### ISSUE THREAD

**Issue by error256** [Codewars/codewars.com#1630]
I approved a translation of [Multiply](https://www.codewars.com/kata/multiply) about 70 minutes ago and the kata has been returning "Request ran for longer than 45000ms" since then. The sign-up page doesn't seem to be affected.

**Comment by error256** [comment]
Here's the translation: https://www.codewars.com/kumite/5bf5c4c30934aa20b800010c?sel=5bf5c4c30934aa20b800010c

**Comment by error256** [comment]
It works now.

**Comment by kazk** [comment]
This happens when a new language is added to a kata with lots of solutions. Each language in a kata have `total_completed` field that gets incremented when a user completes the kata in the language.

The value is initially set to `null` for some unknown reason and this will make the app to calculate the number by going through the solutions, which is often very time consuming with current database design.
The error goes away once it succeeds to calculate in time.

Some pages like trainer for other languages and discussion are unaffected because those don't need this value set for the new language.

It's one of the WTFs I've filed to internal issue tracker.
