### ISSUE TITLE
JS: All test assertion functions now shows the input by default

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1642]
Apparently now every test assertion functions show the input by default, including `Test.assertEquals` and `Test.assertSimilar`.

This means that all the performance katas that tests between two massive objects/arrays will break because the amount of stdout output will terminate the process. The numbers are at least in the hundreds.

**Comment by Voileexperiments** [comment]
Related: https://github.com/Codewars/codewars-runner-cli/issues/599

**Comment by kazk** [comment]
What do you mean by "now"? cw-2 hasn't changed.

By the way, Node 10 will be added soon and it'll remove cw-2. To make the transition smooth, assertion methods under `Test` are still provided. So many of the existing contents will work without any change. If tests are not using `describe`/`it`, it needs to be updated in order to use Node 10. Node 8 will continue to work the same way.

The test framework will be Mocha under the hood with cw-2 style assertions. Users can now use assertion libraries like Chai. Assertion methods under `Test` are now just wrappers for Chai.

This will resolve most issues with cw-2.
