### ISSUE TITLE
Recent Changes 2018-12-xx

### ISSUE THREAD

**Issue by kazk** [Codewars/codewars.com#1647]
I'm going to start announcing Codewars changes, using issues for now. I'll close this when I post a new one.

Feel free to post comments here if you have any questions about the changes.

#### New Languages

- Add PureScript
- Add Elm

Please try/translate them and let me know if you find issues.

#### New Language Versions

- Add OCaml 4.07
- Add Lua 5.3
- Add Node.js 10.x (**unreleased**)
  I've decided to drop the custom test framework cw-2.js and use [Mocha](https://mochajs.org/) under the hood.
  Assertion methods with the same name are still provided to make the transition smooth. They're just wrappers around [Chai](https://www.chaijs.com/).
  You can use Chai directly for better assertion methods and use [fast-check](https://github.com/dubzzz/fast-check) for property based testing.
  Existing contents should be compatible as long as the tests are written using `describe`/`it`. There's no change to Node 6/8 so incompatible ones can continue to use older versions of Node for now.
  When this is released, I'll run a script and update compatible ones to use Node 10. Then create a list of incompatible ones similar to what [we did](https://github.com/Codewars/codewars.com/wiki/List-of-Affected-Kata) when switching to the new runner.

### Codewars

- Lots of bug fixes, reducing technical debts, and minor performance improvements
- Major framework/dependency upgrades

**Comment by Voileexperiments** [comment]
> Existing contents should be compatible as long as the tests are written using `describe`/`it`.

Is it possible to make mocha not polluting the global space with all its test methods? Dropping tons of functions into global scope is problematic because they can easily collide with user defined variables, as well as providing extra vectors of vulnerabilities (e.g it's *still* possible to call test assertion methods in user code).

Maybe something like [this](https://github.com/mochajs/mocha/wiki/Using-mocha-programmatically), but apparently it's only available [when the JS file is run via mocha binary](https://github.com/mochajs/mocha/issues/956). [Looking further into this](https://github.com/mochajs/mocha/issues/2765) kinda makes me want to drop mocha altogether and use something better-designed and which the devs are more open-minded to users.

Or, at least, wrap mocha into a module that exports all its functions into a namespace, and then import *that* module?

**Comment by Blind4Basics** [comment]
I just checked some basic stuff in the preview site, about comments markdown:

* might be unrelated but in preview mode, the redaction panel is missing the first character of each line.
* the code blocks displayed as normal text when the message is posted while it appears as code block in preview seems to be there yet. At least, using backticks, that works, this time.
* the title markdown isn't "title" anymore (smaller than regular text in bold!)

see below:

* preview mode: 
![image](https://user-images.githubusercontent.com/32236948/50310103-4aa3b800-04a1-11e9-874e-31ff30ab6abe.png)

* posted:
![image](https://user-images.githubusercontent.com/32236948/50310145-6444ff80-04a1-11e9-9266-a6ba51613b55.png)

**Comment by kazk** [comment]
Thanks for testing @Blind4Basics.

> - might be unrelated but in preview mode, the redaction panel is missing the first character of each line.

This seems unrelated and happens when writing new comments and not editing existing :/

> - title level 2 is smaller than regular text in the posted message... :/

This looks like a CSS issue. Some rule with higher specificity is making it smaller. I haven't touched the frontend yet and not looking forward to.

---

The markdown preview and the actual doesn't always match because two different engines are used (#1640). But I think it should be closer compared to before because the server side engine also follows Common Mark now.

I'll see if I can make the preview match the actual by adding some options. The server side one is not as configurable.

**Comment by hobovsky** [comment]
Some katas (for example [this one](https://www.codewars.com/kata/the-deaf-rats-of-hamelin/discuss) ) might have descriptions and/or discourse sections messed up because they use `~` character extensively. New markup engine introduces ~strikethrough~ markup, which was not present before, and `~` character got new meaning.

**Comment by FArekkusu** [comment]
Something is wrong with how comments are shown in different places. The upper part is how the comment looks on the dashboard, and the lower part is how it looks in the kata discourse.

![image](https://user-images.githubusercontent.com/31668662/50384118-e4997980-06c8-11e9-8709-9c6c672519de.png)

**Comment by kazk** [comment]
@FArekkusu is that from preview? I reverted the update because of some weird errors and haven't re-deployed yet. So if you saw that on production version then it wasn't introduced by the update.

The dashboard comments can be outdated because it's cached heavily. It looks like the edits were not reflected when you saw it.

Looks like the preview is showing comments from a day ago as newest for some reason. It was always less up to date compared to the production one but it looks like it's been stuck.

I might not work on this during holidays but I'll be back on Wednesday.

**Comment by FArekkusu** [comment]
@kazk no it was not from preview version. Must be a bug with the current comment system.
