### ISSUE TITLE
Repeated 500 errors trying to sign up

### ISSUE THREAD

**Issue by OHailwood98** [Codewars/codewars.com#1650]
#### Describe the bug
I get repeated 500 or 5XX errors when trying to sign upto the service

#### To Reproduce

1. Go to homepage
2. Click on Sign Up
3. Try to sign up

#### Expected Behavior

500 or 5XX errors
#### Contexts
Please complete the following information:

- OS: Win10
- Browser: Firefox
- Browser Version: [64.0]

**Comment by Arkweid** [comment]
Got this one after pressing "GitHub SignUp" button. Looks like sometimes GitHub return not enough data in OAuth response. At the same time, after reloading, I was logged in and did not get errors anymore.
![nil](https://user-images.githubusercontent.com/10600777/50307108-7ecea700-04a8-11e9-881c-882b707351c2.png)

**Comment by kazk** [comment]
Sorry about this.
It's a known issue (both 500 and timeouts) and there's no easy fix due to poorly written/maintained code.
We're also having some database issues.

The worst part of this issue is that it starts a vicious cycle:

1. Slow signup
2. Blocked connection leading to degraded performance for all users
3. Even slower signup

There was around 3000 errors related to this in the past 24 hours.

I started to work on fixing Codewars few months ago and I'm currently working on updating dependencies/frameworks to newer versions. Hopefully I can finish this soon and start working on performance issues including this.

**Comment by Mikie** [comment]
Same issue as above, any update on it?

**Comment by kazk** [comment]
Fixed this by making username uniqueness validation efficient. It shouldn't take more than few seconds now.

Please try again if you haven't already signed up. And please open a new issue if this happens again.

Thanks for your patience!
