### ISSUE TITLE
users with only Invalid Solutions should not be able to watch other users solutions

### ISSUE THREAD

**Issue by javatlacati** [Codewars/codewars.com#1704]
#### Is your feature request related to a problem? Please describe.

Yes, the first users in solving your kata sometimes try to cheat, having the knowledge that it will bring them with access to future correct solutions

#### Describe the solution you'd like
Hence I'd like that:

* users with only Invalid Solutions should not be able to watch other users solutions
* Delete user invalid solution once the valid one has been sent

**Comment by FArekkusu** [comment]
This is idea is just as nonsense as [the reason](https://www.codewars.com/kata/reviews/5c4e818ff6e6fd0001685507/groups/5c4eb9ec9688f800014670c7) why you're making this suggestion.

Firstly, nothing can stop the users from copy-pasting some other warrior's code and resubmit it simply to have access to the solutions page. Secondly, the majority of the users won't care about losing access to solutions page because they've already received their honor and rank points, and most probably they've already assessed the kata rank and satisfaction rating.

**Comment by kazk** [comment]
This requires to detect cheat immediately after submission and doing that makes everyone to suffer from even slower submission (it's already often too slow).

Users that cheat are just wasting their time and making legitimate users' experience worse for them doesn't make sense to me.
Cheaters will find solutions from somewhere as well.

> - Delete user invalid solution once the valid one has been sent

We're not deleting solutions, especially cheats.

**Comment by kazk** [comment]
Wait, it's not about cheating?
Either way, I'm keeping this closed because I don't see the point of doing this.

**Comment by Voileexperiments** [comment]
This is not recommended at all because it'd be very confusing (and it's *already* quite confusing now). If something needs to be done about this at least #57 should be done.
