### ISSUE TITLE
Kata translation in inconsistent state

### ISSUE THREAD

**Issue by suic86** [Codewars/codewars.com#1728]
1. I've created a JS version of [this kata](https://www.codewars.com/kata/ordered-count-of-characters).
2. The publishing ended with "Failed Tests" however there had been no failing tests.
3. The Javascript version is not visible in [Kata Editor](https://www.codewars.com/kata/57a6633153ba33189e000074/edit/javascript). When I insert the translation code directly to the Kata editor and run it, all tests pass but the result show that the tests failed.
4. When I try to publish a fork of the Kata it ends with the same issue.

**Comment by Bubbler-4** [comment]
I did a quick check by forking it. It didn't show any passed tests, which is considered as failure on CW.

What is `assert.deepEqual` thing by the way? I don't remember having used such an assertion before.

**Comment by kazk** [comment]
I don't know what's causing the original issue, but here's some information about Node 10 (I'll add to docs later).

> What is `assert.deepEqual` thing by the way?

For versions before Node 10, that's from assertion package shipped with Node. We include it by default.
From Node 10, we don't do that and we recommend using assertion methods from Chai.

Codewars assertions under `Test` are still usable (just wraps Chai), but not recommended for new tests.

> shows only first failed assertion per `it`

This is because we use Mocha instead of `cw-2` starting from Node 10. This is more standard behavior. `it` is required and that represents a test case. Codewars' custom frameworks are the only ones that relies on assertions for the output.

I'd recommend writing tests like the following:

```javascript

const fixed = [
  ["abracadabra", [['a', 5], ['b', 2], ['r', 2], ['c', 1], ['d', 1]]],
  ["Code Wars",  [['C', 1], ['o', 1], ['d', 1], ['e', 1], [' ', 1], ['W', 1], ['a', 1], ['r', 1], ['s', 1]]],
];

describe("Fixed Tests", function(){
  for (const [text, expected] of fixed) {
    it('text: ' + JSON.stringify(text), function() {
      assert.deepEqual(orderedCount(text), expected);
    });
  }
});
```

> doesn't support expected/actual tabs

Those tabs are from `cw-2` and we no longer use it. We can consider adding it as a new package if the community really need it. I don't know how difficult that can be yet.

If the deep equality output is truncated, you can adjust `chai.config.truncateThreshold`.

**Comment by kazk** [comment]
For random tests with long input, using test case name is not ideal. You can log the input in that case inside each `it`.

```javascript
    for (let index = 0; index < 100; index++) {
      rs = randomString();
      it(`Random test ${index + 1}`, function(){
         console.log(`<LOG::-Text>${JSON.stringify(rs)}`);
         assert.deepEqual(orderedCount(rs), solution(rs));
      });
    }  
```

By prefixing each with `<LOG::-Text>`, you get the output in labeled container.

![image](https://user-images.githubusercontent.com/639336/52811587-526b7d00-304a-11e9-9ccb-4313e370de11.png)

The `-` prefix makes it collapsed by default.

We should document these better.

---

You can also use [fast-check](https://github.com/dubzzz/fast-check) from Node 10.

**Comment by suic86** [comment]
@Bubbler-4 thanks for fixing the tests. I approved your fork so the issue is _de facto_ resolved.
@kazk thanks for the feedback and the info about Node 10. I don't know what was the issue with original translations. However, it's weird that the issue only appeared on/after publishing.

**Comment by kazk** [comment]
It's still not working as expected :/

![image](https://user-images.githubusercontent.com/639336/52813957-d3794300-304f-11e9-9067-9225793b5f27.png)

I'll try editing in the kata editor.

**Comment by kazk** [comment]
Now it's working, but only Node v10.x is enabled. I'm not sure why it doesn't have Node v8.x

**Comment by kazk** [comment]
I'll close this for now, but please let me know if this happens again.

**Comment by suic86** [comment]
@kazk thanks
