### ISSUE TITLE
Error message links to broken status page

### ISSUE THREAD

**Issue by coryallegory** [Codewars/codewars.com#173]
When Running Tests or Submitting, it's possible for the user to be met with a "Nope Try Again!" output result with the following message:

"Submission timed out while communicating with our servers. This may infrequently happen if our servers are extremly busy. Please try again. If issues persist you can check status.codewars.com to see if server issues are being investigated."

When navigating to http://status.codewars.com/ I get an HTTP 406 error.

**Comment by paul-calvelage** [comment]
The timeout message still refers to [status.codewars.com](http://status.codewars.com/) rather than [codewars.statuspage.io](https://codewars.statuspage.io).  Attempting to reach the status page returns status of `HTTP/1.1 406 Not Acceptable` and a non-helpful error page.

```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>406 Not Acceptable</title>
</head><body>
<h1>Not Acceptable</h1>
<p>An appropriate representation of the requested resource / could not be found on this server.</p>
</body></html>
```

Probably the link in the timeout message should be updated, or the error page should redirect.

**Comment by kazk** [comment]
Closing this because both http://status.codewars.com/ and https://codewars.statuspage.io/ is working.
https://status.codewars.com (HTTPS) doesn't work and if this was the issue, let me know and I'll reopen.
