### ISSUE TITLE
Page with Kata not saving source code / incorrect

### ISSUE THREAD

**Issue by Acionyx** [Codewars/codewars.com#1753]
#### Describe the bug
I was training a Kata (https://www.codewars.com/kata/line-safari-is-that-a-line/train/javascript) for a while, i sent my code to server (made an attempt) few times. At some point there were 2 failed tests. So after that i decided to read discussions, pressed "Discuss" button, read them, pressed "Back" in browser and found that i lost all my code. Only very-very old version was presented in editor.
So, in fact, i lost my solution because i pressed "Discuss" button.
I've never seen such behaviour before when training other Katas.

#### To Reproduce

1. Write code
2. Press "Discuss"
3. Press "Back"
4. See no code / random old version in editor.

#### Expected Behavior

Latest version of my solution should be saved in editor anyway.

#### Contexts

Please complete the following information:

- Codewars username (if account related): Acionyx
- OS: macOS
- Browser: chrome
- Browser Version: 72

#### Question
Is there way to restore my code i sent to server? Really, no wish to write twice same code, after i almost completed this Kata.

**Comment by kazk** [comment]
Looks like this is a variation of [a bug](https://github.com/Codewars/codewars.com/issues/1683#issuecomment-456951790) where a user has multiple records for a kata. That bug is a huge mess from over the years and not easy to fix.

I can probably restore your solution by removing the duplicate record. To be safe, can you avoid this kata (don't open, submit, etc) while I take a look?

**Comment by kazk** [comment]
I've removed the duplicate record so it should load what you had.

**Comment by Acionyx** [comment]
Yes, you're right, it was a bug. Now everything is ok.
Thank you, i was not expecting such quick help :)
