### ISSUE TITLE
Performance evaluation

### ISSUE THREAD

**Issue by skaraman** [Codewars/codewars.com#1754]
#### Is your feature request related to a problem? Please describe.
Solutions should be evaluated on their performance as well as the other criteria, some 'clever' solutions are actually very slow and vice versa. Solutions voted as "Best Practices" might actually be slow but common method calls. Operations per second is really important for most code!

#### Describe the solution you'd like
The ability to run solutions against the test and see the operations per second or time operation took to complete.

#### Describe alternatives you've considered
Posting solutions into another benchmark tool.

**Comment by Voileexperiments** [comment]
This has brought up too many times before, so let's clean this up again:

(Note that I'm assuming you have JS background)

> Solutions should be evaluated on their performance as well as the other criteria

It sounds like you think `performance > other constraints`, which is far from true. It also sounds like you think `performance = runtime speed`, which is also far from true.

> some 'clever' solutions are actually very slow and vice versa. Solutions voted as "Best Practices" might actually be slow but common method calls

Are you assuming something here, like what these two labels called "clever" and "best practice" mean? How a solution fares has nothing to do with its votes. It's a popularity vote and frankly, it's mostly not instructive.

> Operations per second is really important for most code!

If you want the peak runtime speed, you should've been hand-writing wasm code instead of writing JS. That's always gonna be the fastest.

Also, are you aware of something called "memory"? Or "development time"? Or "ease of understanding" or "conciseness"?

> Posting solutions into another benchmark tool.

Are you talking about JSPerf? It's a joke and people don't even know how to write proper performance benchmarks on there. They also don't know anything about memory constraint.

---

I suggest you not to bother about this and instead write cleaner, more concise code. JS is not C code running in a Raspberry Pi and pursuing for micro-optimization is just pointless. You can't even get a consistent result anyway; for a JITted language there are too many factors affecting runtime. You're looking for the wrong thing.

**Comment by kazk** [comment]
@Voileexperiments there's no need to put JSPerf or its users down.

---

@skaraman Thanks for the suggestion, but we have no plan to add this.

Codewars is not suited for this.

To benchmark we need to at least:

1. execute with controlled input/environment
2. collect enough data for meaningful statistics

1 is difficult because Codewars' kata are created by the community and not standardized.
Setting up benchmarking for them will require significant effort and proper benchmark is not easy.

2 is simply very expensive. The code runs on our servers and not on users' browsers.

We have some kata that **requires** you to write fast code. In other words, any accepted solutions are considered _fast enough_ for the task.

**Comment by skaraman** [comment]
Ok it's your servers and your supporting many more languages then JS so I get that. Good luck.
