### ISSUE TITLE
Add some alias to language identifiers for code blocks

### ISSUE THREAD

**Issue by anter69** [codewars/codewars.com#1789]
I see a lot of inconsistent use of code blocks in kata descriptions (I have to admit, I did it myself, too ;-)

For example ` ```js` is often used, but it's not recognized/displayed/highlighted in the same way in the editor/description as` ```javascript`:

![image](https://user-images.githubusercontent.com/12795864/55548080-ff6d8800-56d2-11e9-9df4-fc1b20a32076.png)

Frequent offenders:
* `js` vs `javascript`
* `coffee` vs `coffescript`
* `py` vs `python`
* `c#` vs `csharp` (which is the right one?)

---

I suggest to add/enable these aliases (and maybe others), because fixing them otherwise would be impossible/an overkill.

**Comment by kazk** [comment]
The language identifier is the one used in the url (e.g., `javascript`, `python`, `coffeescript`, `csharp`, `cpp`, etc). Adding aliases will break filtering in the description if I remember correctly.

**Comment by anter69** [comment]
So the only option would be to scrape through all katas and find-replace the wrong references? Oh, and to educate the users... ;-)

**Comment by kazk** [comment]
Closing because we're not adding aliases.

> * `js` vs `javascript`: Found 202 and fixed 3
> * `coffee` vs `coffescript`: Found 5 and fixed all
> * `py` vs `python`: Found 44 and fixed all
> * `c#` vs `csharp`: Found 0. Found 1 `C#` and fixed it

Some of these seems to require having wrong id so that the text inside the code block is not filtered, so I'm not fixing them with a script. :man_shrugging: 

For example, I saw a kata with description

````markdown
```js
some text, not even JS code
```
```python
# python example
```
````
so I just removed `js`.

I made a wiki page listing kata with `js`. https://github.com/codewars/codewars.com/wiki/List-of-Kata-with-description-using-wrong-language-id

If you have other examples, I can search them as well.

**Comment by anter69** [comment]
> I made a wiki page listing kata with `js`. https://github.com/codewars/codewars.com/wiki/List-of-Kata-with-description-using-wrong-language-id

The link seems to be broken/deleted

**Comment by hobovsky** [comment]
The page was there, I remember seeing some updates to it, but it might be deleted because all affected kata were fixed.

**Comment by kazk** [comment]
Yes, it was deleted because all of them were fixed.
