### ISSUE TITLE
Make Pending Translations Easier to Find

### ISSUE THREAD

**Issue by kazk** [Codewars/codewars.com#1822]
#### Is your feature request related to a problem? Please describe.

It's difficult to find translations waiting to be reviewed.

#### Describe the solution you'd like

Provide a page listing all pending translations for some trusted users.

![image](https://user-images.githubusercontent.com/639336/57874901-79128e80-77c6-11e9-9903-a6ac8c3bc27b.png)

**Comment by aeros167** [comment]
This feature would be greatly appreciated, at the moment there's really no practical way to find pending translations. There's a lot of solid older kata on the website written in 1-2 languages at most with inactive authors, but when translations are made, they end up becoming stuck in an indefinite pending stage.

**Comment by hobovsky** [comment]
Well, if anyone is interested in my opinion, I have a really mixed feelings about this.

Some time ago I would think of it as a great and awesome idea. I even wanted to provide such feature outside of CW: I created [this sheet](https://docs.google.com/spreadsheets/d/1y5G6ECFnfCa18EZp2veNoncyLIxC2idSYeO0j2oiPeo/edit?usp=sharing), somewhat announced it, and hoped to visit it from time to time, maintain and update. But then the topic of kata quality came up and I started to have second thoughts.

Thing is that without any proper moderation, everyone with sufficient honor can approve a translation. And the honor limit is terribly low. Now there will be very easy way to simply display a list and approve everything from top to bottom, without even checking the translation throughly. And you know very well people will do this, because it happens now too, and only difficulty in finding a translation keeps the scale of the problem small. Who will review a C translation for proper memory management if there's only a handful of users familiar with this aspect? Who will check a C++ translation for missing includes if 90% of users just goes "it works on CW, so meh"? Who will approve an Elm translation if the only user familiar with the language authored it and there's no one else who could catch potential issues?

![lets approve](https://i.imgflip.com/315vwa.jpg)

I would love to have this feature, but only if it would be complemented by some means which would ensure the quality of approved translations: some kind of moderation, or granting the priviledge only to the language versions user is familiar with, or maybe requirement to be approved by more than one user, IDK.  Honor based priviledge proved not to be a guarantee of good quality. I think that at the moment such list will only introduce an easy way to introduce content of low quality into the site.

But yeah, just my opinion, and I hope time will prove me wrong. It's always nice to see some new features :)

**Comment by kazk** [comment]
@hobovsky That's a great point. I was going to do this since the page itself is low effort and we have 2397 (!) translations that's older than a week.

> some kind of moderation, or granting the priviledge only to the language versions user is familiar with, or maybe requirement to be approved by more than one user, IDK

I'll probably make this page only available to users we explicitly allow. I'll start with some users already proven to be trustworthy and have been approving translations responsibly.

**Comment by aeros167** [comment]
Yeah I would definitely agree with this page have limited access, especially at first. In the long run, a potential solution might be to require the user to have at least the skill level the original kata was in, for the language translation they're reviewing (perhaps 1 above) as well as the original language the kata was written in. So for example, in order to rate a C# translation for a  6kyu kata originally written in JS, a user would need 5kyu in both C# and JS. Perhaps that's overkill and only requiring the translation's language would be adequate, but IMO it's better to be on the safe side at first. 

As far as the lesser used languages go, personally I don't have a good solution for a correct manner to approve translations. Perhaps their could be "moderators" of sorts for given languages, so that these trusted individuals could approve or add solid translations by themselves. The moderator status would be not at all based on honor, instead it would be more focused on the individuals experience with a specific language and the testing frameworks. Personally I think that honor or language skill level can be a good indicator of activity, but it's not always an indicator of trustworthiness and moderation ability. This could also be applied to more popular languages as well, but it would benefit the less common languages the most. 

Another issue I'm starting to realize is that there's not much "incentive" at the moment for users to review kata translations. For new beta kata, there's quite a bit of reward available, which I think helps to increase motivation for people to test out new ones. Of course, the translation review process should not award much at all (since you don't have to solve the kata), but even throwing a 1 honor reward at people for rating it could provide some incentive. Perhaps it could require the user to be on the page for at least 30-60 seconds (so someone couldn't just spam approve translations w/o reading them over).

I think almost any system would be an improvement though, as at the moment it's entirely up to chance whether or not your translation gets attention. Currently, the most effective way seems to be to leave a suggestion with the link, and post the translation on the gitter chat, but otherwise there's not much to be done. For example, I have a C# translation that I wrote about 5 months ago (https://www.codewars.com/kumite/5c10abe23cff0d042e00008a?sel=5c10abe23cff0d042e00008a) which pretty much got buried. Zed left a comment (made the recommended changes) and it has just been sitting in a purgatory of sorts since then. I don't mind having to wait a bit for them to be voted on, but it does feel discouraging to spend some time working on a translation only for it to get stuck in purgatory forever.

**Comment by xavierguihot** [comment]
@hobovsky maybe based on the honor (percentile?) acquired on the language the kata is being translated to?

**Comment by hobovsky** [comment]
Actually I think that there's absolutely no point to search for ideas how to approach this problem, because... whatever we come up with, it's simply not going to happen :) Community might throw some ideas for good and bulletproof solutions, or quick, easy and "good enough" solutions, but each of ideas would require some support from the platform itself, and (as far as I am aware) there are no resources (people/time) to bring any new mechanisms into the platform.

**Comment by kazk** [comment]
Yeah, we can't do much. I'm the only dev at the moment and can spend about a day per week in total. The next big thing for Codewars is the database upgrade and I've been preparing for that. We still need to a lot of testing but it's mostly ready. We'll make an announcement when we decide on the date to do it because we need to take the site down for a while.

For new features, I might be able to do it if it's _actually_ quick and easy. It might look easy from the outside, but some things aren't. Some of the features I originally thought would be easy were not because of how the data is stored for example.

Making this page is low effort and I thought this can have a good return for the time invested. The page is already done and currently enabled for admins only (it looks better than the image I posted). For who gets to see this page, I'm not planning to do anything complicated at the moment. I'll probably just add a new privilege that's only granted manually.

**Comment by aeros167** [comment]
@kazk
Would there be a way of allowing others to help contribute voluntarily to portions of Codewars, even if it's just isolated components? I have a feeling many in the community would be more than happy to dedicate their time at no expense. Especially if you're the only developer working the site and unable to dedicate a lot of time to doing so.

**Comment by kazk** [comment]
@aeros167 

> Would there be a way of allowing others to voluntarily contribute to portions of Codewars, even if it's just isolated components?

No

> Is there a particular reason why it's not practical for Codewars to allow for others to contribute?

Short Answer: There's no isolated components. It's a [big ball of mud](https://en.wikipedia.org/wiki/Big_ball_of_mud).

Longer Answer:
My reply to a user saying:

> speaking of bugs, it'd be nice if they gave power users access to CW source code so we could submit pull requests or at least offer suggestions lol

Even if it was possible, I highly doubt this will help considering the state of the codebase.

It's very difficult to split the work because everything is tangled.
Accepting a pull request will require significant amount of time and energy to review because a small change can break something that seems unrelated.
Offering suggestions is very easy until you need to consider the background which no one really remembers anymore.
6 years of tech dept is not easy.

For some of the newer things, I've been trying to make them open source projects so that the community can help. Maybe I can gradually replace parts of Codewars like this, but not anytime soon.

---

Codewars is basically in maintenance mode (mostly bug fix and small enhancements only) as we need to focus on [Qualified](https://www.qualified.io/). The active development stopped around the end of 2014. I inherited the project in late 2018 and have been cleaning up/optimizing the code and modernizing dependencies to keep the current version alive. We've been discussing about a rewrite but it's been getting pushed back as more work with higher priority comes up.

It's getting off topic so let's stop.

**Comment by aeros167** [comment]
@kazk 
Yeah you're right, this is completely unrelated to the translation page issue, apologies for derailing. I definitely understand the dilemma to some degree after having to work with non-modularized legacy code at my internship. In the meantime, I'll keep an eye out for any open source projects related to Codewars, but without holding my breath. Thanks for the detailed explanation and I hope Qualified works out well for you guys, it would be great to have future interviews based on Codewars problems.

**Comment by kazk** [comment]
This is deployed and enabled for selected users (currently 20 users). I got the list of users based on the number of approved translations and filtered them by hand, picking the users that seemed trustworthy. I'm not planning to increase the number for now.

The page lists the pending translations (over a week) for kata you've already completed. The languages you haven't enabled are not shown.

There's a pagination at the bottom so you can jump to super old translations.

![image](https://user-images.githubusercontent.com/639336/58301044-d47de700-7d99-11e9-8d5c-f63452d089f4.png)
![image](https://user-images.githubusercontent.com/639336/58301378-16f3f380-7d9b-11e9-8837-0e54d8afc2b0.png)

**Comment by aeros167** [comment]
Thanks, this should help greatly with helping translations get more attention. The only potential issue with a fixed set of 20 users having access to this feature would be if a significant portion of those users stopped being as active (with translation approval). I suspect it may have to be modified periodically.
