### ISSUE TITLE
Issue template categories need improvement

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1831]
![image](https://user-images.githubusercontent.com/14909989/58719844-3f1acc80-8403-11e9-8d36-2d78f2a5ecd5.png)

- `Bug report for a kata` belongs to the kata's discourse. Unless it's about the language run-time, but that belongs to the runner repo
- `Bug report` should be `Bug report for the site` (front-end and back-end). And not the runner, because that belongs to the runner repo too
- `Language issue` doesn't belong here at all, it should go to the runner repo
- Instead these categories should be added:
  + User-related inquiries (e.g honor calculation problems)
  + Kata/Translation process (e.g can't approve translations, kata language selection is empty...)
  + Site objective (about various aspects of how the site is run and maintained, like code of practice, kata topic...)

**Comment by kazk** [comment]
> Bug report for a kata belongs to the kata's discourse. Unless it's about the language run-time, but that belongs to the runner repo

Have you read the templates?

`Bug report for a kata`: "Please file an issue on the discourse page of the kata. You can do so by creating a comment and marking it as an issue."

`Language issue`: "Please open an issue at [Codewars/codewars-runner-cli](https://github.com/Codewars/codewars-runner-cli/issues) repository."

I added them specifically because I thought it's more likely for users to read that than when it was part of a generic bug report template.

Templates are in https://github.com/Codewars/codewars.com/tree/master/.github/ISSUE_TEMPLATE

**Comment by Voileexperiments** [comment]
@kazk That's not a very good measure because, well, users don't read them! Just look at #1836 and #1837, and many more.

Also there are other templates that could be added. So I don't see why this issue is closed.

**Comment by kazk** [comment]
If users don't even read those, then why add more? Like I wrote above, it's under https://github.com/Codewars/codewars.com/tree/master/.github/ISSUE_TEMPLATE.

Please open a PR if you can improve them or if you think adding more is helpful. We'll take a look.
