### ISSUE TITLE
Search query matching is most definitely broken

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1853]
I've encountered this many times before and it's very frustrating, but kata search results seem to use some algorithms that makes no sense at all.

e.g if I want to search all kata with "frog" in its title, you thought you should put `frog` in the search query? Nope, it gives ~800 katas which none of them are about frogs:

![image](https://user-images.githubusercontent.com/14909989/59972382-7cb4e480-95c0-11e9-8519-393a59352faf.png)

To actually find katas about frogs you need to put... `frotg` in the query (yeah I discovered that by an accidental typo). Then you get 9 katas, all of them have frogs in the title:

![image](https://user-images.githubusercontent.com/14909989/59972372-53945400-95c0-11e9-8d78-143474328481.png)

---

Another thing that used to work but is now broken is, I used to be able to search katas of a specific author by searching their user name, e.g `myjinxin2015`. Apparently it's not working anymore.

**Comment by kazk** [comment]
I'm not sure how it works exactly since it's done by a package, but I agree it's not working as intended. I guess with current configuration, it _assumes you've made a typo_. Your `frotg` example and `frog` returning "**forg**iving" and "**prog**ramming" (from tags).

I'd like to eventually add [search operators](https://github.com/Codewars/codewars.com/issues/1018#issuecomment-500610861). But in the short term, I'll try changing the option to behave more predictable.

> Another thing that used to work but is now broken is, I used to be able to search katas of a specific author by searching their user name

This is my fault. When updating the package used for searching, it was changed to require specifying fields and I missed to include the `author` field.

It currently matches `name`, `description`, `tags`, `state`. `name` match is preferred over others when found.

**Comment by kazk** [comment]
> I guess with current configuration, _it assumes you've made a typo_.

The problem seems to be that it mixes the typo result indifferently. So searching for `frog` should be also returning those kata with `frog` in the name, but it's buried under results that contains typo variants. I found a configuration to avoid including typos unless the search result is less than 5 so that should fix it.

**Comment by kazk** [comment]
Fixed both weird matching and searching by author.
