### ISSUE TITLE
Easy cheat in python

### ISSUE THREAD

**Issue by mercenarychaos** [Codewars/codewars.com#1874]
It's possible to open the main.py in python and to read the solution directly.
I'm not sure if I should post the line of code here so I'm not gonna yet but it's very simple.

**Comment by DonaldKellett** [comment]
Thanks for taking the time to report it.  The Codewars team is well aware of common exploits such as the one you mentioned above. Since it is infeasible to try to find and patch all such possible loopholes, Codewarriors found to abuse them repeatedly, especially on `1-4 kyu` Kata (but not limited to them), will be permanently banned (i.e. rank fixed to `8 kyu`, honor set to `0` and no way to delete or modify offending account) once discovered.

cc @kazk to close this

**Comment by error256** [comment]
The source can be used as a hint and a base for solutions rather than for direct copypasting. There can be some tutorials, hints and solutions somewhere on the net, but this one is always here, so it's more like attaching free hints to every kata by default without any choice. So this does look like an issue, but I think it may not have easy solutions.

**Comment by Bubbler-4** [comment]
Just an idea: [compile to bytecode](https://docs.python.org/3/library/py_compile.html), remove original source and run the bytecode instead?

**Comment by kazk** [comment]
Our policy is to only do something if it can be done accidentally. Cheating on CW mostly just harms the cheater by wasting their time and the learning opportunity.
