### ISSUE TITLE
Editing comment in published Kata resulted in tests not passed

### ISSUE THREAD

**Issue by nomennescio** [codewars/codewars.com#1881]
After correcting a remark in a published Kata by editing the solution and updating a comment, publishing resulted in the tests not being passed.

https://www.codewars.com/kata/5a3af5b1ee1aaeabfe000084

**Comment by hobovsky** [comment]
Aaaaand the link you posted made me to forfeit the kata. Yay, thanks for that. I think I need to be more careful next time.

The problem is not CW issue, or at least not directly. It's the kata/translation issue. Out of 10 clicks on "Validate solution" button, I got 5 timeouts, so there's one of these happening:

 - Generated test cases are inconsistent in terms of difficulty, and sometimes you get easy ones, and sometimes RNG does not like you and generates more demanding tests. If it is so, then it's translation problem - separate test runs should be consistent.
 - Reference solution is inconsistent in terms of performance between runs.
 - Translation in general is screwed and cannot be helped because of https://github.com/Codewars/codewars-runner-cli/issues/714 which makes all C++ performance-based kata totally useless.
