### ISSUE TITLE
Really slow codewars

### ISSUE THREAD

**Issue by asdf334** [Codewars/codewars.com#1891]
The Codewars server runs so slow, even when I want to skip a kata, train, or just view my profile I have to wait 30ish seconds. Does this have to do with not having CW Red? Or is it just a server error?

**Comment by FArekkusu** [comment]
CW is working poorly for everybody, and this is an old issue. Although, the problem seems to be move severe these last few days - everything times out very often, and the loading times may go as high as a minute.

**Comment by Steffan153** [comment]
The slowest part (at least for me) is the translation editor. Takes about 5 seconds to type in 1 character (that's why I always write it in my IDE).

**Comment by FArekkusu** [comment]
@Steffan153, your problem is different from this one. I've never heard about the editor lagging for anybody (there **is** one kata with such problem but there's a reason for it to be unresponsive). You should probably raise a separate issue.

**Comment by kazk** [comment]
Yeah, CW is always slow, but like @FArekkusu wrote it's even slower the past few days. It's difficult to find the cause because nothing was changed.

I'm working on some optimizations and bug fixes right now and hoping that will help.

I have no idea about the editor issue. Maybe some extension is getting in the way?

**Comment by Steffan153** [comment]
> Maybe some extension is getting in the way?

Yep! It worked fine with no extensions. :smikey:

**Comment by samuelludwig** [comment]
Good to know it isn't always this bad, I just started two days ago and the 30+ second wait times from clicking a button is really starting to hit me- I wish it could be faster though, as far as experience it's been my favorite of all the "coding puzzles" sites (and its one of the few with good Elixir support)

**Comment by kazk** [comment]
The recent performance issue is most likely caused by the increased traffic. For some reason, Codewars had the highest number of new users per month last month (20% more than previous highest), especially towards the end of the month.

@samuelludwig All of the challenges now supports Elixir 1.9. The test output is not great, but I'm planning to improve and open source it sometime soon. Elixir is one of my favorite languages.

**Comment by ImranAhmed** [comment]
Great platform and love it, but the slowness is a real problem. Please could we have a look at this. I use this along with Repl.it as a teaching aid and it would be a shame to abandon. The editor is fine but loading My Solutions, All Solutions and Solutions of Users I am Following is unusable at times. Submissions can take very long too.

**Comment by kazk** [comment]
The performance issues for solutions page for kata with many solutions are known. It's one of the last few critical technical dept, and related to the problem with the database design I wrote [here]( https://github.com/codewars/codewars.com/issues/2263#issuecomment-719997658), and it requires a significant effort to fix. I'd like to fix it this year.
