### ISSUE TITLE
Is it possible to copy all JavaScript challenges to TypeScript?

### ISSUE THREAD

**Issue by usernamehw** [Codewars/codewars.com#1904]
`JavaScript` shows **5000+** available Kata while `TypeScript` - **400+**.

Is it not possible to just move them somehow, since TypeScript compiles to plain JavaScript?

**Comment by kazk** [comment]
No, it uses different test frameworks and TypeScript uses proper modules unlike JavaScript that concatenates solution file to test file.

It's _technically possible_ to transpile to JS and then use the tests written for JS, but we don't have any plans to do this. Codewars have lots of JS because it's the first language that was supported and it has many issues because of it. Maybe in the future, automatically generating JS version from TS version might become possible, but not vice versa.

**Comment by Voileexperiments** [comment]
> Is it not possible to just move them somehow, since TypeScript compiles to plain JavaScript?

No, because there are advanced JS katas that, for the most part, has nothing to do with the additional capabilities of TS. Making them TS kata wouldn't add anything to them.
