### ISSUE TITLE
Feature/Sort kata solutions by runtime execution

### ISSUE THREAD

**Issue by bestwebua** [Codewars/codewars.com#1906]
It would be great if in kata solutions would be an opportunity sort by runtime execution.

**Comment by Voileexperiments** [comment]
This has been brought up many times before and it doesn't work on CW at all, not to mention it's a bad idea, because:

1. CW does not have a tightly controlled runtime environment, it's run on docker containers on cloud. Whatever result you get cannot be called a benchmark if they're not run on the same machine in the same condition
2. Katas don't use a set of fixed test cases but rely on random tests to ensure correctness, so by nature every run will give a different runtime. If you want 0.1% uncertainly with 99% confidence statistically you have to run the same code for about 4 million times. Good luck with that
3. In the end, what does it *achieve* anyway? The commonly stated purpose is along the lines of "get rid of this short, 'clever', UUN but `O(n^2)` instead of `O(n)` solution that I don't like from the top solutions list", but it'd be extremely problematic if a criteria is invented just because *some* people don't like short code; not to mention that shooting at these solutions is not solving their problems at all since what they actually wanted is solutions that is UUN, which is not solution that is the fastest. CW's not an OJ site (it'd be a pretty terrible one if it was) either, and even along that line nobody likes OJ problems that encourages/mandates micro-optimizations because they're mostly pointless.

**Comment by bestwebua** [comment]
Hi, @Voileexperiments! Thank for your detail answer. This problem became more clear for me, and now I absolutely agree with your point of view.
