### ISSUE TITLE
Javascript test code can be accessed by using function.caller

### ISSUE THREAD

**Issue by PatrickHollweck** [Codewars/codewars.com#1952]
#### Describe the bug
One is able to access the source of the test-code by using this snippet:

```js
// This is the function that will be called by the test code
function validParentheses(source) {
  // Multiple possibilities to do the same thing
  // Gets the calling function and using .toString() you can get the source of that function.
  console.log(arguments.callee.caller);
  console.log(validParentheses.caller);
}
```

This will spit out the testing code

```js
function () {
    var 
          Test = global.Test,
          describe = global.describe,
          it = global.it,
          before = global.before,
          after = global.after;

    Test.assertEquals(validParentheses( "" ), false);
    Test.assertEquals(validParentheses( "())" ), false);;
}
```

When you have access to the testing code you can use this information to cheat.
**You could prevent this by running all test-code in strict mode**

#### To Reproduce

1. Goto any challenge
2. Switch to Javascript
3. In the "main" function insert `console.log(arguments.callee.caller.toString())`
4. See the code that is used to test the solution in the console.

#### Expected Behavior

Depending on if this behavior should be allowed or not this should or should not log the code.

#### Screenshots

![image](https://user-images.githubusercontent.com/20997737/66268108-497a2680-e83a-11e9-869f-3efc9480ea60.png)

#### Why is this a Problem?

You can get access to the hidden tests.

#### Contexts

Please complete the following information:

- Codewars username: -
- OS: any
- Browser: any
- Browser Version: any

**Comment by kazk** [comment]
This is well known and we don't consider this a bug. There's many other ways to cheat and our policy is to only try to "fix" if it can _accidentally_ pass tests.

> You could prevent this by running all test-code in strict mode

If I remember correctly, we used to add `"use strict";` to the IIFE wrapping the test code, but it was reverted because many kata was broken.
Letting kata authors opt-in by adding `"use strict";` to tests doesn't work for Node 6/8 because we prepend some variable declarations before wrapping in IIFE like you saw and `"use strict";` must come before any other statement within the function. I'm not changing how older versions of Node works on Codewars unless it's absolutely necessary because of the content compatibility.
From Node 10, kata authors can add `"use strict";` if they want to. Maybe adding to the template to encourage doing so is a good idea.

Also, tests for newer kata (and for newer version of Node) are written like:
```javascript
describe("test group", () => {
  it("test case", () => {
    assert.strictEqual(solution(), expected);
  });
});
```
so it doesn't expose everything like your example.
