### ISSUE TITLE
"Discourse" section on the dashboard needs to be a lot shorter

### ISSUE THREAD

**Issue by shakhbulatgaz** [codewars/codewars.com#1968]
#### Is your feature request related to a problem? Please describe.
The "Discourse" section, the section most people don't give a damn about, is about 5 times bigger than "Your Next Challenge..." section, which is the most important section on the page.

Why do users have to scroll to be able to read the challenge text in that tiny-ass window, while the random comments on random katas (not even the katas they engaged with) take up more than half of the page? It doesn't make sense .

#### Describe the solution you'd like
Shorten the "Discourse" section and make "Your Next Challenge" section a little bit taller so that users can read most challenges without having to scroll.

#### Describe alternatives you've considered
I don't see any other alternative, it is really that simple.

**Comment by FArekkusu** [comment]
You can click on the title to go to the kata page and read the full description there, you know?

The "Your next challenge..." section is uncomfortable to use, misleading for the new users as they may think that the CW content is limited to what they see in this tiny block, leads to bugs (#1664), and displays already completed katas if there're too few not completed ones. Personally, I don't see any benefit in this section being present, but who knows, maybe somebody is *really* using it as some sort of guide.

What would be a good idea IMO, is to rename it to something like "Suggested challenge" so that its intent is clearer.

**Comment by Blind4Basics** [comment]
@shakhbulatgaz : I disagree about the relative sizes of the "next challenges part" and "discourses" part: I totally don't care about the chaloenges and use the dashboard only to see the last posts in the discourses part. If someone want challenges, the kata search page seems more appropriate to me than the dashboard... ;)
