### ISSUE TITLE
Python. Overloading __eq__() to pass almost any kata

### ISSUE THREAD

**Issue by ringolol** [Codewars/codewars.com#1970]
#### Describe the bug

The same Python code can be used to pass almost any kata without actually solving it.

I think that overloading of equality function ( __eq__() ) leads to a wrong behavior of the test functions, like test.assert_equals(...)
#### To Reproduce

Write the following code into solution box:

```
class MyClass:
    def __call__(self,*x):
        return self
    def __eq__(self,x):
        return True
        
choose_best_sum = MyClass()
```

Where 'choose_best_sum' is the function the user of the site should define

#### Expected Behavior

I believe this code shouldn't be a valid solution to katas

#### Screenshots

![Screenshot_2](https://user-images.githubusercontent.com/57327672/68508940-cf95ec80-0280-11ea-9a30-975598d677ea.png)

#### Contexts

- Codewars username (if account related): Ringolol
- OS: Win10 Pro
- Browser: Firefox
- Browser last

**Comment by hobovsky** [comment]
This issue is known to admins and while it cannot be easily protected against (I do not know the exact reason why, I just remember it being mentioned somewhere some time ago), submitted solutions are scanned for such tricks (there's more of them, not only for Python), and when detected, solution is flagged and brought to the attention of admins. Eventual ban is left to the discretion of site administrator.

**Comment by ringolol** [comment]
Hobovsky, thanks for the information. With hindsight I shouldn't have published this solution;)

**Comment by kazk** [comment]
Cheating by exploiting the test framework is possible and we don't try to prevent them unless it can be done _accidentally_. We simply ban users that abuses them, so don't do this anymore if you don't want to get banned.
Your solutions have been marked as cheat and you've lost some points.
