### ISSUE TITLE
Inconsistency in site policy regarding treatment of submitted solutions to Kata

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars.com#1990]
As noticed by @ParanoidUser in https://github.com/Codewars/codewars.com/issues/1378#issuecomment-566958760 , there is a serious inconsistency in site policy regarding the treatment of submitted solutions to Kata.

On one hand, the [Codewars Terms of Service](https://www.codewars.com/about/terms-of-service) states:

> To promote collaboration and create a living resource, all kata solutions are actively opensourced under the FreeBSD 2-Clause License.

... which implies that Codewarriors are free to redistribute and use any submitted solution to any Kata, "with or without modification", as long as the copyright notice is included ([source](https://opensource.org/licenses/BSD-2-Clause)).

On the other hand, the [Codewars Community Code of Conduct](https://github.com/Codewars/codewars.com/wiki/Community-Code-of-Conduct) states:

> **Please do not post your solutions on Github.** We realize you would like to use these challenges as your resume, but you should have side-projects for that. If a Code Warrior is unable to find a solution online, then they are further encouraged to complete the task themselves - which will enable them to get more value out of their time spent.

So which one is it? Considering that the latter was updated on a more recent date (Jan 2019 as opposed to Oct 2018), perhaps we should stick to the latter and amend the ToS to give Codewars more ownership over submitted solutions to Kata? The only other option is to remove the quoted part about not posting solutions to GitHub in the Community Code of Conduct which will inevitably open a can of worms (think of a cheater saying "Yes, I copied solutions to hundreds of Kata from GitHub and submitted them to gain honor/rank but added a comment in my code including the license terms so you shouldn't ban me for doing so").

**Comment by kazk** [comment]
> there is a serious inconsistency in site policy regarding the treatment of submitted solutions to Kata.

No there isn't.

The ToS makes all user solutions and comments licensed under BSD-2-Clause without explicitly mentioning it in each (similar to `LICENSE` file in repository that applies to all files in it). This is required in order to allow many activities on Codewars.

Users have the right to redistribute/use the code according to the license (using it outside of Codewars requires including the license explicitly). Unless I'm mistaken, users also have the right to re-license their own work outside of Codewars if they're the only copyright holder.

So making your own solutions accessible to anyone is **highly discouraged and we ask users not to do so, but it's legal**.
However, submitting a solution found online _written by others as your own_ is a copyright infringement. And unless I'm misunderstanding or the original authors explicitly allows it, you cannot claim the copyright of the solutions you found by including the license (remember the implicit licensing). Note that derivative work within Codewars is explicitly allowed by the ToS.

If we change this and let Codewars own the solutions, we can request takedowns to GitHub for the repositories containing solutions submitted after the ToS change, but I wouldn't want to do that.

Disclaimer: I'm not a lawyer.

> "Yes, I copied solutions to hundreds of Kata from GitHub and submitted them to gain honor/rank but added a comment in my code including the license terms so you shouldn't ban me for doing so"

Remember that we reserve the right to ban anyone for any reason at anytime without notice as stated in ToS. "shouldn't ban me" is meaningless because we decide.

**Comment by DonaldKellett** [comment]
@kazk Many thanks for your clarification; I would like to quote https://github.com/Codewars/codewars.com/issues/1378#issuecomment-567265654 in the future when dealing with Codewars solution repositories in the future if you don't mind :smile:

**Comment by kazk** [comment]
Sure, I wouldn't recommend wasting your time hunting those repositories, but you can quote the comment when it makes sense.
