### ISSUE TITLE
Sign out button doesn't work if it's opened as a new tab

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#1993]
^

**Comment by kazk** [comment]
This is because it's implemented using Rail's `link_to method: :delete` which adds `data-method="delete"` attribute and uses JS to make `DELETE` request instead of `GET` when clicked. This obviously won't work if you explicitly "open" (`GET`) the link location in a new tab.

It's a common practice for apps using Rail's views as far as I know. Newer apps might just use `click` event handler on `<a>` without `href` or `<button>`, but middle clicking it (to open in a new tab) won't work on those either.

I'll reopen if you can tell me why you need this to work and if it makes sense to me.

**Comment by Voileexperiments** [comment]
@kazk ...then it shouldn't be a link? When I see an explicit `<a>` I expect it to work regardless of middle-click or left-click or whatever I use to interact with it. The common practice for an element to trigger a non-GET request is, well, use a `<button>`.

Currently it's just misleading and opens up unnecessary interactions that don't work.

**Comment by kazk** [comment]
I'm not arguing that this is semantic. This is/was a **common practice in Rails views** (see examples in the official [`link_to`](https://api.rubyonrails.org/v5.2.3/classes/ActionView/Helpers/UrlHelper.html#method-i-link_to) docs). As far as I know, it's a convention that uses `href` and `data-method` so that you don't need to write your own JS code.

I agree with you and I'd prefer to have a separate helper method that generates a button (e.g., `<button data-href="" data-method="">Action</button>`) instead that works similarly. But remember that normal users wouldn't know/care if it's `<a href="" data-method="delete">` or `<button onclick="">`.

I only asked you to elaborate on because I don't know why you'd want to or try to open "Sign Out" in a new tab. I'll reopen if there's a practical reason.

We also have a _plan_ to start redoing the UI sometime in 2020 so this will be "fixed" then.
