### ISSUE TITLE
Head to head compare provides greatly varying execution times.

### ISSUE THREAD

**Issue by SavioVolceroKiera** [Codewars/codewars.com#1999]
#### Describe the bug
Head to head compare is completely unreliable when it comes to providing execution times. It happens that every single one of my solutions is significantly slower than other user's. I'm not sure what is the cause (server load or inclusion of time needed to load kata (mostly in compiled languages)), however with it being as is, the feature seems pointless.

#### Expected Behavior

Somewhat reliable timer results.

#### Screenshots

![BugScreenshot](https://user-images.githubusercontent.com/55797790/71557252-fd5b0e80-2a43-11ea-9224-abb12b39ba54.JPG)

#### Contexts

Please complete the following information:

- Codewars username (if account related): savoki

**Comment by kazk** [comment]
Head to Head Compare does not rerun the solutions. It shows the best time recorded during successful attempts.
So for example, it's possible that the other user submitted their solution 5 years before you and the solution was tested against significantly less test cases, the time was measured differently or incorrectly recorded (or not even recorded) back then, or your solution took more time for some other reasons than your code when attempting etc.

The time shouldn't be that different (`9 ms` shouldn't be possible now) if it was recorded around the same time and the implementation is equivalent.

Also, comparing execution times is not that meaningful to begin with because most kata has random tests and each submissions are tested against different inputs. It's also only recorded on successful attempts so the number of samples is not enough.
We don't show the time on solutions page for this reason and don't have plans to benchmark solutions properly at the moment.
