### ISSUE TITLE
kata's output's error screen need instructions for newbies

### ISSUE THREAD

**Issue by ovdey** [Codewars/codewars.com#2002]
hi!) just each error code description :

error: cannot find symbol
   squareSum += i;
   ^
l (am newbie and) have this symbol and dont understand what programm want from me, like a lot of other people. thank you for watching)

**Comment by FArekkusu** [comment]
Not an issue. If you don't know the language you're using, can't read error messages or don't understand them, that's your problem.

**Comment by ovdey** [comment]
there is a kyu system, if things was like you said, there was only 1 kyu hard kata and - "
If you don't know the language you're using, can't read error messages or don't understand them, that's your problem."

**Comment by FArekkusu** [comment]
Kyu is a representation of the knowledge required to solve a kata, and not your general programming skills. If you're not competent enough to write code which *at least works*, nothing is going to help you. Moreover, `cannot find symbol` is a built-in compilation error, it is not possible to make it noob-friendly (maybe it is possible, but that would be a huge waste of time). As they say, "git gud".

**Comment by ovdey** [comment]
thank you for answer and all time you waste, but I hope there will be more friendly answers pointed to enfast education

**Comment by kazk** [comment]
> l (am newbie and) have this symbol and dont understand what programm want from me

The program (compiler) is telling you what it wants in that message. The symbol (`squareSum`) might _appear_ to be there (when humans are reading it), but the compiler doesn't know/understand it so it's "missing" from its perspective. You need to write your code so that the machine can understand.
I don't think it's possible for it to tell you what needs to be fixed. Even if it was possible, this is out of scope here since it should be included in the compiler.

Also, you'll see this outside of Codewars so you should learn the error messages. Start by using Google/DDG and search "error: cannot find symbol".

**Comment by ovdey** [comment]
ok, like said FArekkusu - thats only MY problem)))
