### ISSUE TITLE
Submit button doesn't appear

### ISSUE THREAD

**Issue by HowToDisappear** [Codewars/codewars.com#2010]
Hello. When I enter my solution to kata and click 'attempt' button it passes all tests successfully. But the 'submit' button doesn't show up. It used to work just fine but yesterday and today it doesn't.
I use Mac OS, Google Chrome.
Do you know how to fix it?
<img width="1209" alt="Screenshot 2020-01-18 at 12 33 29" src="https://user-images.githubusercontent.com/60031509/72661728-e67a5d00-39ee-11ea-8bab-a88cd2789b77.png">

**Comment by hobovsky** [comment]
#1839

**Comment by FArekkusu** [comment]
> #1839 

This is a separate issue. In that case the button is not visible, while here `Attempt` button is not replaced with `Submit final`.

**Comment by kazk** [comment]
@HowToDisappear can you try refreshing the page and try again?

Some users are having this issue because of a recent update and requires reloading a page to fix.

**Comment by rpalri** [comment]
I am facing the same issue. Does anyone know the solution?

**Comment by lion9** [comment]
Multiple refreshing and reloading with clearing cache did not help

**Comment by DominicYonce22** [comment]
this is my issue now, has this been adressed

**Comment by hobovsky** [comment]
> this is my issue now, has this been adressed

@DominicYonce22 could you please do following:
- create a new ticket 
- describe again how do you work through a kata and what does not work for you: are buttons missing? Buttons do not do anything? Some other problem?
- include screenshots if your problem is visible on screen.
- please check browser console and browser developer tools for errors and tell if you see any.
- retry in incognito mode.

You can also visit Codewars Discord server, go to the channel `#contact-mods`, create your own thread there, and provide all information requested above.

There is also no reason to post the same question in multiple threads.

**Comment by olegkamuz** [comment]
Same here with https://www.codewars.com/kata/62c702489012c30017ded374/python
