### ISSUE TITLE
Comment time is incorrectly shown as "A couple years ago"

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#2012]
I observed this in [this kata solution discussion](https://www.codewars.com/kata/reviews/58638ebf35af21f5f2001e67/groups/5863d5ab08feb0ae440001ac):

![image](https://user-images.githubusercontent.com/14909989/72697734-ef4c6980-3b7b-11ea-9f3e-e00417d0d252.png)

The top comment is *just* 3 years old (from 18 January 2017), and the two comments below are from June 2017. For some reasons the two comments at the bottom says "a couple years ago" instead of "2 years ago", which is expected and gives more information.

**Comment by FArekkusu** [comment]
Not only years have changed, there're also "a couple of months/days/hours/minutes/seconds ago" messages.

**Comment by hobovsky** [comment]
I hate this "human-readable time span" thing in general, its ambiguity is enough to trigger me hard ;) I prefer just a regular timestamp much more.

**Comment by kazk** [comment]
I had accidentally updated `vagueTime.js` and it seems like they changed how `2` is handled.

I've replaced it with something minimal and also added exact timestamp in UTC to `title` attribute so that it shows that when you hover.

Note that the relative time is now rounded, so `2.5 years ago` becomes `3 years ago`. Read it as almost 3 years ago.
