### ISSUE TITLE
If "TEST" or "ATTEMPT" button is pressed, its tooltip does not disappear

### ISSUE THREAD

**Issue by FArekkusu** [Codewars/codewars.com#2047]
The tooltip from `TEST` button is still present while the cursor is hovering over `ATTEMPT` button:

![image](https://user-images.githubusercontent.com/31668662/75487955-163a5e80-59b8-11ea-87a7-f9fa854cd10a.png)

**Comment by kazk** [comment]
Fixed

**Comment by FArekkusu** [comment]
I've just noticed that the same thing happens with the `DISCUSS` and `VIEW SOLUTIONS` buttons too.

The remaining `RESET`, `SKIP`, `UNLOCK SOLUTIONS` work fine.

**Comment by kazk** [comment]
Doesn't those go to discussion page and solution pages?

**Comment by FArekkusu** [comment]
Yes, but you can middle-click those and the tooltip will remain, which is probably not desired.

**Comment by kazk** [comment]
This is because the element has `:focus` state. Most of the new tooltip libraries seems to work this way for accessibility.
The problem is that the tooltip should be shown when focused using a keyboard, but not after middle clicking.

> The remaining `RESET`, `SKIP`, `UNLOCK SOLUTIONS` work fine.

These can't be middle clicked because there's no `href`. I can change `DISCUSS`/`VIEW SOLUTIONS` to be the same, but that will prevent opening the discussion page in new tab.

I've been gradually updating the frontend codebase to be more maintainable, so I'll keep this in mind as a low priority enhancement.
