### ISSUE TITLE
Not all keywords are highlighted in C#

### ISSUE THREAD

**Issue by Seprum** [Codewars/codewars.com#206]
I have noticed that such keywords as `foreach`, `typeof`, `is`, `ushort`, `uint`, `ulong` are not highlighted in C# code editor window.

**Comment by jhoffner** [comment]
Fixing this will likely involve having to wait until we can update CodeMirror to the latest version, which isnt a simple upgrade unfortunately.

**Comment by kazk** [comment]
Closing this because those keywords are recognized now.
![image](https://user-images.githubusercontent.com/639336/29698210-b6c4a08c-8908-11e7-8f14-c33d03199f01.png)

![image](https://user-images.githubusercontent.com/639336/29698269-2401ddcc-8909-11e7-9ba1-cc6bc29b0eec.png)
![image](https://user-images.githubusercontent.com/639336/29698283-3db00028-8909-11e7-9d80-48e2e0269035.png)

**Comment by SlyBeetle** [comment]
https://www.codewars.com/kata/reviews/5739964ef14baceffa0000c0/groups/587d19f3436f3c0f68001cba

**Comment by Voileexperiments** [comment]
This happens sometimes to some solutions. The highlighter just completes dies and nothing is highlighted.

**Comment by SlyBeetle** [comment]
https://github.com/Codewars/codewars.com/issues/779
