### ISSUE TITLE
New solution doesn't pass tests, and forking gives a massive error message

### ISSUE THREAD

**Issue by Steffan153** [codewars/codewars.com#2098]
https://www.codewars.com/kata/reviews/5e92b8ebd867810001cb545e/groups/5e949103955e44000113a95f

This solution does not pass the tests, in Lean, `sorry` is just a placeholder. It does nothing.

And when I fork it, I got the biggest error message I've seen on CW. x)

![image](https://user-images.githubusercontent.com/40404519/79284505-157e5e80-7e78-11ea-9c34-100ab4a57681.png)

**Comment by kazk** [comment]
I don't know why that solution was accepted, but the cause of this error when forking was because it resulted in invalid Kumite (solution forks have kata's initial code as root and all Kumite must be different from its parent to be valid, but this solution had the initial code as is).

I removed the solution and the solution group.
