### ISSUE TITLE
Payload for saving Kumite changes the line ending to CRLF

### ISSUE THREAD

**Issue by error256** [codewars/codewars.com#2105]
It shows as if everything is removed and everything is added, even if it's the same text. It's the same for code blocks and for the description. For instance: https://www.codewars.com/kumite/5dcab5c58c32c20028d44d46?sel=5e9c83de4a64400028e47ec4
![Broken diff](https://user-images.githubusercontent.com/5375100/79694684-71bef500-8261-11ea-87bf-b3e4222b8756.png)

**Comment by kazk** [comment]
This was correct. The fork has `\r\n` line endings while the original had `\n` :man_facepalming: 

![image](https://user-images.githubusercontent.com/639336/80020499-027a1880-848e-11ea-86fa-13fbfecb159f.png)

**Comment by error256** [comment]
Something must have changed... I never saw this until recently. Now there are quite a few new translations like this by different people:
https://www.codewars.com/kumite/5e94ee4bf78fa90014bd10e8?sel=5e94ee4bf78fa90014bd10e8
https://www.codewars.com/kumite/5e954acbfa64eb000fd1ecf7?sel=5e954acbfa64eb000fd1ecf7
https://www.codewars.com/kumite/5e96a2eff3bd4a0020ba63d8?sel=5e96a2eff3bd4a0020ba63d8
https://www.codewars.com/kumite/5e96f0ff481bf600241dca33?sel=5e96f0ff481bf600241dca33

**Comment by FArekkusu** [comment]
The same thing happens everywhere, and it's not limited to kata descriptions, In [this fork](https://www.codewars.com/kumite/5e9dfa382ace36000f9aeef6?sel=5e9dfa382ace36000f9aeef6) only 1 **character** was changed in the fixture, but the `diff` tab shows that almost everything was replaced... with the same code. Surprisingly, in the next fork 1 line was changed in the fixture again, and the `diff` tab shows it as the only difference.

**Comment by hobovsky** [comment]
I guess the way how newlines are handled changed at some point and when you diff old fork vs new fork you see everything changed because of new line differences, and when you diff new fork vs new fork, newlines do not differ anymore.

Maybe we could get "ignore whitespace" options in diff viewer like in all proper software? :) OR maybe set something as default? Not that I **know** things, but I would believe that diff tool used by CW supports such options?

![image](https://user-images.githubusercontent.com/23709795/80109333-a7bfea00-857d-11ea-9cfd-b456a8f73031.png)

**Comment by error256** [comment]
But how and why `\r\n` are there in the first place? `\r\n` is normally Windows-only and I get these diffs in my new forks of my own new solutions made in Linux, so line endings get replaced inconsistently somewhere on Codewars side.
For instance: https://www.codewars.com/kumite/5ea93a37030dc8002a521a8c?sel=5ea93a37030dc8002a521a8c

**Comment by kazk** [comment]
@error256 You're right. Looks like `POST` request to save the fork have `\r\n` endings (I'm using Linux as well). I changed the payload to JSON instead of FormData few weeks ago and maybe something related to that is causing it. It's weird because the request to the runner doesn't seem to have this problem and it should be both getting the code from CodeMirror :/

**Comment by kazk** [comment]
Turns out jQuery's `$(form).serializeArray()` changes the line ending to `CRLF` because it's required for `application/x-www-form-urlencoded` :exploding_head:

So this is caused by using the string prepared for `x-www-form-urlencoded` in JSON. I'm using slightly modified version of https://github.com/marioizquierdo/jquery.serializeJSON which uses jQuery's `serializeArray()` internally.

I've been migrating away from forms, but this is still used in Kata Editor, Kumite Editor, and Account Settings pages.

**Comment by kazk** [comment]
This shouldn't be happening anymore for new forks. But the reverse will happen if you fork kumite with CRLF which was only possible while this bug was in effect. The line ending is going to be always LF (CodeMirror normalizes it).

The affected data is kata description (any save/publish changed description to have CRLF) and kumite fields (description and code) changed between 2020-04-13 21:24 UTC and 2020-04-30 6:52 UTC.
I'm looking into fixing the affected data, but this might be difficult because the revisions is a mess to begin with.

I'll also look into adding an option to ignore whitespace when viewing diffs.
