### ISSUE TITLE
Move Lean Support out of Beta

### ISSUE THREAD

**Issue by DonaldKellett** [codewars/codewars.com#2134]
So now we have 76 Lean kata in total (compared to 79 in Coq as reference), 50 of which have been approved and no major issues with the current setup thus far. What do you say about moving Lean out of Beta and officially declaring it as a stable supported language on Codewars?

***

:+1: reaction *may* help

**Comment by monadius** [comment]
One thing which need to be done before moving Lean out of Beta is to update the mathlib version and see how easy it will be to fix existing kata. I don't know about Lean itself, but mathlib should be periodically updated.

**Comment by DonaldKellett** [comment]
AFAIK mathlib commits are tightly coupled with the Lean version so we will probably have to update our Lean version as well. I'll ask the community over at Zulip if having a slightly outdated Lean + mathlib (v3.7.2 compared to the current v3.11.x) is an issue, and if so, we can request for the Lean version (and the corresponding mathlib) to be updated.

**Comment by monadius** [comment]
Lean 3.11 with the updated mathlib is considerably slower than Lean 3.7.2. Because of this, I am not able to update the Lean version of my [Chebyshev kata](https://www.codewars.com/kata/5d2bd8e414a6ef001a0421d2). I created an (almost) empty [kumite](https://www.codewars.com/kumite/5ebe371ed319db001a8d4775?sel=5ebe371ed319db001a8d4775) which demonstrates that just importing `analysis.special_functions.trigonometric` is enough to get a timeout in Lean 3.11.

**Comment by kazk** [comment]
:(
I made the container image exactly the same way so I believe Lean 3.11.0 and/or this mathlib version is much slower for some things. Currently 65/81 kata have 3.11.0 enabled (was compatible and also didn't timeout).

If I remember correctly, Lean 3.7 was slower than 3.5 and 3.6 as well (which was also slightly slower than 3.4) when I was experimenting (https://github.com/codewars/codewars-runner-cli/issues/773). I'm not increasing the time limit every time it gets slower.

**Comment by DonaldKellett** [comment]
For Lean-only kata that cannot be updated due to timeouts, perhaps we should just retire them? Not sure how to handle those with Coq versions as well though (IIRC it cannot just be removed due to database issues?) ...

**Comment by monadius** [comment]
Let's just wait. If understand this Zulip [discussion](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/speed-up.20project.20returns/near/197723788) correctly, long import times is a known issue and it may be fixed in future Lean releases. Although it is also true that mathlib itself is growing and timeouts in future are still possible.

**Comment by DonaldKellett** [comment]
@kazk All except Real Chebyshev have been updated to 3.11.0.

**Comment by kazk** [comment]
We can keep 3.7.2 for now. Hopefully, the next update fixes the problem.
I'll close when I deploy the change to move Lean out of beta.

**Comment by kazk** [comment]
Deployed

**Comment by sainiboey** [comment]
what is kata

**Comment by DonaldKellett** [comment]
Thanks for moving Lean out of Beta, I've updated the Wiki to reflect the change. By the way, it seems that the main page still says that Lean is in Beta?

![螢幕截圖 2020-05-20 12 37 21](https://user-images.githubusercontent.com/7777884/82405532-c3dc7b80-9a96-11ea-9003-0900a36902ee.png)

**Comment by kazk** [comment]
The cache wasn't invalidated. It should be fixed now.
