### ISSUE TITLE
Login with email and password does not work. Email with reset password instruction is not sent.

### ISSUE THREAD

**Issue by alex75it** [codewars/codewars.com#2137]
#### Describe the bug
Cannot login using email and password.

#### To Reproduce

1. Create an account linked to your GitHub account.
2. Go to home page. 
3. Logout if you are logged in.
4. Login using email and password.

5. Obtain the error "Invalid email or password"

6. Login using GitHub account.
7. Change the password with a new temporary one very simple
8. See the message saying the account update was successfull
9. Log out
10. Try again to login with email and password

11. Obtain the error "Invalid email or password"

12. Click "Forgot email" link/button
13. Enter the email
14. See message: "You will receive an email with instructions about how to reset your password in a few minutes."
15. Check email for instructons..............

#### Expected Behavior

I expect to log in but I receive the error "Invalid email or password"
I expect to receive the email with instructions to reset the password.

#### Screenshots

Not needed.

#### Contexts

Please complete the following information:

- Codewars username: alex75
- OS: Windows
- Browser: Chrome
- Browser Version: Version 81.0.4044.138 (Official Build) (64-bit)

My email has this format:  firstname.lastname.123@gmail.com

**Comment by kazk** [comment]
For password reset email, your email was in the suppression list because according to the record on our email service, you "unsubscribed" on 2016-10-06. I just removed it so the password reset email should work now.

Can you try resetting and logging in with password?

**Comment by alex75it** [comment]
I received the email, I changed the password and I can log in usinf email and password.
Thanks.

Your statement sound strange to me for 2 reasons:
1. More than 3 years ago I unsubscribed from news/offers emails and that prevents me to receive the email for reset the password?
2. When I click on "Forgot Password?" and I insert my email it shows me the message "You will receive an email with instructions about how to reset your password in a few minutes."

That seems like 2 separate issues to me.
I'm tempeted to create 2 new issues for these because:
1. I possibly will unsubscribe again and I don't want to end in the same situation
2. I ended to give up and I used other "kata/exercise" platform in the last 2 years instead to open this issue, maybe other users are doing the same.

Are you taking some action with the interested product teams?
Thanks again.

**Comment by kazk** [comment]
> More than 3 years ago I unsubscribed from news/offers emails and that prevents me to receive the email for reset the password?

I wasn't involved with the project at the time, but I'm pretty sure that we've been using two separate services. One for newsletters (weekly challenges) and the other one for transaction emails (password resets and notifications). So it's either that wasn't the case back then and unsubscribing the newsletter cause this or you disabled the notifications by requesting the email provider to stop.

> When I click on "Forgot Password?" and I insert my email it shows me the message "You will receive an email with instructions about how to reset your password in a few minutes."

That's because your email address was in the suppression list of the email service provider and we didn't know. There should be some way to get notified when a user does this, but it's currently not done.

With that information, we can show some error and ask the user to email us with the email address to re-enable email delivery. I'll look into it.

> I possibly will unsubscribe again and I don't want to end in the same situation

For now, please use the Account Settings to stop the notification if that starts to bother you instead.
