### ISSUE TITLE
hints for kata

### ISSUE THREAD

**Issue by quixotic-axolotl** [codewars/codewars.com#2143]
i would love to see a 'reveal hint' feature which would help nudge people who have difficulties with their kata in the right direction. this could be very helpful to people who are completely lost or are using an entirely wrong approach, even after spending days on the kata. the unlock solution works for sure, but it simply reveals the answer and this might reduce the learning value of the kata.

there could be 2-3 hints per kata and revealing each hint would forfeit an amount of honor, such that the those who use the hints won't earn the full amount of honor. the hints could simply be links to resources (as some users have mentioned), methods or modules to use etc. the hints shouldn't restrict the approach, but they can't be too broad to not be helpful either :-)

**Comment by DonaldKellett** [comment]
@quixotic-axolotl You can always ask for hints (without penalty) on our Gitter [kata-solving-help](https://gitter.im/Codewars/codewars.com/kata-solving-help) channel.

**Comment by hobovsky** [comment]
If you don't want to go outside of the site, you can always ask for help in the kata discourse too (remember about "question" tag), but I think gitter chat is more convenient.

**Comment by FArekkusu** [comment]
Often you can learn a lot by... simply reading the comments, and you can always ask a question yourself if you don't understand something, as @hobovsky said. After you forfeit the kata, you can always leave a comment under somebody's solution asking what they're doing as well.

Asking for a hint-system is pointless because:
* nobody will update a few thousand katas to have those hints
* you can't force authors to add hints
* and even if you do, they can always enter some useless info just to make it publishable
* some katas are designed in a way that you must find out what's the task yourself, and providing help would ruin the idea

**Comment by alexbprofit** [comment]
> i would love to see a 'reveal hint' feature which would help nudge people who have difficulties with their kata in the right direction. this could be very helpful to people who are completely lost or are using an entirely wrong approach, even after spending days on the kata. the unlock solution works for sure, but it simply reveals the answer and this might reduce the learning value of the kata.
> 
> there could be 2-3 hints per kata and revealing each hint would forfeit an amount of honor, such that the those who use the hints won't earn the full amount of honor. the hints could simply be links to resources (as some users have mentioned), methods or modules to use etc. the hints shouldn't restrict the approach, but they can't be too broad to not be helpful either :-)

i think that this user want to reproduce leetcode's approach about problems into katas
