### ISSUE TITLE
Changing the buttons on the left menu bar / user's profile menu / ideas around that.

### ISSUE THREAD

**Issue by Blind4Basics** [codewars/codewars.com#2190]
## Current state:

![image](https://user-images.githubusercontent.com/32236948/86514954-f4ddf900-be15-11ea-85c8-e077745f1711.png)

* [BUG] as you can see in the picture above, there is a small bug when the mouse is over the sidebar: beginnings of the labels are showing up before the menu reveals itself.
This might be browser dependent (personally using FF 78 on Win7).

* that menu bar is not really visible for some users (I personally like it like that, but...)

* Generally, people will considere the buttons this way: "the upper, the most important". Hence kumites and (what's left of) the forum are given much more importance than the docs, while we'd want the users to go there first.

* [SIDE TOPIC] kumites. Those could need a topic on their own.... Not the place for it. Since I still don't get what they really add to CW, I'd just go for a removal. Offtopic, yes. Here, I'd just put them looooooower in the menu bar.

* `Kata` and `Kumite` are the labels while plurals would look more appropriate to the contents.

* The "forum" button should just be removed, imo:
  - most of the messages posted there are useless. 
  - Users are often told to go repost their problem in the github repo (here) or they ask for stuff that is (or should be/will finally end up) in the documentation.

Yes, I'm actually saying to just remove the forum from CW. Only problem is: where do the users go for general purposes that do not have a place in the github repo...? (that's another topic)

![image](https://user-images.githubusercontent.com/32236948/86515134-476be500-be17-11ea-892c-62ee800acb0b.png)

* why "account settings" and "training setup" are separated? I get the idea when I'm in those pages, but that still seems awkward to me when I read the menu. I'd actually merge the two pages. Except that causes the problem about the link in the upper box of the dashboard, to the "training setup" page. Not sure. I still feel like it's a better idea to have one single link in the user's profile menu...

* [SIDE TOPIC] new kata/new kumite:
Note that there is a difference in behavior about the way to create katas or kumites:
  - Kumites can be started from the link of this menu, or from the page of the kumites itself (reached by the left menu bar)
  - while a new kata cannot be created from the kata search page (which might actually be a good idea, to see less "hot garbage" showing up?).

Not really important, I'm just asking if that shouldn't be made more "homogenous".

---

## Suggestions for the left menu bar:

* Correct the label `Kata` to either `Search Kata` or `Kata Search` or if too long, just `Katas`.

* Same for `Kumite -> Kumites` (if kept...)

* add a link to the profile of the user in addition to the link currently in the top right corner (`https://www.codewars.com/users/USER`). Its icon could be the "figurative head" currently used in the user's profile menu (see "view profile" in the picture above).

* add a direct link to the github repo (?? -> rather a question than a suggestion, actually)

* change the order of the items to:  `dashboard / katas / profile / docs / (github repo?) / forum / kumites` (or possibly removing the last two?). Main goal: draw more attention to the docs on wiki

## Suggestions for the user's profile menu:

* add the kata search page above "new kata"

* add the images used in the left menu bar for katas and kumites to the related items in the user's profile menu.

* merge the two "settings" pages, as suggested above

**Comment by error256** [comment]
Kata vs katas is like indices vs indexes, cacti vs cactuses, etc. Both forms seem to be used, but I'm not sure about stylistic subtleties...

**Comment by Blind4Basics** [comment]
Sure. Just an idea on drawing more attention to what's actually "there".

**Comment by kazk** [comment]
@Blind4Basics Please avoid issues with multiple topics.

![image](https://user-images.githubusercontent.com/639336/88611812-b7e4db00-d03e-11ea-908b-db3a8871408a.png)
is a bad sign.

It's already difficult to post a reply because I have to quote each part.

---

> as you can see in the picture above, there is a small bug when the mouse is over the sidebar: beginnings of the labels are showing up before the menu reveals itself.

I assumed that was intentional, peeking before actually revealing all. But not sure. Can you open a separate issue?

> kumites. Those could need a topic on their own.... Not the place for it. Since I still don't get what they really add to CW

Yeah, it started as an experiment, and the experimenter forgot about it :laughing: It's been useful for bug reports for the runner at least. And doing some basic code reviews.

> `Kata` and `Kumite` are the labels while plurals would look more appropriate to the contents.

Users can use `katas`/`kumites` if they want, but we won't inflect Japanese loan words, as I explained in the docs repo.

I think changing to
> :mag: Kata 

will make it significantly clearer.

> The "forum" button should just be removed, imo:

Forum will be replaced with [Discourse](https://www.discourse.org/) instance that you login with your Codewars account. And we'll stop using the term "Discourse" within Codewars to avoid confusion.

> why "account settings" and "training setup" are separated? 

Because those two are separate things? But I guess we can consider removing "Training Setup" from there and add a link to it inside "Account Settings".

> while a new kata cannot be created from the kata search page (which might actually be a good idea, to see less "hot garbage" showing up?).

Not sure about reducing garbage, but we can consider this.


> add a link to the profile of the user in addition to the link currently in the top right corner 

Is it really necessary? You can just click the avatar to go to your profile. "View Profile" is mainly for the mobile UI where clicking the avatar opens the menu.


> add the kata search page above "new kata"

I don't think it makes sense to be under profile menu. We can think about how to encourage users to search first before creating new kata in some other way.


> add the images used in the left menu bar for katas and kumites to the related items in the user's profile menu.

We can use the icons currently used on the left sidebar for those, but I'll probably change the kata icon on the left sidebar to search icon (:mag:).

**Comment by kazk** [comment]
The sidebar was updated. For anything else, please open separate issues.
