### ISSUE TITLE
CodeMirror: enable autoindentation "sensitive to what the user wrote on the previous lines"

### ISSUE THREAD

**Issue by Blind4Basics** [codewars/codewars.com#2191]
![image](https://user-images.githubusercontent.com/32236948/86517094-60c85d80-be26-11ea-8855-856dfbc7d85c.png)

The auto-indentation is currently not keeping the indentation that was introduced by the user. In the picture above, I'd expect the "pointer" to be aligned with the definition of `j`.
=> is there a way to enable autoindentation aligning with the previous line if not "entering a new syntaxic block" (I mean: just after opening curly brackets in JS/java or after the colon of a condition or a loop in python, ...).

**Comment by kazk** [comment]
> => is there a way to enable autoindentation aligning with the previous line 

I don't think so because that contradicts with auto indentation (indent based on syntactic context). But it's possible that CodeMirror supports it so feel free to experiment and let me know.

> if not "entering a new syntaxic block" (I mean: just after opening curly brackets in JS/java or after the colon of a condition or a loop in python, ...).

Not sure if I'm following. I think it's indented from the opening curly brace already?
```javascript
return Object.keys(cs).reduce((s,k)=>{
__
}, 0);
```
`_` denoting the space.
