### ISSUE TITLE
Include solution in the test case

### ISSUE THREAD

**Issue by afonsomatos** [Codewars/codewars.com#22]
I'm writing a test case that is very random and so I want to get the result from the complete solution.

Something like this:

Test.expect( myFunction(val), userFunction(val), "Wrong value for " + val);

**Comment by afonsomatos** [comment]
I could copy-paste the solution in the test case.. But there should be a feature for this.

**Comment by bkaes** [comment]
> I could copy-paste the solution in the test case.. But there should be a feature for this.

This sounds like a feature request instead of a actual issue. I'm not sure whether Jake and Nathan use github for everything instead of the [respective forum](http://www.codewars.com/topics/feature-requests).

That being said, I think that this isn't feasible. Your own function should pass the test, therefore it needs to have the _same_ name as the function provided by the user. So you would need some kind of automatic renaming. Given that some solutions use additional functions on the global namespace, it can be tricky to get renaming right, e.g.

```javascript
// function that solves the kata
var createPrimeNumbers = function( start, stop ){
    var res = [], i;
    for(i = start; i <= stop; ++i)
       if(isPrime(i)) res.push(i);
    return res;
}
// additional helper function
var isPrime = function(n) { /* ... */ }
```
Which one should be renamed? Which one is the actual solution, which is the helper function? In order to create a service that provides a _convenient_ way to copy and paste the solution, the service needs to solve those questions. I guess this isn't feasible, at least with Codewars' current resources.

After all, it's 20 additional seconds for your: copy and paste to your editor, put the functions into a hidden scope, rename the reference solution, and you're done.

-----
By the way, I do this random testing for all my kata tests, it really takes only ~20 seconds in JavaScript/CoffeeScript/Ruby/Python and even less in Haskell ;). It takes much longer to generate the _right_ random values IMHO.

**Comment by jhoffner** [comment]
This is definitely an enhancement and something we want to add. Especially for strongly typed languages, it is needed to try to detect what libraries are being used (to do things like restrict usage). 

It may take a bit for us to get it in there, and it would be a language by language rollout. Will update with an ETA once we set our sights back onto the next set of code execution engine upgrades.
