### ISSUE TITLE
Bug and inactive discussions

### ISSUE THREAD

**Issue by nmaxcom** [Codewars/codewars.com#220]
I've left messages in a couple katas but doesn't seem very active so I don't get any response and my seemingly correct code doesn't get accepted by the system.

When you train katas and submit solutions or have issues like this one, the site seems a bit forgotten.

Example from http://www.codewars.com/kata/554ca54ffa7d91b236000023/discuss#567cfcd4e44c476db7000032

> x = 3 - Expected: [1,2,3,1,1,2,2,3,3,4,5], instead got: [1,2,3,1,1,2,2,3,3,2,4,5,1]

Yet, if I run it in Cloud9 for example:

> Neithan:~/workspace $ node main.js 
> [ 1, 2, 3, 1, 1, 2, 2, 3, 3, 4, 5 ]

Which is the right answer :\

**Comment by kazk** [comment]
Closing this because I don't think this is Codewars issue, and many people solved that kata in JavaScript since this issue was reported.
One possible explanation is that some code executes differently depending on the versions of Node (V8). For example, `const` used to have function scope outside of strict mode.

**Comment by kazk** [comment]
If this issue was about getting responses in general, there's a [kata-solving-help](https://gitter.im/Codewars/codewars.com/kata-solving-help) channel on gitter.
