### ISSUE TITLE
Remove "Average Power User Assessed Rank" from kata editor

### ISSUE THREAD

**Issue by FArekkusu** [codewars/codewars.com#2207]
It looks like this info was added at some point to show how PUs' opinions are different from the general public's ones, but as of now it serves no good purpose:

* It's not clear whose votes are counted towards this metric (_we_ generally consider PUs to be users with 6k+ honor, but it's not clear what criteria is used in this particular case).
* It's not clear how this metric is tracked (is it updated every time you view the kata editor, or is there some running total that gets incremented when a user votes, so it's possible for a "non-PU" to cast a vote, become a "PU", and their choice will not be accounted for because it was made before the "promotion").
* Assuming the criteria for being a PU in this context is having 6k+ honor too, almost all the votes are counted both towards the "average rank" and the "average PU rank", but they always end up differing by 1 kyu (which could be explained by different rounding if this is all true), so this metric is practically meaningless nowadays, and only leads to confusion that there's a separate group of people who underrank everything compared to the general public, when, in fact, there is none.

┆Issue is synchronized with this [Clickup ](https://app.clickup.com/t/2me1djx) by [Unito](https://www.unito.io)

**Comment by Blind4Basics** [comment]
thing is, the usul average has its troubles too. Afaik:

* regular avg is a ceiled value
* PU avg is rounded, (but I believe it's in "bank fashion", meaning that `x.5` is sometimes rounded up, and sometimes down, depending on the parity of the result

@kazk: if a change needs to be done here, imo the best (quick) option would be to remove the integer values and just drop the float result instead.

related: #1999

**Comment by kazk** [comment]
Yeah, that number is pretty much pointless. See:

> And I just found out that "power user" in this context is users with at least 500 (!) honor points. Almost everyone assessing rank is "power user" (only `[100, 500)` are not) and `avg` is the average of all assessments, so it's pointless. The number is hardcoded and looks like it wasn't updated over time.
>
> https://github.com/codewars/codewars.com/issues/2030#issuecomment-630615184

CW has many WTFs like this from over the years.

> It's not clear how this metric is tracked (is it updated every time you view the kata editor, or is there some running total that gets incremented when a user votes, so it's possible for a "non-PU" to cast a vote, become a "PU", and their choice will not be accounted for because it was made before the "promotion").

The number is updated whenever a rank assessment is done. So in your example, their choice will not be accounted for until the recalculation is triggered.

> which could be explained by different rounding if this is all true

Good point. I just checked and the power users' average is rounded to the nearest. The average of all is not rounded and is truncated implicitly when stored in the database.

> if a change needs to be done here, imo the best (quick) option would be to remove the integer values and just drop the float result instead.

The field is an integer field so it's not quick.

How does this relate to #1999?

---

I don't think showing an average is helpful to begin with. If we're going to keep the current beta process largely unchanged, I'd show a sparkline:

![image](https://user-images.githubusercontent.com/639336/88095748-7211a980-cb4a-11ea-80d5-a2e58773cbec.png)

The root cause of all the conflicts between users when assessing ranks is that everyone have their own scale. Like I've been saying, this is Codewars' fault for not providing any guidance over the years.

**Comment by Blind4Basics** [comment]
> How does this relate to #1999?

it doesn't, typo... XD it's #1939

**Comment by FArekkusu** [comment]
> I don't think showing an average is helpful to begin with. If we're going to keep the current beta process largely unchanged, I'd show a sparkline

I wanted to open a feature request to show a breakdown of all the votes (a bar graph would be great) exactly for this reason, but kinda forgot about it :(

**Comment by Blind4Basics** [comment]
that's #1939 actually. But the thread got crowded about other topics... (my fault... x) )
