### ISSUE TITLE
Feedback on new Markdown style

### ISSUE THREAD

**Issue by FArekkusu** [codewars/codewars.com#2212]
After the tonight's update, some markdown elements styling changed (there may be something I haven't seen yet, and it's not mentioned here):
* the text and headers font got bigger
* links are not white instead of being grey
* in-line code became bold
* in-line code and code blocks are rendered in italics when editing them (this changed with an earlier update, but I decided to mention it here too, because IMO it's very inconvenient when trying to align text)

I thnk these changes are not intentional, but who knows.

**Comment by kazk** [comment]
I replaced the Markdown style with [@tailwindcss/typography](https://tailwindcss.com/docs/typography-plugin/) plugin. So it is mostly intentional.

The original style had annoying issues like:
![image](https://user-images.githubusercontent.com/639336/88773396-e5ad4b00-d136-11ea-82fa-98f654f7165b.png)
because styling Markdown can be tricky. For the above, it can produce `<p>` inside `<li>` in some cases. I decided to replace it because the original CSS was difficult to change and that plugin was recently released and I use that plugin for the new documentation.

I can tweak the colors and some styles, but I'd rather not customize too much of the sizes and spacing because I trust them way more than myself about typography. I did consider making all the heading sizes smaller, but I decided against it. Some kata descriptions look awful at the moment, but I'm hoping the new style will help improve the readability over time as it gets adjusted. Like encouraging the proper use of heading levels. Having multiple `h1`s in kata description is wrong.

> in-line code and code blocks are rendered in italics when editing them

I'm not sure what caused this one.

**Comment by kazk** [comment]
> in-line code and code blocks are rendered in italics when editing them

For some reason, Markdown code span and code block without language have `cm-comment` class and comments are italics at the moment so that's the cause.

> IMO it's very inconvenient when trying to align text

Adding language ID turns the block syntax highlighted like normal editor and shouldn't be italic anymore.

**Comment by kazk** [comment]
> - the text and headers font got bigger

The base text size should be the same 16px. I'm planning make it change depending on the screen size later.

The header sizes did change and it's intentional. I'm hesitant to change them because it'll break the balance with spacing like margins. Maybe I underestimated the number of kata descriptions with `h1`s.

> - links are not white instead of being grey

The color have higher contrast, following the plugin's style. I think it's better to let it stand out.

> - in-line code became bold

It's slightly heavier than the base text and it has higher contrast color. I'm unsure about this one and willing to change.

**Comment by FArekkusu** [comment]
> > the text and headers font got bigger

> The base text size should be the same 16px

I wasn't really sure where the regular text's size changed. Looking at it now, it indeed seems to be the same as before.

> The header sizes did change and it's intentional. I'm hesitant to change them

I think it's okay as is. If somebody doesn't like how the headers changed, they can always update the description.

> > in-line code became bold

> It's slightly heavier than the base text and it has higher contrast color

IMO, it is too heavy. Inline code looks kinda fine by itself. but in the middle of the sentence it looks like plain bold text with a smaller font size, and different background color (which became less noticeable now, at least in dark mode):

![image](https://user-images.githubusercontent.com/31668662/88830058-1c866e00-d1d6-11ea-9941-ae28991f1eb4.png)
![image](https://user-images.githubusercontent.com/31668662/88830210-4e97d000-d1d6-11ea-8a19-d087d2cc93f7.png)

> > links are not white instead of being grey

> The color have higher contrast, following the plugin's style. I think it's better to let it stand out.

IMO, links became less recognizable now. They're easier to read, but it is harder to differentiate the links from regular text, and having to rely on underlines instead of having a strong visual cue in the form a different color feels weird now:

![image](https://user-images.githubusercontent.com/31668662/88830722-075e0f00-d1d7-11ea-9c80-759f6208b93b.png)

**Comment by kazk** [comment]
Thanks for the constructive feedback!

Some of these might be caused by the font we use lacking support for appropriate font weights.

**Comment by kazk** [comment]
![image](https://user-images.githubusercontent.com/639336/88858880-91917d80-d1ad-11ea-823e-cf4673abeb2b.png)
![image](https://user-images.githubusercontent.com/639336/88858923-a9690180-d1ad-11ea-8fd5-f08978c73829.png)

Reduced the font weight of the code span and used the rounded border instead of background color to emphasize it.

Changed the color of the link text.

**Comment by kazk** [comment]
Deployed the changes and opened a separate issue (#2213) for the editor italicizing.

Please open new issues if you find any other regressions in readability/accessibility.

**Comment by FArekkusu** [comment]
> used the rounded border instead of background color to emphasize it

Background color looked quite nice, but I think either way is fine.

IMO there's not enough contrast between the `<span>` border color and the page's background color. In light mode the borders are more or less visible, but in dark mode I can hardly see them.

___

After playing around with border colors I found out that making `border color = text color` in light mode, and increasing the alpha to `0.75` in dark mode *really* improves everything.

The following screenshots were taken [here](https://www.codewars.com/kata/5f1e3fba8f51e10010cf446a).

Before:

![image](https://user-images.githubusercontent.com/31668662/88894480-99562e00-d250-11ea-8c43-c4d73e654d1a.png)
![image](https://user-images.githubusercontent.com/31668662/88894488-9bb88800-d250-11ea-9253-90e30ae4ca6f.png)

After:

![image](https://user-images.githubusercontent.com/31668662/88896543-a3792c00-d252-11ea-92d2-b711b9a531b3.png)
![image](https://user-images.githubusercontent.com/31668662/88897349-c9530080-d253-11ea-8b3a-83bfe017ac1c.png)

**Comment by Blind4Basics** [comment]
borders look a bit too much visible, here. I feel like looking at buttons. Maybe an intermediate between those 2 versions?

**Comment by kazk** [comment]
> IMO there's not enough contrast

That was intentional. I didn't want the borders to be that visible, but I'll try tweaking it.

**Comment by docgunthrop** [comment]
Looks like some katas got impacted more than others, particularly those with HTML interpolated in the markdown and/or those with images. Some of my katas descriptions that contain images appear to have changed alignments, resulting in some overlap of elements (e.g. text over image).

Here's myjinxin's kata with a description that got blown up: https://www.codewars.com/kata/59a67e34485a4d1ccb0000ae

**Comment by kazk** [comment]
I know some descriptions looks awful. Especially those that uses `h1`. But it's usually easy to fix and it should improve the readability after fixing. I've updated some of myjinxin's.


> Some of my katas descriptions that contain images appear to have changed alignments, resulting in some overlap of elements

Which one? I might be able to suggest some solution.

In general, try minimizing the use of HTML and custom styles unless it's really necessary. Avoid using obsolete tags (like `<font>`) and attributes (like `align`) because changes to options for HTML sanitizer can remove them. I can't check for custom styles when making changes.

I do think it'll be nice to have some Markdown extensions for common constructs to have consistent look and am open to suggestions. Things like info/warning containers.

**Comment by kazk** [comment]
By the way, myjinxin's kata blew up because he has weird HTML like:

```html
<p align="center"><font size=5><b>I guess this is a ?kyu kata. series #2:<br>Merge strings<br><font size=3></b></font></p>
```
at the top, which doesn't close the `<font>` tag and wraps the rest inside it.

![image](https://user-images.githubusercontent.com/639336/89231323-f24bfc00-d599-11ea-849d-bb0f18fdf6a8.png)


It was already broken before the Markdown style update which was just CSS change. The update just made it more noticeable.

**Comment by Blind4Basics** [comment]
seems there has been some update somewhere in the last 8 hours (dunno if it's you or the engine itself), but it seems that currently, _inlined code blocks_ used inplace of code spans aren't rendered anymore.

see: https://www.codewars.com/kata/597a264ad9416c38230000eb

**Comment by hobovsky** [comment]
I always thought that triple backticks are invalid for inline code spans and they just happened to work accidentally :)

**Comment by Blind4Basics** [comment]
sounds reasonnable, yes. But there are _A LOT_ of descriptions doing this... :/

**Comment by kazk** [comment]
> seems there has been some update somewhere in the last 8 hours

I didn't change anything that affects how Markdown is rendered. That inline triple backtick is not new. It should be like that since we started using CommonMark (years).
