### ISSUE TITLE
KaTeX math sometimes doesn't render

### ISSUE THREAD

**Issue by dramforever** [codewars/codewars.com#2222]
#### Describe the bug

Sometimes the math just... doesn't render. Refreshing seems to fix it.

It occured to @Blind4Basics on [Cracking the digital hash lock][hashcode-lock] (at the end), and I've seen kata mentioning something like 'if you don't see the math render, refresh', but I can't remember where. So this is definitely a problem.

[hashcode-lock]: https://www.codewars.com/kata/cracking-the-digital-hash-lock

Need details from users who have experienced this.

#### To Reproduce

1. Go to a kata where the description has math
2. Hope you can reproduce the issue
3. See that the math is not rendered despite being correctly formatted in markdown

#### Screenshots

(Missing, to be filled in)

#### Contexts

(Missing, to be filled in)

Please complete the following information:

- OS: ?
- Browser: ?
- Browser Version: ?

**Comment by Blind4Basics** [comment]
* OS: Win7
* Browser: firefox 79.0

screenshot:

![image](https://user-images.githubusercontent.com/32236948/89628822-232f7800-d89d-11ea-9c28-b61dd422e6e8.png)

Happened again. I feel like it could be the same problem than the one about the links to the coments that is not making the screen scroll down when the user lands on the page... (?)

**Comment by DonaldKellett** [comment]
- OS: macOS Catalina 10.15.6
- Browser: Firefox 79.0

Screenshot:

![Screenshot 2020-08-07 at 17 05 10](https://user-images.githubusercontent.com/7777884/89629370-4a536d00-d8d0-11ea-9542-4e7398a29796.png)

To reproduce, visit a Kata with KaTeX in its description for the first time since boot. Refresh the page once and the problem does not appear again until the next boot.

I actually noticed this back when KaTeX support was first added but didn't consider it an issue worth reporting ¯\\\_(ツ)\_/¯

**Comment by FArekkusu** [comment]
Kazk said somewhere that the first time you open a page using KaTeX markdown, some dependency, or whatever, is loaded without which it can't be rendered correctly,

**Comment by dramforever** [comment]
Yeah, I feel like this is a known bug, but I found no issue tracking it so I opened this.

**Comment by kazk** [comment]
@dramforever Thanks for opening it. I was going to fix it when I commented on Codewars, but had something else come up and forgot to.

I'll probably just include the JS in the application bundle.

**Comment by kazk** [comment]
Fixed
