### ISSUE TITLE
Give authors the ability to pin solutions

### ISSUE THREAD

**Issue by ddejohn** [codewars/codewars.com#2237]
## Problem

Objectively bad solutions voted up as `clever` and `best practice` en masse by inexperienced coders when the solutions are neither.

## Solution

Give the author of the Kata the ability to "pin" solution groups, and **hightlight them** as `best practice` and/or `clever`.

## Alternative

Allow authors to secretly "downvote" bad solution groups to move them to the bottom of the pile, and "upvote" good solution groups.

**Comment by hobovsky** [comment]
You assume that authors can tell good solution from poor one.

**Comment by ddejohn** [comment]
That's a fair point, but I think that'll be less common in general than the poor solutions that get upvoted by the masses.

**Comment by FArekkusu** [comment]
You also assume that authors will not pin their own solutions only, or push other solutions away from the top... Either option is bad.

**Comment by ddejohn** [comment]
> You also assume that authors will not pin their own solutions only

So don't let them. For your other point, I'd be willing to bet that not many people would actually do that, and being able to stop inexperienced coders from being exposed to bad practices is worth the trade-off of potentially a few bad apples abusing the system.

**Comment by FArekkusu** [comment]
> So don't let them

What if the author's solution is genuinely good?

___

* And what if the author pins a solution, and something better gets submitted in the future? Should the author constantly check every kata they've authored in every language to find these? Or should the users constantly nag the author in the kata discourse to pin their solution because they think it's good?
* And what if the author pins something, and stop using CW altogether? Or the author hasn't been active for years already, and nothing can be pinned? Who will be doing all this work in their place? Letting PUs will definitely lead to cheaters/noobs/trolls abusing the system.
* What if the author doesn't know what's good or bad, and they pin random solution only because it looks "cool" or "readable"?

There's no way such a system could work with so many assumptions. It'd be much easier to explain in the comments why some solution is not good despite having many upvotes, instead of having solution-pinning feature on CW.

**Comment by shadowninja-coder** [comment]
What about giving a very huge amout of extra weightage to an upvote by an ranked user. 
Or something like giving a tag of **programmers  choice** or something like that to a solution.

**Comment by kazk** [comment]
Closing because I don't think this will work well.

Proposals to fix Codewars issues are welcomed as long as it's not a duplicate and I appreciate the efforts. Unfortunately, many of the problems are often more complex than they might seem like at first.

---

(This is just a brain dump)

I don't like how solutions are currently voted and sorted, but there are many factors involved, and it's difficult to fix in a short term.

The first obvious problem is that "Best Practice" and "Clever" is not well-defined. I was thinking of letting the community classify solutions instead. For example, by describing the solution with combinations of predefined tags, which is basically "explain in the comments", but in a format easier to aggregate. This will produce more meaningful insights at least. But I don't think this will scale well considering the number of solutions and the number of users willing to spend the time tagging them.

Another problem is that the most users are not capable to review others' code because they are using Codewars to learn the basics. Increasing the dimension, by classifying with a combination of multiple tags instead of clicking buttons with vague labels, should help to identify those, but how much can we trust?

Gamifying code review to collect these data might be interesting, though. It's difficult to rate the users' ability to code review, but maybe it can be done by measuring the difference from the reviews by few trusted users. Once a users' ability to review a solution in a language is rated, their reviews for the language can be amplified.
