### ISSUE TITLE
Add Nim support to CodeMirror

### ISSUE THREAD

**Issue by hlaaftana** [codewars/codewars.com#2243]
Nim currently uses Python syntax highlighting because CodeMirror does not have Nim support. Someone seems to have written a mode for Nim: https://github.com/stisa/nim-codemirror-mode. However, I found this mode via Google and it was released relatively recently, so it might be buggy/unfinished. If it is missing features, it would still most likely be preferable to Python syntax highlighting.

**Comment by kazk** [comment]
I tried, but it sets `cm-error` class all over the place so it'll look like this on Codewars.

![image](https://user-images.githubusercontent.com/639336/93288080-f4f06280-f78f-11ea-94c2-6ef2d3593249.png)

https://play.nim-lang.org/ "looks" fine, but that's because they're not styling `cm-error`. The same issue is happening there, so both https://github.com/stisa/nim-codemirror-mode and the original https://github.com/PMunch/nim-playground-frontend/blob/master/codemirror/mode/nim/nim.js should be fixed.

![image](https://user-images.githubusercontent.com/639336/93288038-d7bb9400-f78f-11ea-8191-c02cb99204cd.png)

https://github.com/PMunch/nim-playground-frontend/blob/3891f1805af7c1ebdbf7d0eb130a70f668270bea/codemirror/mode/nim/nim.js#L191 should return `null` instead of `ERRORCLASS`.

![image](https://user-images.githubusercontent.com/639336/93288510-cfb02400-f790-11ea-9456-eba684c9e15a.png)

**Comment by kazk** [comment]
Deployed with a copy of a patched version.

**Comment by hlaaftana** [comment]
Another error that should be removed:

https://github.com/stisa/nim-codemirror-mode/blob/168d87d703d63bc80807b8d472dde13df3699065/index.js#L571-L579

This code doesn't account for the `..` operator or code like the following (even if it is weird): 

```nim
echo "abc".
  len
```

**Comment by kazk** [comment]
Can you contribute to https://github.com/stisa/nim-codemirror-mode (both this error and the one I mentioned)? Then I can use that package instead.

I was going to open PR there, but got lazy.

**Comment by hlaaftana** [comment]
PR has been merged

**Comment by kazk** [comment]
Thanks! I'll let you know when it's deployed.

**Comment by kazk** [comment]
Deployed. If you find any other issues, please let me know by commenting here after fixing the package, so I can update it.
