### ISSUE TITLE
Kata Submission

### ISSUE THREAD

**Issue by gimmeACookie** [codewars/codewars.com#2246]
#### Describe the bug

Clicked "attempt" on a kata, then modified code and clicked test so i dont submit by accident.

Click "attempt", dont click "submit" after that.

#### Expected Behavior

For solution to not be submitted and kata to be completed.

Please complete the following information:

- Codewars username (if account related): UniqueLoginSucks
- OS: Windows 10
- Browser: Chrome
- Browser Version: 85.0.4183.121

**Comment by gimmeACookie** [comment]
Hello,
i wouldnt mind that the solution got submitted, problem is that i stumbled upon cheat solution by accident and wanted to verify if it works on attempt/submission aswell to know if i should save it and post it as an issue later.
Sadly after some time when i progressed significantly on the kata, i found out it got submitted. I also lost all my progress and im not sure if it has something to do with the submission.
Id like to know if you can confirm from some logs what happened - i didnt click submit, i also didnt open tab with solutions so far to copy someones solution.
Is it possible to fix  my situation or am i gonna be "forever cheater" and have to create new account and rewrite my solutions so they dont look like copies or start using different site than codewars?
Thanks.

**Comment by hobovsky** [comment]
Yeah I love how everyone only "tests" cheat solutions on purple and blue kata instead of "Multiply" or some other white... ;)

**Comment by gimmeACookie** [comment]
Dear donald.
Please, take a look at my account and the bug solution in question.
1. From my account its clear im doing only low number of higher tier kata so no, whites wont happen.
2. Cheat solution is kata specific and its clear that anyone echoing debug data at some point can easily stumble upon the same thing i did and possibly submit without realizing hes cheating.

**Comment by kazk** [comment]
Hi @gimmeACookie

I think everyone is just confused, so I'll try to clarify.

Kata trainer buttons:

- "Attempt": Attempt to complete the challenge using the solution. If that passes all tests, it marks the kata completed. Training again means starting a new solution.
- "Submit": Submit the final version to be listed it in solutions page.

Even though it's confusing and it's not ideal for multiple reasons, this is currently how it works and it's not a bug.

---

> I also lost all my progress and im not sure if it has something to do with the submission.

I'm assuming you meant it was reset to the original code. That's probably because you had opened the trainer after completing the kata (attempted and passed all tests). This is not a bug.

---

> Cheat solution is kata specific

Please let the author know by commenting on the kata discussion.

> Is it possible to fix my situation or am i gonna be "forever cheater"

No, you're not considered a cheater at all. If the kata is doing something unusual and allows solutions to pass accidentally, then the kata needs to be fixed. If it's something that affects all kata in that language, then please let me know by opening an issue at [runner repo](https://github.com/codewars/codewars-runner-cli) so I can try to fix it.
