### ISSUE TITLE
Give the objective ranking of users solutions

### ISSUE THREAD

**Issue by tsedii** [codewars/codewars.com#2251]
Now users' solutions can be sorted by 'Best practices', 'Clever', 'Newest', 'Oldest'.

But there are no any objective ranking criteria for users' solutions.

I am proposing to create two new criteria for it:

First - The time duration of Fixed tests for each kata's solution.

Second - The size in bytes of each kata's solution. Without taking into account spaces, tabs, CRLF and users' objects names length.

**Comment by hobovsky** [comment]
You can read #959 (and a bit of #1409) to see why your first proposal is not that good. The second one is IMO also far from good, because it would promote code golf solution, what is bad enough itself, but additionally could be completely replaced by your first proposal: just sort by execution time in reverse order (slowest first) and you would get pretty much similar result ;)

**Comment by tsedii** [comment]
@hobovsky, I agree with you. Thank you for your time.
