### ISSUE TITLE
Can't signup with github account

### ISSUE THREAD

**Issue by vitoyucepi** [codewars/codewars.com#2254]
**Describe the bug**
I've tried to signup with my email and github account. But I can't use my email.

**To Reproduce**
1. I open signup page and see signup form. This is OK. https://i.imgur.com/qavwlKx.png
1. After oauth with github account. I see that github is linked and my name is filled in signup form. https://i.imgur.com/1WEQwh0.png
1. If I try to input my email and submit the form, then it'll say that my email is already in use. https://i.imgur.com/kIW1dqm.png
1. If I try to restore my account with "Forgot password", then it'll say that my email is not found. https://i.imgur.com/fV6Wq9Z.png

**Expected behavior**
Allow to register with cock.li email address. 

**Additional context**
I'm not sure if you use blacklist or whitelist for email providers.
But I do want to use this email address, because it's already linked to github, gitlab and other services. https://i.imgur.com/NF8HDgo.png
I know that cock.li is not a mainstream provider like google.

**Comment by kazk** [comment]
> I'm not sure if you use blacklist or whitelist for email providers.

We use [mailchecker](https://github.com/FGRibreau/mailchecker) to blacklist disposable email providers because we had issues with spammers in the past. Looks like `cock.li` is in it. See https://github.com/FGRibreau/mailchecker/blob/a937877319d33f5c7b6b25f0666f3256e8846f5e/list.txt#L7346 (may take a while to load).

This is why you're getting the error email is already taken. This error message is _intentionally_ misleading.

> But I do want to use this email address, because it's already linked to github, gitlab and other services.

The screenshot of GitHub says "Cannot be verified" and it means:

> You cannot verify email addresses from disposable domains. If you'd like to keep your email address private, you can use a GitHub-provided noreply email address. For more information, see "Setting your commit email address on GitHub."
>
> https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/verifying-your-email-address

So even though GitHub allows you to register with it, they think it's a disposable email as well and you're restricted because of the unverified email address.

We won't allow registering with disposable email addresses and you also need to verify your email in order to use Codewars fully.

**Comment by vitoyucepi** [comment]
But for me it's not disposable. It has bad reputation because it allow you to register email without phone check.
I can do the same with protonmail.

Yes ones I had problem with github tempblock. But the day after I wrote them a letter they unlocked me. So now I have no restrictions.

Also gitlab has marked my email as verified. https://i.imgur.com/0ETrXoz.png

**Comment by vitoyucepi** [comment]
Can you add a distinct error message that profile can't be registered with email instead of "is already taken".
Something like "email address is invalid" or "email address is blocklisted" or "email address has bad reputation" or at least "unable to register".

**Comment by kazk** [comment]
You might want to open a Pull Request to https://github.com/FGRibreau/mailchecker because a lot of services uses it like us.

For the error message, I made it intentionally confusing, but I'll consider changing to "invalid".

**Comment by vitoyucepi** [comment]
They already had a bunch of pr-add-remove discussions.
FGRibreau/mailchecker#245
FGRibreau/mailchecker#218

I'm not sure if it's right to allow everyone to register with easy-to-register email providers. Maybe some kind of sandbox.

As for me I want to solve puzzles, but sometimes signup buttons are very-very annoying. So I decided to register, but I can't register with only github. As you see I have failed with email.
