### ISSUE TITLE
Hello, kata name Highest and Lowest bug

### ISSUE THREAD

**Issue by IvanShadrin-97** [codewars/codewars.com#2256]
My python code:
def high_and_low(numbers):
    num_list = list(map(int, numbers.split()))
    return print(f"\'{max(num_list)} {str(min(num_list))}\'")

When im tested this code all logs same with answers, but test not passed... wish this will fix.

**Comment by hobovsky** [comment]
Kata specific issues should be reported in kata discourse ([here](https://www.codewars.com/kata/554b4ac871d6813a03000035/discuss), not here on this board. This board is used for tracking issues related to Codewars platform, and not specific kata.

Your code is incorrect. Your last line does not return what it should return. Kata is good, your solution is wrong.

Regards

**Comment by hobovsky** [comment]
You can read [this paragraph](https://github.com/codewars/codewars.com/wiki/Troubleshooting-your-solution#expected-the-same) of FAQ for some hints. One of bullet points there describes your problem.

Also read [this part](https://github.com/codewars/codewars.com/wiki/Markdown-Formatting#block-code-formatting) of manual on how to post your code.

**Comment by IvanShadrin-97** [comment]
I told you i'm started from:
return max(num_list), min(num_list) 
to:
print(f"\'{max(num_list)} {str(min(num_list))}\'") 
yes i fogot "\" but its still dosent work! log with answers is same !!!
try it by your self and watch log!

**Comment by DonaldKellett** [comment]
@IvanShadrin-97 You're confusing `print` and `return` - please see [this StackOverflow post](https://stackoverflow.com/questions/750136/how-is-returning-the-output-of-a-function-different-from-printing-it) for the difference between the two.

Anyway, as @hobovsky mentioned, Kata-related questions and/or issues should be directed to the Discourse page of the Kata itself instead of this GitHub repo.
