### ISSUE TITLE
Internal Server Error on solution group voting and commenting

### ISSUE THREAD

**Issue by Blind4Basics** [codewars/codewars.com#2263]
[Counting Duplicates](https://www.codewars.com/kata/54bf1c2cd5b56cc47f0007a1/)

For a reason I don't get, I cannot up or down vote any solution or comment of this kata.

* tried in JS and python: same thing
* tried on another kata: no problem
* tried in the discourse page of the problematic kata: this time it works

behaviour:
* gone to the solutions page
* tried to vote for a solution => nope
* tried to vote on a comment from the solutionS page => nope
* tried to vote on a comment from the page of solution itself (the group) => nope either
* I tried reloading the page after the vote: still nothing

related information:
* in the console, the network tab is showing me the POST requests with a state 200, just like when it works, but the delays are huge (I believe?): between 2s and 4,5s (Maybe the number of completions is part of the problem: there are like 80000 completions to the kata ; 25000 in JS, 30000 in python)
* @hobovsky tried on his side: same problem

**Comment by Blind4Basics** [comment]
Seems I cannot add a new label here... `area/votes` doesn't exist

**Comment by FArekkusu** [comment]
> the network tab is showing me the POST requests with a state 200

The request is "successful", but the actual response is `{"success": false, "message": "Internal Server Error", "status": 500}`.

**Comment by hobovsky** [comment]
It could have the same cause as #2048, maybe?

**Comment by kazk** [comment]
Yeah, it's the same as #2048 and #2255. This is one of the last few major technical dept that's left.

MongoDB allows embedding documents, but you shouldn't embed documents if it grows indefinitely (i.e., if you append to embedded array of documents) because there's a size limit.
Unfortunately, Codewars doesn't use MongoDB properly. Some old documents have too many embedded documents created over the years and have reached this size limit. You can't comment, vote, add a new solution group, etc. anymore. I don't know the background of the design flaw, but it was probably just overlooked.

To fix the issue properly, I need to migrate all the nested embedded documents out to own documents and modify the code to work with them. The fix itself doesn't sound too bad. But I need to plan this carefully and allow gradual migration because it's buried in a big ball of mud and involves tens of millions of documents. I just haven't had the time for it yet and it's been on my list to do.

What I did in #2048 is a hack to reduce the document size of some documents that had reached this limit, e.g., removing unused fields and compressing text that's never queried. It doesn't fix the root cause so it comes back eventually and I also need to apply the hack manually because the operation is so intensive that it affects the overall database performance. Newer documents are created with the hack from start, so those will take longer to reach the limit.

This design is also the reason why solutions page is so slow for old kata with lots of solutions. All the solution groups for a language are embedded in a document. Each solution group embeds some information about variations, comments, and votes. Each comment embeds some information on votes. 

So it currently looks like the following:

- `review`
  - `solution_group`
    - `solution_group_vote`
    - `solution_group_item`
    - `comment`
      - `comment_vote`

As you can see, once a `review` reaches the size limit, you won't be able to do many things because it's actually modifying a `review` document.

I need to migrate the above to:

- `review`
- `solution_group`
  - `solution_group_vote`
  - `solution_group_item`
- `comment`
  - `comment_vote`

Or even move `solution_group_item` to top level.

**Comment by atirek89** [comment]
Internal Server Error, while trying to Signup

**Comment by kazk** [comment]
@atirek89 That should be unrelated. I see users signing up right now, so it can be a glitch. Please try again, and open a new issue with details if it fails again.

**Comment by radek-altof** [comment]
What is the state of this issue? Same thing for [this Kata](https://www.codewars.com/kata/523f5d21c841566fde000009/solutions/javascript).

**Comment by Blind4Basics** [comment]
still opened, so still going on. ;)

**Comment by davegregg** [comment]
same problem for the [6 kyu "Create Phone Number" kata](https://www.codewars.com/kata/525f50e3b73515a6db000b83/).

**Comment by kazk** [comment]
Fixed!
Migrated the documents larger than 7MB for now. The rest will be migrated gradually over time.
