### ISSUE TITLE
Selected code has the same background color both in dark mode and light mode

### ISSUE THREAD

**Issue by FArekkusu** [codewars/codewars.com#2277]
Selected code in dark mode has very light background color which makes the text unreadable:

![image](https://user-images.githubusercontent.com/31668662/100145483-10b76980-2ea1-11eb-975f-4c0a2228cbbb.png)

**Comment by kazk** [comment]
It's been missing the required `!important` and was using the default for both themes. I just deployed the fix.

**Comment by XRFXLP** [comment]
I guess this is also due to a similar kind of unintended keyword missing: 

Linked inline code block is hard to read in dark mode:
(Something like [`Wikipedia`](https://www.wikipedia.org/))
![image](https://user-images.githubusercontent.com/23459568/100184733-2b70f900-2f08-11eb-8f9b-486a5d39d57b.png)

But are excellent in light mode:
![image](https://user-images.githubusercontent.com/23459568/100184926-9ae6e880-2f08-11eb-9ff3-e5c24e9a7e64.png)


Or it might be the case that I've seen this for the first time.

**Comment by kazk** [comment]
@XRFXLP Thanks for letting me know. I simply didn't notice `a code {}` had a different color and didn't override it for the dark mode (maybe the update introduced it and I didn't catch it).

**Comment by kazk** [comment]
@XRFXLP The fix was deployed.
