### ISSUE TITLE
Changing email address does not affect where the "weekly kata" newsletter email gets sent.

### ISSUE THREAD

**Issue by emceekain** [codewars/codewars.com#2287]
**Describe the bug**
About a year ago or so, I changed the email address associated with my account.  I can log in just fine with the new email, but I'm still getting the "weekly kata" newsletter at the old email address (and not at the new).

**To Reproduce**
[Not really a code-related question].

**Expected behavior**
I would expect to get newsletter-type emails at the email address currently associated with the account.

**Screenshots**
[N/A]

**Browser**
[N/A]

**Comment by kazk** [comment]
Yeah, this used to happen because the list of subscribers were not updated when a user changed their emails.

I fixed this some time ago when we changed the ESP, but those who changed their email before that are not handled because it's not possible to update without knowing the previous email. A possible workaround is to change your email to the old one temporarily and back to your new one. You can also email me (kaz at codewars.com) and I can update it manually.

I'd like to make it easier to manage newsletter subscription.

**Comment by emceekain** [comment]
@kazk I'll try your suggested workaround and let you know if it doesn't work.  It's an old school email, but thankfully I still have access.  Many thanks!
