### ISSUE TITLE
This site can’t be reached error when confirming email

### ISSUE THREAD

**Issue by anonymousSally** [codewars/codewars.com#2298]
**Describe the bug**
I've tried 3 times to confirm my protonmail email address with codewars. Every time I try to click the confirm email link, I receieve a 'This site can’t be reached post.spmailtechno.com refused to connect.' error message.

**To Reproduce**
Link I clicked to try to confirm which results in error: http://post.spmailtechno.com/f/a/4Io1ug2WAZLhHjrWz4mvoA~~/AAMLTwA~/RgRh3NCeP0RSaHR0cDovL3d3dy5jb2Rld2Fycy5jb20vdXNlcnMvY29uZmlybWF0aW9uP2NvbmZpcm1hdGlvbl90b2tlbj1wdk5TNmR5R2pYcFZtNjU5eVVSSlcDc3BjQgpf9R6d-1_TP9P0UhxzYWxseWhhZWZsaW5nQHByb3Rvbm1haWwuY29tWAQAAAAB

**Expected behavior**
Confirming email is successful.

**Screenshots**
<img width="727" alt="Screen Shot 2021-01-10 at 5 41 33 PM" src="https://user-images.githubusercontent.com/77252891/104139803-1c84bf80-536b-11eb-8972-f3d82f6afd0b.png">

**Browser**
Brave browser

- OS: MacOS Catalina
- Browser: Brave, also tried in Chrome and get same error

**Additional context**

**Comment by kazk** [comment]
Hi @anonymousSally, that's the domain of the email service provider, and it should redirect to Codewars. I don't think I can help you since it's not under our control, but I see users confirming emails (few thousands in the past few days), so it might be something on your end.

Maybe check if you have any firewall/antivirus that's preventing access to that domain.
