### ISSUE TITLE
The Facebook account is already associated with a different user

### ISSUE THREAD

**Issue by oneastok** [codewars/codewars.com#2319]
I deleted my codewars account and then recreated it again. Now I got the message “The Facebook account is already associated with a different user”.

**Comment by kazk** [comment]
Thanks for reporting. We anonymize the user and facebook account information is removed as well, but there's a bug skipping `facebook_uid` field. I've fixed the data, so it should work now. I'll fix the code soon.

By the way, linking to Facebook won't do anything anymore because they changed the required scope, and we're not allowed to get the profile URL.
I'll remove the feature when I have the time.

**Comment by oneastok** [comment]
Oh! Thank you very much!

By the way, I’m trying to link the Facebook account because, as I think, it’s the only way to change my avatar. I couldn’t find any other way to do that.

Thanks for so quick response!

**Comment by kazk** [comment]
Facebook no longer allows us to get the profile image either, so that won't work. Linking GitHub account will.

Allowing users to change avatar is tracked with #1398. It's not a priority, but it's planned.

**Comment by oneastok** [comment]
Thank a lot! it works!
