### ISSUE TITLE
Broken API versioning

### ISSUE THREAD

**Issue by jamesrweb** [codewars/codewars.com#2347]
**Describe the bug**

I built an [API Client](https://github.com/jamesrweb/codewars-api-client) and have a set of schemas I use as part of the test suite [like the schema you can see here](https://github.com/jamesrweb/codewars-api-client/blob/69a14180034bb0c1cf8f7f6cab83207fbab41e9a/src/schemas/ChallengeSchema.php) for example. These have been breaking in CI recently and upon inspection I see that the API docs for the v1 API are not what the API returns and the changes since v1 should be namespaced under v2 now.

Case in hand, this is how [the v1 docs](https://dev.codewars.com/) define a challenge response via `https://www.codewars.com/api/v1/code-challenges/:id_or_slug` to have the following keys:

- id
- name
- slug
- category
- publishedAt
- approvedAt
- languages
- url
- rank
- createdBy
- approvedBy
- description
- totalAttempts
- totalCompleted
- totalStars
- tags

In actuality though, the API returns the following extra keys in the response:

- createdAt
- voteScore
- contributorsWanted
- unresolved

**To Reproduce**

Check the v1 API definitions and then the actual API response.

**Expected behavior**

That the versioning system is not broken and that a new v2 version is created for changes since the v1 release and v1 is reverted.

**Screenshots**

N/A

**Browser**

N/A

**Additional context**

N/A

**Comment by kazk** [comment]
I apologize for the inconvenience, but the documentation is simply outdated. We haven't touched the API in a while, definitely not since your project had started. For that specific endpoint, it was last changed more than 6 years ago (2014-07-18). Also, adding a new field to a response is generally not considered a breaking change either. (I do agree that it should be documented for the users to know.) 

The API v1 hasn't been in a good shape for many years (or ever), and I'm not planning to touch it. v2 is necessary to resolve the issues and expand, but it's not a priority at the moment.

**Comment by jamesrweb** [comment]
@kazk Can you give a very rough overview of the internal plan or thoughts for v2?

Related: I also raised #2305 before and we briefly discussed the current state of the API over email, would be interested in an update since then as you had mentioned you were working on the API at that time if memory serves.

**Comment by kazk** [comment]
> you were working on the API at that time if memory serves.

No, I wasn't working on it. I basically said the same thing.

![image](https://user-images.githubusercontent.com/639336/111831051-113e9a80-88ac-11eb-9130-96de7ac85b7c.png)

> Can you give a very rough overview of the internal plan or thoughts for v2?

No, I haven't even started to think about it.

You're probably frustrated with the pace of development, but I'd like you to know that I spend a lot of unpaid time to maintain it. I do work for [Qualified](https://www.qualified.io/), the company behind Codewars, but I usually have other priorities for different projects during work hours.

I took over the project around the end of 2018, and have been the only dev and admin.

![commits](https://user-images.githubusercontent.com/639336/111833152-020d1c00-88af-11eb-8b8c-4982e1fc2080.png)

As you can see in the above commit activity, Codewars wasn't actively developed for years when I took over. The codebase was in a terrible condition. I focused on major technical issues and most of them are resolved now, but the codebase is still not in a good shape. Making a change takes much longer than it should :(
I'd love to provide a better API for users like you, but there are many other things to be worked on with much higher impact.

**Comment by jamesrweb** [comment]
> No, I wasn't working on it. I basically said the same thing.

Ah, I misremembered then, my bad!

> You're probably frustrated with the pace of development

Not at all actually. Just looking to be in the loop.

> I took over the project around the end of 2018, and have been the only dev and admin.

Crazy, is the team at Qualified not able to support or is the workload elsewhere just so high? Thanks for the work to date in that case! 🙇🏻

> I'd love to provide a better API for users like you, but there are many other things to be worked on with much higher impact.

Understandable and the platform itself is great, I have used it for quite some time now personally and would like to see it grow and mature further.

I guess my only real questions left would be:

1. Has there been an internal discussion or idea to just restart with a clean slate since it's so hard to refactor?
2. Are Qualified supporting you in your efforts with the platform since their name is on it? You seem to be doing the lions share the work and yet you even do unpaid time, seems a bit unfair.
3. What are the chances of more focus being put onto the platform or is it something that they would rather retire eventually?

**Comment by kazk** [comment]
> Crazy, is the team at Qualified not able to support or is the workload elsewhere just so high?

We're a team of 2.5 devs (3 senior devs, but one is our CTO). I think we're extremely productive, considering our competitors having tens to hundreds of devs.

> 1\. Has there been an internal discussion or idea to just restart with a clean slate since it's so hard to refactor?

When I started to work on Codewars back in 2018, I almost gave up and wanted to rewrite it in [Phoenix](https://phoenixframework.org/) because I fell in love with it, and I was so sick of mutations. But I decided to at least clean some up first because it was too messy to even think about what it takes to migrate. Then it became somewhat manageable after months of struggle, so I decided to keep refactoring. If I could literally start from scratch (forgetting all the existing data in MongoDB), then restarting made more sense. It's taking long to refactor mainly because I don't have much time, even less consecutive time.

> 2\. Are Qualified supporting you in your efforts with the platform since their name is on it? You seem to be doing the lions share the work and yet you even do unpaid time, seems a bit unfair.

I don't consider the situation unfair at all. Just to be clear, they're not making me do unpaid work in any way. I just care about Codewars a lot, and decided to work on it when I can.
You can think of it like a side project with millions of global users that you sometimes get sponsored to work on. I don't know about you, but that's pretty cool to me. I admit it's sometimes stressful, especially the community aspect (e.g., dealing with problematic users and support), but it's satisfying.

> 3\. What are the chances of more focus being put onto the platform or is it something that they would rather retire eventually?

Our main focus will always be Qualified, and we're doing great. Note that Qualified's success is required for Codewars to exist. After all, Codewars doesn't make money, so it's not sustainable by itself. We also want Codewars to be accessible to anyone who wants to train their skills. If we had to monetize Codewars, I believe we'll lose a lot of its value.

There's no plan to retire Codewars. I wouldn't be spending time on it if there was :)

**Comment by jamesrweb** [comment]
@kazk thanks for the detailed response!

Well, hopefully we can see things move forward in the future and once again, thanks for all you do in maintaining the platform 🙇‍♂️

If I can somehow contribute to the API, do let me know, I’d be happy to help develop the features I’m asking for myself and contribute to the platform if you’d be able to show me the ropes but otherwise, all the best dude ✌️
