### ISSUE TITLE
My stat reset?

### ISSUE THREAD

**Issue by BadNameSad** [codewars/codewars.com#2348]
Today, I created a codewar account.
And finished some challenges.
Most of the challenges were finished using my old codes(optimized it a bit).
So, my honor got higher.
Then, I made a kata(since I got enough honor to make a kata).
It was called Max and Min of number(https://www.codewars.com/kata/6055a9563a99a0000bd96e54).
I wasn't able to find any kata similar to it.
So, I published it.
Around 5:20, my stat was reset by somebody(don't know who).
Why?
P.S. I just made this account to report this.

**Comment by Blind4Basics** [comment]
> using my old codes

what do you mean exactly?

**Comment by BadNameSad** [comment]
I once(few months ago) made a code similar to what the challenges(katas) asked me to do.

**Comment by Blind4Basics** [comment]
so you had a previous account on cw? Link?

**Comment by BadNameSad** [comment]
No. Never had one until today.
Few months ago, I was just looking through the internet for some things to challenge myself at programming.
One day, I found the codewars website(and other sites, as well).
In there, I found some challenges(like Cut the cake).
I didn't make an account.
Because there were descriptions.
I tested it as the descriptions told me to(my code wasn't perfect, though).
Now, I guess I became lazy to make a test code for myself.
So, I made a codewars account.

**Comment by Blind4Basics** [comment]
ok, let' get this straight: you're lying.

the codes you posted are deduplicated versions of other codes I could find and that are regularly used by copycats. Adding `console.log` stuff here and there, renaming variables, splitting functions a bit differently doesn't make the approach eligible. That's why the solutions got invalidated. And don't tell me you're the original authorS, because I found the accountS who posted the original solutions and you're clearly someone else.

Moreover, your speach is inconsistent:

> P.S. I just made this account to report this.

no, you completed some kata first, then solutions where invalidated then you came complaining about it.
