### ISSUE TITLE
Privacy: Github OAuth now requires access to private email addresses to login

### ISSUE THREAD

**Issue by nomennescio** [codewars/codewars.com#2366]
Recently the Codewars login procedure using GitHub OAuth changed. Codewars now requires permission to access private email addresses associated with GitHub. Without it, it's impossible to login. This was not communicated upfront, and it's impossible to login without it. I find this change unexpected, and prefer not to share private GitHub email addresses.

**Comment by kazk** [comment]
Sorry for the surprise and inconvenience.

A few days ago, I had updated OAuth libraries to fix a possible bug. When I was testing the update, I noticed that a user trying to sign up with their GitHub account must enter their email after linking, and found this awkward. I added `user:email` [scope](https://docs.github.com/en/developers/apps/scopes-for-oauth-apps#available-scopes) which is what's usually used for this flow, so the primary verified email is prefilled when signing up with GitHub account.

Sign in uses the same callback, so GitHub asks for permission to grant the `user:email` scope for existing users who signed up before the change. We look up the user with the returned GitHub uid, so we don't use the returned emails, but I understand your concern.

> This was not communicated upfront

I honestly didn't think too much about the change because this is the scope I had assumed Codewars had before looking into this update. I didn't think much about how awkward it may appear for existing users, or some might refuse because they use different emails. It should be possible to use a different scope when signing in, so I can look into that.

> and it's impossible to login without it.

For now, you can still log in with your email and password (if you've never set the password, you need to reset it).

**Comment by nomennescio** [comment]
I don't mind Codewars has access to my published public email (which it already had), but user:email gives access to (all) private email addresses, which discloses privacy sensitive information coupled to my Github account. That kind of defeats using a Github login, as I could have used a email + password combination for Codewars to begin with.

It would be useful to be able to change Codewars login to email + password if you've previously used Github login without a private email address, without having first to give Codewars access to your private Github email address(es).

**Comment by kazk** [comment]
> I don't mind Codewars has access to my published public email

I don't see public email on your GitHub profile. Did you make it private?

> user:email gives access to (all) private email addresses

Yeah, but unfortunately there's no way to get only the primary one, and `user:email` is the scope used by most apps for this flow (check other OAuth apps if you have any). We don't use other emails, but there's no way to prove that.

> That kind of defeats using a Github login, as I could have used a email + password combination for Codewars to begin with.

I believe most users use GitHub login so that they don't need to enter email/password, so requiring them to enter their email was awkward and I wanted to fix.

> It would be useful to be able to change Codewars login to email + password if you've previously used Github login without a private email address, without having first to give Codewars access to your private Github email address(es).

This should be possible already by clicking "Forgot your password?", and entering the email used for Codewars, use the password reset email to update the password, then sign in with the new password.

Again, I can look into changing the scope for sign in.

**Comment by nomennescio** [comment]
I didn't use a Github public email because of spam/privacy. That was previously OK with Codewars. Therefore I can't enter an email address for password reset on Codewars. Making it impossible to login without authorizing Codewars access to my private email addresses. As said, if this would have been the situation from the beginning, I would have made an email address specifically for Codewars.

If changing the scope for sign-in would prevent giving access to Codewars to private email addresses, I would prefer that.

**Comment by kazk** [comment]
> Therefore I can't enter an email address for password reset on Codewars. 

I don't understand this part, can you elaborate? You enter the email address you've always used for Codewars to reset password. We require email address even if you sign up with GitHub, so there has to be an email that you can enter.

> if this would have been the situation from the beginning

Yeah, this is unfortunate and I'm sorry for the surprise.

> If changing the scope for sign-in would prevent giving access to Codewars to private email addresses,

Yeah, if I can change it back to no scope when signing in, it won't affect the users who signed up before this change. I only changed it for the convenience of users signing up. The same scope is used because that's the default and I didn't think much.

**Comment by nomennescio** [comment]
> We require email address even if you sign up with GitHub, so there has to be an email that you can enter.

Had to check that, you're right!

**Comment by kazk** [comment]
Closing as wontfix. This scope is widely used, and users can reject and switch to email/password as I wrote above.
