### ISSUE TITLE
Roadmap for "infinite pending translations" solution?

### ISSUE THREAD

**Issue by nomennescio** [codewars/codewars.com#2372]
For several years, it's known that in very common situations, it's extremely difficult to get translations approved. This severely sets back the willingness of people to translate, as people might put in a lot of effort to come up with a translation with test cases, just to find it sitting around for years (!) without getting any honor points for approval. It also sets back "new" language communities which won't get the "pool" of qualified people who could approve translations.

Some suggestions have been made, on how to improve upon this situation (E.g. one of my requests to add honor points to approving translations #1518), or it has been suggested to "ask around" for approval of translation, which very rarely leads to results (at least for some specific mentioned cases).

At the moment it's unclear if this is being addressed, or will be addressed at all. Can you give some insights in sort of a "roadmap" on improving the current situation of the near impossibility of getting translations approved?

**Comment by hobovsky** [comment]
@kazk can confirm or correct if I am wrong, but from what I managed to collect from related discussions:

- There's approx. between 4 and 15 translations being approved daily (just an estimate from skimming over the logs).
- Some users can access a list of pending translations. Not many of them, and it's not just moderators, some of the users are from outside of moderation team. I have no idea if others use it, but I am picking some translations from it when I have time, and either approve them, fix them, or leave some review comments. I chose to go from newest, because these are the easiest to approve: usually they are not too far from current standards, and translators are active enough to reply to requests. Fun fact: there's currently 480 pending translations which I could potentially review (I solved the kata and I know the language of the translation). I believe for other users with access to the list, this amount can go up to thousands.
- Old translations are problematic for several reasons: the kata itself is bad and it's difficult to decide if anything should be approved into it without fixing existing part first. Or the way how translation forks work gets into a way. I am not sure where exactly maintainers placed it on their backlog, but the workflow of forks is going to be improved (see [this comment](https://github.com/codewars/codewars.com/issues/2363#issuecomment-827137443)). It would be also possible to train on forks and translations.
- Many translations is also simply bad, and they stay in limbo where no one wants to approve them, and everyone hesitates whether fix them or reject them. I personally would not be really concerned if 90% of pending C translations would disappear.
- Mods are not affected by 7-days delay, and they are able to approve or reject every pending translation they can see.
- A team of "content maintainers" is considered (see [this comment](https://github.com/codewars/codewars.com/issues/2363#issuecomment-827157824)), but it will be probably realized after functional improvements are done.

**Comment by nomennescio** [comment]
Thanks to give some insight into this. If I look at my situation, I have translations years old, because the language is esoteric with a small user base (Factor, Forth), or it are high-level Katas which few people have solved, further reducing the list of potential translation approval.

The proposal I linked to requested an honor system to be implemented to award translation approvals (under conditions to prevent misuse of course), to at least making introducing new translations a worthwhile effort for everyone. A win-win-win-win for author (potentially more upvotes), translator (ranking), approver (ranking), and the community (access to more problems in a certain language).

**Comment by nomennescio** [comment]
> I personally would not be really concerned if 90% of pending C translations would disappear.

What's wrong with them?

**Comment by kazk** [comment]
From internal chat:

> My current plan for the huge list of pending translations is to revamp the translation approval process. I think we have the following problems at least:
> 
> 1. Discoverability: Difficult to find pending translations to begin with. Fixing this is easy, but that can degrade the quality of approved translations.
> 2. Scalability: The current workflow doesn't scale well. We don't have many reviewers and reviewing is time-consuming. Fixing discoverability can increase the number, but can degrade the quality.
> 3. Workflow: The current workflow is terrible. Too much responsibility for a single reviewer. Reviewing is difficult as well because you'll need to fork it and try some solutions. Merging the translation is also problematic.
> 
> Possible solution:
> 
> - Make the translation completable. Let users solve like kata and leave feedback. They'll get rewarded for completing and giving feedback like beta kata.
> - Make them only approvable after collecting multiple approval votes. I think this vote will be different from kata approval. It's more like agree to approve or not.
> - Make a page similar to kata search for this.
> - Make merge conflict easy to fix. It should be enough to show the description with conflict markers when approving. Then making the approver fix just before merging.
> - Make kata easier to fix. Allow forking the current state to propose fix. It should be easy to fix any mistakes.
> - Allow mods to retire/pause language. As a last resort, we should be able to disable further completions.

**Comment by hobovsky** [comment]
> From internal chat:

That's the post I was looking for and could not find :/

**Comment by nomennescio** [comment]
Thanks to at least give some insights. I'm glad it's recognized that the current process is inadequate to handle the amount of pending translations, and there are ideas on how to proceed. Is there any timeline attached to this?

**Comment by kazk** [comment]
No timeline because I don't know how much time I can spend on Codewars. But it's one of the top items on my list to do.
