### ISSUE TITLE
Submission Errors

### ISSUE THREAD

**Issue by andrew-werdna** [Codewars/codewars.com#246]
So for the last 2 kata's I solve it correctly, but when I hit submit, it says "There was an error communicating with the servers. Check our Status..." and even though the status page says that everything is operational, the submit button becomes **greyed out** so I no longer have the ability to submit my correct answer. If I refresh or do anything, it loads a new kata and I receive no credit for my correct solution.

**Update** It just happened again
![screen shot 2016-02-25 at 11 47 58](https://cloud.githubusercontent.com/assets/8261769/13328735/f438ee02-dbb5-11e5-9370-3c1fcf8c14c2.png)

**Comment by Mujaddadi** [comment]
Sam issue here.  It's looks like developer has abandoned the site. Let us know please, so we don't waste our time on it. 
![image](https://cloud.githubusercontent.com/assets/2556882/13353881/01e0a140-dca0-11e5-9332-24a96ec3a109.png)

**Comment by Mujaddadi** [comment]
I am using Edge, so might be related to this issue https://github.com/Codewars/codewars.com/issues/240

**Comment by jhoffner** [comment]
MS based browsers are not well supported on the site. IE has always had issues, I assume Edge will to. Have you tried on FF or Chrome? If the issue is still happening there please let me know.

**Comment by andrew-werdna** [comment]
I only use Firefox

**Comment by Mujaddadi** [comment]
For me FF and chrome worked.

**Comment by paul-calvelage** [comment]
This has happened to me intermittently and multiple times.  I remember having to backup my code to Notepad++ and refresh to get another try.  Unfortunately, I'm not sure how to reproduce the problem.

I only use Chrome and Firefox for Codewars so I think it is safe to rule out Edge or IE as the cause of my problems, anyway.

Occasional server errors are forgivable; it's the greying out of the button that is the real crime of this bug, since it forces you to refresh and potentially lose your work.
