### ISSUE TITLE
VSCode Editor alongside emacs/vim

### ISSUE THREAD

**Issue by SeyyedKhandon** [codewars/codewars.com#2483]
Hi, 
typing and formatting the code manually is really time consuming and annoying.

Is there any plan to integrate an editor with IntelliSense/autocompletion like vscode integration in the browser like github editor, typescript playground, codesandbox etc. ?

It would be great if the vscode integration can be used in the codewars😍
like this ( just press  dot key on the keyboard (`.`) to see it):
https://github.dev/?redirect=%2Fcodewars%2Fcodewars.com

**Comment by SeyyedKhandon** [comment]
I've found an interesting editor which supports all language, `manaco-editor`:
https://github.com/Microsoft/monaco-editor
It has a good react component too:
https://github.com/suren-atoyan/monaco-react

**Comment by SeyyedKhandon** [comment]
It seems other platforms are using  `manaco`:
[hackerrank](https://www.hackerrank.com/) :
![image](https://user-images.githubusercontent.com/59599950/133733992-4a3325db-f467-41e9-9167-9a9abb59a512.png)
[typescript playground](https://www.typescriptlang.org/play):
![image](https://user-images.githubusercontent.com/59599950/133734161-388b0194-d84a-4445-8f72-db6189d1606c.png)

**Comment by SeyyedKhandon** [comment]
Thanks for the answer, but It's a basic feature that almost every platform supports, and it's kind of annoying to code on `codewars` 
without it. I think soon you need to consider it because of users.

**Comment by kazk** [comment]
We know it's nice to have, and we'd love to support it, but it's not cheap. Like I wrote above, we _might_ introduce autocompletion as a paid feature.

> It's a basic feature that almost every platform supports

I disagree. It's definitely not a **basic** feature when you need remote Language Servers. I also disagree about almost every platform supporting it. It's probably more limited than you think. Incomplete autocompletion ignoring context is more annoying than not having any.

- VS Code for the Web (github.dev) works entirely in browser, and has [limited language support](https://code.visualstudio.com/docs/editor/vscode-web#_language-support) because of it. Autocompletion in many languages only show existing tokens. It's also by Microsoft, who owns VS Code.
- TypeScript playground is only for TypeScript in the browser context.
- Services like CodeSandbox and Replit are great, but I don't think it's fair to be compared against teams focused on providing the best in-browser coding experience.
- HackerRank's free problem is a single main file, which is much cheaper to support. We have multiple files with more complex setup. I don't think they have more complex challenges for free.
- LeetCode supports it as a paid feature.

I wrote some technical details in https://github.com/codewars/runner/issues/42#issuecomment-719843804 if interested.

**Comment by SeyyedKhandon** [comment]
Thanks, I hope to see this feature soon👍
