### ISSUE TITLE
A proper way to retire new, problematic katas in beta

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/codewars.com#2560]
Let's say I'm a lazy bum who want others to solve my coding homework. All I need to do is to turn my homework problem into a crappy kata, bait for PUs, and because it is required to solve the kata before downvoting it to retirement (don't ask why this is encouraged; 4 precious, missable honor points are at stake here) by the time my kata is retired out of sight I already have fished 4 highly advanced solutions for my assignment.

This is definitely very prone to abuse. There should be easier, more responsive way to retire katas that don't require 4 separate users giving out their working solutions to the kata author.

┆Issue is synchronized with this [Clickup ](https://app.clickup.com/t/2me1e4v) by [Unito](https://www.unito.io)

**Comment by kazk** [comment]
Mods can unpublish betas. They can also remove the author's privilege to create kata if they continue to republish or create more.

**Comment by Voileexperiments** [comment]
Mods are typically much slower than PUs at detecting the existence of beta katas, so it's not working.

**Comment by Kacarott** [comment]
Perhaps new katas which reach some threshold number of issues (2?) should be automatically reverted to draft. Additionally draft katas should not be publishable with unresolved issues.

This would help deal with low effort katas, while also benefiting "genuine" authors by giving them a chance to repair their katas before being downvoted due to overlooked issues.

**Comment by kazk** [comment]
Any suggestions?

Maybe add a way to flag a kata to be reviewed by mods. Flagged kata will function like drafts, but can't be republished without approval. Mods will be allowed to retire a flagged kata.
Some things to consider: Who should be allowed to flag? How many votes should it require?

**Comment by hobovsky** [comment]
While possibility of flagging kata might be useful, I think the problem posed as it is is either exaggerated, or I don't get it:

- I think "very prone to abuse" is severely exaggerated, because it occurs very rarely.
- PUs can always choose to _not_ solve a beta kata if they discover it's bad.
- Downvoting into an automatic retirement (after solving) is not the only possibility of handling bad beta kata.
- Mods are quite responsive when notified and I would say they are very easy to reach, over Codewars main site, Discord, and Gitter. I agree that Discord might be not ideal for some users to get in touch with mods, but, well, such users kinda chose this themselves, havent they. Even if you do not want to communicate with mods, still users and mods do communicate and they pass information between them. Raise an issue on a beta and it will be handled.

I do agree that possibility of flagging every kind of content created by users, like kata, kumite, translations, posts, collections, accounts, could be a good feature to have, but I do not agree with the motivation _and_ arguments presented by OP in this thread.

**Comment by Voileexperiments** [comment]
> I think "very prone to abuse" is severely exaggerated, because it occurs very rarely.

Every kind of abuse surrounding beta process (or even the site itself) occurs very rarely. #1365 is an example. It should not be used as an excuse to leave holes in the open for years.

> PUs can always choose to not solve a beta kata if they discover it's bad

I already wrote above: `don't ask why this is encouraged; 4 precious, missable honor points are at stake here`. FFS, *some* PUs would regularly bypass the fixed tests with a hardcoded solution just to give a ranking and a downvote. It's way more common than you think.

> Downvoting into an automatic retirement (after solving) is not the only possibility of handling bad beta kata.

So how does this address the issue? We're still handing out at least 1 perfectly good solution to someone fishing for them.

> I agree that Discord might be not ideal for some users to get in touch with mods, but, well, such users kinda chose this themselves, havent they.

??????? Since when is CW Discord treated as the semi-official medium of conversation of the site? This is a blatant discrimination to people who do not want to be involved with CW Discord for various reasons, now you just shut them down the right to have their concerns addressed. (More like most of the rights, but you get the idea, since pretty much everyone prioritizes on only things raised on Discord.)

And even with that aside, you're assuming PUs will actually report problematic beta katas to Discord at once instead of farming those 4 honor points first. Track record is that nobody does. So you didn't address the problem at all.

> Even if you do not want to communicate with mods, still users and mods do communicate and they pass information between them. Raise an issue on a beta and it will be handled.

That's funny, because I keep seeing katas with various issues when I try to do new beta katas, and I'm not even that active to begin with.

All in all, please do not spread the misinformation that mods are actually active, and users act in ways preferable to the site. This has happened for a long time.

**Comment by hobovsky** [comment]
> FFS, _some_ PUs would regularly bypass the fixed tests with a hardcoded solution just to give a ranking and a downvote. It's way more common than you think.

I know it's very common, but I always considered it as showing the author of a bad kata how bad their tests are, and not squeezing out every single honor point.

> So how does this address the issue? We're still handing out at least 1 perfectly good solution to someone fishing for them.

Are we? If you know that the kata is a bait, you can raise an issue about abuse without solving it. If the main premise here is that the kata is bad (and tests are bad), then hardcode tests and raise an issue about abuse.

> That's funny, because I keep seeing katas with various issues when I try to do new beta katas, and I'm not even that active to begin with

I did not mean "various issues", I means specifically issues signaling some kind of abuse. I think these are handled quite effectively.

> ??????? Since when is CW Discord treated as the semi-official medium of conversation of the site? This is a blatant discrimination to people who do not want to be involved with CW Discord for various reasons, now you just shut them down the right to have their concerns addressed. (More like most of the rights, but you get the idea, since pretty much everyone prioritizes on only things raised on Discord.)
> All in all, please stop spreading the misinformation that mods are actually active, and users act in ways preferable to the site. If they were, I don't have to raise this issue.

Your hyperbolas are getting seriously out of hand. I do not discriminate anyone, and I do not shut down anyone's rights for anything. I do not force anyone to use Discord, even though I consider it much more effective way of communication than Gitter, and than website discourses. I like Codewars Discord server, I recommend using it for effective communication, but I still consider website discourses (as ineffective as they are) as the basic medium of communication between users. Mods are recommended to look at the Codewars Gittter chat too, and I have a Gitter tab constantly open, even if just to check from time to time if you posted some potentially interesting info.

> Mods are typically much slower than PUs at detecting the existence of beta katas, so it's not working.

With this I might actually agree, but I cannot see what difference it makes. So you discover a bad beta, and what then? You singlehandedly decide to delete it? Not that it's impossible, but it would be quite a powerful privilege. Or maybe you flag it, raise an issue, or mark it in any other way? Then this boils down to the same problem of reaction of a responsible person to such mark being potentially slow.


My idea to tackle the actual problem raised by you would be to make publishing of a new kata a restricted function. Users could author kata and submit drafts for acceptance, and then content mods would perform a rough review and eventually publish it for beta process. This way, there would be no need for quick reaction because kata accepted for beta would be preliminarily reviewed.

**Comment by hobovsky** [comment]
> [...] I didn't not start the hyperbola myself; statements such as `such users kinda chose this themselves, havent they` pretty much implies that "yeah we did not force anyone to do that, but it's your choice to be alienated". There are already implied social/peer pressure there.

The quoted sentence was my lame attempt at picking on you a bit. Putting it in this form was wrong, and I am sorry for this.   When a user asks how to communicate, I usually try to present three possibilities: website discourse, Discord, or Gitter, with a remark that Discord might be the most effective. I usually try to not just throw _"Hey, come to Discord!"_ at them.

> (In any case, this is kind of off-topic, I'll put this in another issue.)

Discussing this is indeed a good idea.


>  There are like one of these homework assignment katas every 1-2 weeks, and AFAIK they all get retired by 4 downvotes instead of mod actions. Where are the mods when we need them?

But then how flagging helps here? A user raises a flag, and the flag still needs to wait to be handled. The matter of reaction time still stays, doesn't it?

**Comment by Voileexperiments** [comment]
> But then how flagging helps here? A user raises a flag, and the flag still needs to wait to be handled. The matter of reaction time still stays, doesn't it?

Flagging in any case would function better than the current system, which requires you to "solve the kata to downvote it so it gets retired" (sometimes even resorting to bypassing a kata just to downvote it), which is really just extra hoops to achieve the same end result.

I think kazk has outlined a good basic idea:

> Flagged kata will function like drafts, but can't be republished without approval. Mods will be allowed to retire a flagged kata.

> Some things to consider: Who should be allowed to flag? How many votes should it require?

Probably the current one used for translations, aka 15k honor? Site privileges are already getting very powerful at this point anyway, so adding a flag action wouldn't affect much.

I think 3-4 flags should suffice? If there's a flag system then the auto-retire criteria would become pretty obsolete. Also it should be possible to retract existing flags, in case the kata author is active in fixing the issues.

**Comment by anter69** [comment]
How about:
* raising the honor limit for creating katas (e.g. to 3000, instead of 300)?
* linking this privilage to other things, too (e.g. 50-100-500 solved katas)?

...as suggested multiple times before

**Comment by hobovsky** [comment]
> * raising the honor limit for creating katas (e.g. to 3000, instead of 300)?

Once together with B4B we did some analysis: we got a list of published kata from kazk with some details, and we could not come with _any_ criteria which would correlate quality of a published kata with users honor. Users with 250 honor created a nice kata which got quickly approved, and a user with 4k honor shitposted 4 kata in a row, 3 of which got insta-retired. IIRC, sign-in date was similarily inconclusive.

**Comment by ichdamola** [comment]
How kyu point does a user need to amass before being given the privilege to create kata?

> How about:
> 
> * raising the honor limit for creating katas (e.g. to 3000, instead of 300)?
> * linking this privilage to other things, too (e.g. 50-100-500 solved katas)?
> 
> ...as suggested multiple times before

Thanks, I was just about to ask the number of katas a user must have solved before being given the privilege to create it.

**Comment by anter69** [comment]
> How kyu point does a user need to amass before being given the privilege to create kata?

see the docs: https://docs.codewars.com/gamification/privileges

**Comment by ichdamola** [comment]
> > How kyu point does a user need to amass before being given the privilege to create kata?
> 
> see the docs: https://docs.codewars.com/gamification/privileges

Thank you.

**Comment by Kacarott** [comment]
I believe this issue has since been solved by the implementation of #2600 last year. Now simply raising two issues on new problematic betas is enough to revert them to draft and remove them from the beta pool.
