### ISSUE TITLE
Conflict of role and lack of transparency from usage of CW official Discord server

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/codewars.com#2565]
Since CW official Discord server is set up, everything is being moved to Discord server. This causes massive issues to site operation due to conflict of role and lack of transparency, which is affecting site moderation and other official site matters.

CW official Discord server is meant to replace the previous Gitter chat as a place for users to chat inside. This makes sense. However, the current CW official Discord server does everything; from casual chatting to site content moderation, to even disputes and official support.

None of the latter should belong to Discord. This brings up a lot of problems, not limited to:

* It is unreasonable to expect every coding oriented person to have a Discord account suitable for use among CW ecosystem. Discord has little overlap to coding ecosystem, unlike Github (CW/Gitter allows registering account with a Github account), or even Slack (and even then there could be a conflict between work and private account); meanwhile Discord has lots of other usages (college groups, gaming groups, subcultural groups, patreon content groups, etc..) that has nothing to do with coding. Meanwhile, Discord do not allow simultaneous use of multiple accounts easily, without resorting to using one separate client per account. This creates a software barrier to users that hinges on invasion of one's privacy, if their main Discord account is used for non-coding matters.
* Site-related discourse are now happening on Discord instead of Github or on the main site.  Now when the topic is brought back up on Github/the main site, it is not a topic pending for debate anymore, it becomes a foregone conclusion instead. (You know it is one when it starts with something like "as talked on Discord".) This arbitrarily bars users not participating in Discord from having a say in the topic at the period in which discussions have the most bearing on the decision making process.
* Discord is dark web; all chats inside a Discord server are only accessible by joining the server. This makes all site operations very opaque. If I search `codewars block user` in Google it brings up #1365, because Github, Gitter and CW are on surface web. If I search `codewars "LearningFTW"` I wouldn't even know what happened to LearningFTW because all the communications and official verdicts are in Discord, which is unsearchable.
* It is also impossible to search for and categorize anything being said on Discord, because casual chat and official-worthy discourse are all mixed in the same channels with zero grouping, while threads are not mandatory to start a topic. In Github it is simply not possible to start a discussion without having to first put it in a corresponding issue, so they can be picked up easily compared to Discord.
* Last but not least, using CW Discord for content moderation creates a conflict of functionality with [content issues](https://github.com/codewars/content-issues/issues) repository; now it has become out of date since everything is brought up in Discord instead.

Please take examples from similar sites: [FreeCodeCamp](https://www.freecodecamp.org/news/freecodecamp-discord-chat-room-server/) and [Codecademy](https://discuss.codecademy.com/t/official-codecademy-discord-server/495965) also have their own official Discords, but they strictly limit their Discord to _only_ serve as a casual social lounge for their users, plus a little bit of "contact the mods" support channel. CW Discord is a server with 6k+ users; it is inappropriate and unacceptable to use a _public_ Discord server with such size to openly handle official matters in a willy-nilly matter.

(Just in case some people are wondering: I _am_ in CW Discord, so I get to see various things inside from time to time, including the Good, the Bad and the Ugly. However I do not have any intent to participate. This post may or may not have outlined some of the reasons.)

┆Issue is synchronized with this [Clickup ](https://app.clickup.com/t/2me1b6k) by [Unito](https://www.unito.io)

**Comment by hobovsky** [comment]
+1 to _"as talked on Discord"_ - I don't like this either.

> * Last but not least, using CW Discord for content moderation creates a conflict of functionality with [content issues](https://github.com/codewars/content-issues/issues) repository; now it has become out of date since everything is brought up in Discord instead.

This is partially my fault. I had some ideas to regulate processes related to content moderation, and `content-issues` repository was meant to support them. However, amount of content which I would like to process overwhelmed me, and additionally private activities took over and I did not even make it to setting up the repository completely :( However, I'd still consider the repository as a main place for recording (almost) anything what would significantly affect the content. kazk also likes to have a record of discussions or decisions leading to retirement of a kata, etc. That's why I usually tried to create a Github issue related to deduplications, and used Discord only to notify users and have some quick-paced exchanges.

Currently, the repository is unfortunately set up only in half of what I imagined it to be :(

For some things of a smaller importance, like looking for a volunteer to fix a description, or asking someone to diagnose an issue in a language not many people know, I think ad-hoc questions and discussions are ok, arent they?

**Comment by Voileexperiments** [comment]
> For some things of a smaller importance, like looking for a volunteer to fix a description, or asking someone to diagnose an issue in a language not many people know, I think ad-hoc questions and discussions are ok, arent they?

We've been doing that in Gitter previously anyway, so it's not like it'd be any different. And usually after we fix the katas we just scrub them off one of the big lists on the wiki.

However, we *definitely* didn't put things that should be transparent like discussions leading to moderation decisions solely on Gitter. They belong to Github or the main site.

**Comment by hobovsky** [comment]
> However, we _definitely_ didn't put things that should be transparent like discussions leading to moderation decisions solely on Gitter. They belong to Github or the main site.

Do you mean some specific instance of content moderation here? If so, could you give examples especially bothering you, please?

**Comment by kazk** [comment]
I've been telling users to use GitHub (issues and discussions) for anything that should be kept for the record. I agree with the concerns you brought up. Discord is not ideal for some discussions. That being said, I'd rather have the discussions happening somewhere than not happening at all.

> meanwhile Discord has lots of other usages (college groups, gaming groups, subcultural groups, patreon content groups, etc..) that has nothing to do with coding.

There are also many servers related to coding as well. Many open source projects are using Discord now.

> Meanwhile, Discord do not allow simultaneous use of multiple accounts easily, without resorting to using one separate client per account. This creates a software barrier to users that hinges on invasion of one's privacy, if their main Discord account is used for non-coding matters.

I believe this will be resolved by "Switch Accounts" feature that's in beta right now.

> "as talked on Discord"

I agree this shouldn't happen. The summary of the discussion should be included at least, and it should be open to further discussion on GitHub.

> If I search codewars "LearningFTW" I wouldn't even know what happened to LearningFTW because all the communications and official verdicts are in Discord, which is unsearchable.

That **shouldn't** be searchable. The information is not necessary for Codewars or the community. We have a private issue tracker for problematic users with all the information. That incident happened openly within Discord server because the user was openly attacking the mods **there**. We ban users regularly and none of them should be searchable.

> It is also impossible to search for and categorize anything being said on Discord

Anything on Discord should be considered ephemeral, and I prefer users to open issues on GitHub for anything important and encourage users not on Discord to participate. I think the search is pretty decent, though.

> Please take examples from similar sites: FreeCodeCamp and Codecademy

The main difference from them is that they already had a very active and structured forum, and that continues to be the main platform of communication. We didn't have anything like that. GitHub was used for reporting bugs. Gitter was only used by a few regulars. For a more structured and asynchronous communication, our [GitHub Discussions](https://github.com/codewars/codewars.com/discussions) can be used.
They are also much larger orgs/communities. I'm sure they have more than one admin and larger team of mods to manage the community.

> CW Discord is a server with 6k+ users; it is inappropriate and unacceptable to use a public Discord server with such size to openly handle official matters in a willy-nilly matter.

Can you elaborate? What do you mean by "openly handle official matters in a willy-nilly matter"? An example should help me understand.

> However, we definitely didn't put things that should be transparent like discussions leading to moderation decisions solely on Gitter. They belong to Github or the main site.

I'm not sure what you mean here (please elaborate), but in general, I don't think we should be comparing the current Discord server to the Gitter we had. Gitter was just a random, unmoderated chat for a few regulars. Your concerns about transparency are valid, but "we didn't do in Gitter" shouldn't prevent us from doing in Discord.
