### ISSUE TITLE
How to win every level? 

### ISSUE THREAD

**Issue by manfredj** [Codewars/codewars.com#26]
While trying **Don't rely on luck** kata in Python (first by trying to bind the variable to a function and then by overwriting the function) I discovered a leak that lets you pass every level. Plugging it in appears to trick into into a successful completion and terminate the program:

```
Test.assert_equals(1, 1, "Hello", True)
exit()
```

Was not my intention, but then again the level was sort-of hackish anyway so it was encouraging thought in that direction. Just figured you perhaps wanted to patch this hole up :)

**Comment by jhoffner** [comment]
This should be handled by our async cheat detection worker that fires after each kata is completed. After a certain amount of detected cheats the user starts to become penalized not only the honor/progress earned but also is taxed additional honor. 

Leaving this open for now so that I can double check that the newer languages are being handled correctly.

**Comment by bkaes** [comment]
> After a certain amount of detected cheats the user starts to become penalized not only the honor/progress earned but also is taxed additional honor.

As a side note, could we get some information on those anti-cheating measurements? For example, I often "cheat" during beta, in order to motivate the author to add random tests, or to show issues with the current tests. My solution then passes all given tests (so it doesn't cheat the _CW system_, but the _kata test cases_). Are such solutions also counted as cheats?

Also, do user get notified if they lose honor due to cheating? (I think there was a feature request that asked for transparent honor changes, but I can't seem to find it).

**Comment by jhoffner** [comment]
The anti-cheating simply works by passing in the solution with the existing specs/tests, but mixed in with added tests that should definitely fail. As long as you are not actually circumventing the testing system and just "cheating" the gaps within a kata's own tests, then you will not be flagged as cheating.

Part of the reason why we don't make a big presentation about you being or not being a cheater is to make it harder to try to use any instant feedback to try to find a workaround. I don't know that there can be a workaround, but I've played the cat and mouse game long enough with users to know that I shouldn't assume there isn't a way ;)

**Comment by adam-tokarski** [comment]
So I have a question. I've submitted solution (I rather shouldn't link here, right?) that anti-cheating system mis- recognized as "possible cheating". 
It's not true, but it happens sometime, I know. But it seems that it was negative to my honor level. As far as I know it was my first solution flagged as "cheating", so why is that?

**Comment by bkaes** [comment]
Given that this still works, couldn't you simply check whether the python code contains `sys.exit`, or any other `sys` method?
