### ISSUE TITLE
Codewars ranked me down from 3 kyu to 4 kyu.

### ISSUE THREAD

**Issue by nuriddin-gulamov** [codewars/codewars.com#2602]
I'm very upset now because Codewars ranked down my level & honor. I had more than 1,000 honor and my level was 3 kyu, but after completing 2 kyu kata Codewars ranked me down. So my level got 4 kyu and honor 933. Anyone can help?

**Comment by DonaldKellett** [comment]
Did you plagiarize solutions from the web by any chance?

**Comment by nuriddin-gulamov** [comment]
@DonaldKellett Yes

**Comment by DonaldKellett** [comment]
> @DonaldKellett Yes

There you have your answer. At least you admitted to it.

What most likely happened is that your plagiarized solutions were discovered by a moderator and flagged for cheating, so whatever progress you gained by "completing" them were revoked. Note that we do lock accounts of repeat offenders at `8 kyu / 0%` indefinitely, so please do not plagiarize or otherwise cheat going forward.

**Comment by Blind4Basics** [comment]
> flagged for cheating

"Invalidated",  actually.  Flags for cheats or yet another thing.

**Comment by Blind4Basics** [comment]
You realize that birthing stores each version of each message..? Same for the title.  So I'm not sure what you're trying to achieve by editing everything everywhere?
