### ISSUE TITLE
Could not filter completed kata

### ISSUE THREAD

**Issue by yangyanzhan** [Codewars/codewars.com#265]
I filtered kata by 'kata I have not completed'. But still I can see the completed kata on the page. For example, when I filtered kata by 'kata I have not completed on 8 kyu', I can see the 'Multiply' kata on this list which I have solved long time ago.

Also I can see the past solutions on the 'Multiply' kata page. However, no matter how many times I have clicked the 'submit final' button, I can still find the same kata listed as uncompleted katas.

**Comment by yangyanzhan** [comment]
Now when I Filtered 'Kata I have not completed on Kyu 8', I get 50 katas which I have solved a long time ago. 5 days ago, there are only 3 abnormal katas. The number of abnormal katas is growing.

**Comment by paul-calvelage** [comment]
I filed an issue very similiar to this.  https://github.com/Codewars/codewars.com/issues/282

It's possible the two issues have the same cause; however there is at least one difference, since I cannot see my solutions to multiply and broken greetings--even though they are stored under "past solutions' on the training page:
![multiply missing](https://cloud.githubusercontent.com/assets/5090280/14468019/f814d2c8-00ab-11e6-9e98-77714f0e70e7.PNG)
![multiply](https://cloud.githubusercontent.com/assets/5090280/14468014/f06fcbd6-00ab-11e6-92c5-ad76daa71d9e.PNG)
![broken greetings missing](https://cloud.githubusercontent.com/assets/5090280/14468069/25703aaa-00ac-11e6-9c58-9d87d949461f.PNG)
![broken greetings](https://cloud.githubusercontent.com/assets/5090280/14468070/299f46de-00ac-11e6-9564-b9cff4c0b6cb.PNG)

**Comment by kazk** [comment]
Closing old issue. Please open a new one if this issue is still there.
