### ISSUE TITLE
Cannot login with github even tho my account still exists

### ISSUE THREAD

**Issue by charliearaya** [codewars/codewars.com#2694]
**Describe the bug**
I signed up with my Github account, I've now changed my email adress in Github and I'm now unable to login to codewars. I'm getting redirected to the main page but still not logged in.

**To Reproduce**
Go to login page, press on login with GitHub

**Expected behavior**
Login should happen

**Browser**
Chrome

- OS: Windows
- Browser: Chrome
- Version: 101.0.4951.54

**Comment by kazk** [comment]
Changing your email in GitHub shouldn't change anything on Codewars side because we use the user id to find the associated user.

Is https://www.codewars.com/users/charliearaya your account? No GitHub account is not linked to it at the moment.

To log in with GitHub again, you can sign in to Codewars by using password reset, and link your GitHub from Account Settings.

**Comment by charliearaya** [comment]
The password reset is not working, I'm getting an error that no account is linked with my email. Is it possible you can trigger that for me?
