### ISSUE TITLE
solutions page layout: description and tests aren't readable

### ISSUE THREAD

**Issue by Blind4Basics** [codewars/codewars.com#2696]
The new layout made the destails/description and the tests completely unreadable, from the solutions page:

![image](https://user-images.githubusercontent.com/32236948/169379404-2682be23-5efe-472e-92c5-4413395023e2.png)

oops ;o

(FF, on desktop, while my screen is 2560 pix wide...)

**Comment by JohanWiltink** [comment]
Also, the test window doesn't scroll with the keyboard, _only_ with the scroll bar on the bottom. If there are enough tests that it is impossible to have the top of the tests and the scroll bar in view at the same time, you're fscked; you can't see what's out of sight to the right of the margin. ( Unless you scroll down, then right, then back up. Nope. )

**Comment by kazk** [comment]
Move them above the solutions similar to the discussions page.

Can you guys explain how/when you've been using this **on the solutions page** so we can understand the use case better?

**Comment by JohanWiltink** [comment]
One use is after solving a Beta kata: looking at the tests to see if there are random tests, what the reference solution looks like, what the organisation of tests is, &c &c.

**Comment by kazk** [comment]
Ok, thanks.

> One use is after solving a Beta kata:

Yeah, that's what I used to use it for. Having it on `Solutions` page is just convenient since you land there after completing. Having it on `Discours` page is also useful to reference while writing comments. This is why I didn't really want to do a dialog that takes over the page.

> I could do that from Discourse instead of Solutions, but sometimes Discourse is long, and slooow.

Yeah, good point. It's still slow for older kata with many comments. You can also view from solution group page, but that requires clicking "Link" on the solutions page.

I think the fix is good enough for now.
