### ISSUE TITLE
[Ability to view shell mode / used bash scripts]

### ISSUE THREAD

**Issue by imhunterand** [codewars/codewars.com#2758]
![image](https://user-images.githubusercontent.com/109766416/181769254-944e9169-ec22-45ae-95bc-0112a56fc3bd.png)

![image](https://user-images.githubusercontent.com/109766416/181769337-bc0212cf-1588-46f5-9660-21e07566caae.png)

**Describe the bug**
I see the attacker can uploaded any malicious code from https://www.codewars.com/join?language=shell
for example code :
```bash
#!/bin/bash -e
a=$1
b=$2
cat /etc/passwd
echo $((a*0))
```
and the result is a your passwd servers.

used a ``wget`` for uploaded backdoor or malicious code - used a ``ls -la`` and ``pwd`` for see path your file

**Comment by DonaldKellett** [comment]
@imhunterand Please don't disclose security vulnerabilities publicly in the issue tracker, suspected or otherwise. They should be reported privately to Codewars (can @kazk advise how exactly to do so? I can't seem to find it in the docs)

On the other hand, code submissions are executed as an unprivileged user within a container, so (1) you shouldn't be able to dump the contents of sensitive files like `/etc/shadow`, and (2) even if you could, it's only as seen from within the container and probably has nothing to do with the container host.

**Comment by imhunterand** [comment]
In others company likely as your project/websites this has been accepted ? and now do you accepted this issue vulnerable ?

**Comment by kazk** [comment]
There's an option for reporting security vulnerability:

![image](https://user-images.githubusercontent.com/639336/181810415-adcfc784-1f61-45d8-9c08-064287798bbb.png)

which links to https://github.com/codewars/codewars.com/security/policy that explains how to contact us.

---

> `/etc/passwd`

Yes, you can read any world readable file in the container.

> used a `ls -la` and `pwd` for see path your file

You can do that too.

> used a `wget` for uploaded backdoor or malicious code

Please let us know the details by following https://github.com/codewars/codewars.com/security/policy

**Comment by imhunterand** [comment]
**Hi!** @kazk 

Thank you for your respond. I sent the report to [security@codewars.com](mailto:security@codewars.com).

Regards,
@imhunterand
