### ISSUE TITLE
Solutions are rendered by front-end with tabs replaced with whitespaces

### ISSUE THREAD

**Issue by Voileexperiments** [codewars/codewars.com#2867]
I just discovered that whenever a solution is rendered by CW front end, all instances of tabs are replaced with white spaces that occupies exactly the amount of space a tab would occupy for that language's display. Using the entry kata and this simple solution as POC:

```python
def multiply(a, b): return a * b if len('	') == 1 else None
```

In trainer and code editor (from forking the solution):

![image](https://user-images.githubusercontent.com/14909989/203488025-0834e1db-f4f9-439a-a3bf-066c1bf9a83b.png)

In solutions page, "past solutions" display and probably every other similar view:

![image](https://user-images.githubusercontent.com/14909989/203488122-fb5afbd3-81b2-438a-bc8e-400f7e0eeb24.png)

As can be seen, tabs have converted to whitespaces and hence makes the code behave completely differently depending on where you copy the code.

This is not a back-end issue as the user code in the response does contain `'\\t'` instead of whitespaces. It was modified during the front-end rendering somewhere.

**Comment by kazk** [comment]
Using custom `CodeMirror.runMode` works for solutions list, which calls it directly. But tabs inside Markdown code block is lost because of https://github.com/markedjs/marked/issues/644 (closed as wontfix). The tabs are already converted to 4 spaces by the time `runMode` is called.

I'll close this issue when I deploy the fix for solutions.

**Comment by kazk** [comment]
Those should get fixed.

**Comment by kazk** [comment]
Deployed
