### ISSUE TITLE
Inconsistent rank points on Julia leaderboard

### ISSUE THREAD

**Issue by devinallen** [Codewars/codewars.com#3069]
**Describe the bug**
It seems like there are 49 unobtainable points on the Julia Ranks leaderboard, as I completed all kata and haven't tied the top user

**To Reproduce**
See the Ranks section of the leaderboards, set to Julia:
![image](https://github.com/codewars/codewars.com/assets/36391203/b7cddbc0-3821-48a9-bc91-b913f48cea52)

Then, find the number of total rank points attainable from completing all Julia kata (using the codewars docs):
![image](https://github.com/codewars/codewars.com/assets/36391203/b2932966-b3b5-42b6-a7c3-e33ad6fc2185)

**Expected behavior**
Since the only way to gain rank is to complete kata, completing all kata should give you the maximum amount of rank. 

**Additional context**
I've been grinding Julia kata for a while and I'm kinda bummed that I don't get to catch up to depial :(

**Comment by hobovsky** [comment]
The user **depial** has solved three kata which got later retired and cannot be completed now. I cannot remember what the original ranks of the retired kata were, but it would make up for at least some of the missing points. Unfortunately, since the kata cannot be completed anymore, you will not be able to get points for them.

What you can do to get to top 1 is to create some Julia translations and get them approved. For every approved translation you should get as much language rank as for solving the translated kata. But still, if depial decides to solve your translations, you will lose the TOP 1 position.

If you would like to create some Julia translations, I'd be happy to help with review and approval, if they are of sufficient quality. You can reach out to me at Codewars Discord, you can ask questions at `#help-translate` channel there, and I could share a small list of kata which should be easy to translate.

**Comment by VanessaGreene** [comment]
Hi @devinallen I hope Hob's answer helped. I'll close this issue now.

**Comment by devinallen** [comment]
That works, thank you!
