### ISSUE TITLE
Can't view solutions after completing kata

### ISSUE THREAD

**Issue by paul-calvelage** [Codewars/codewars.com#311]
I can't view solutions to the kata [Time to Watch a Parade!](http://www.codewars.com/kata/time-to-watch-a-parade) after completing it.  It says, "Solutions have been withheld".  But if I train on the kata again, I can see past solutions.  Also my honor points went up by 3 after completing it.  (It is in beta.)  So something is definitely wrong here.
![past solutions](https://cloud.githubusercontent.com/assets/5090280/15399059/2666245e-1db4-11e6-9c42-80acb750e878.png)
![solutions withheld](https://cloud.githubusercontent.com/assets/5090280/15399063/290ef78a-1db4-11e6-9fde-6dc4fb24e34b.png)

**Comment by jhoffner** [comment]
This is related to #300

**Comment by chrisdel101** [comment]
This is still open since 2016? I am experiencing this currently. Unsure how to troubleshoot.

**Comment by kazk** [comment]
Yes, it's still open unfortunately. I actually posted a detailed explanation earlier today on what's going on and why it's difficult to fix. If you're interested, you can read it [here](https://github.com/Codewars/codewars.com/issues/1683#issuecomment-473416159).

I've been fixing bugs from over the years after inheriting the project in late 2018. It takes time because there's so many bugs that accumulated while not being worked on and this one is definitely one of the most difficult ones remaining.

**Comment by chrisdel101** [comment]
If I already passed, and I click on forfeit to see the solutions, will it deduct the points that I just earned? It decided not to risk it. 

Thanks for the update.

**Comment by kazk** [comment]
@chrisdel101 I wouldn't recommend because that might prevent you from earning the honor if we recalculate the honor or some reason or when this issue gets fixed in the future.

What's your Codewars username? I'd like to confirm if what you're experiencing is the same issue.

> PS- if there is a contributions section maybe I can help work on bugs?

Thanks, but it's not open source.

**Comment by chrisdel101** [comment]
@kazk Ahh too bad. I'm looking for a project. 

Username: arssonist

**Comment by kazk** [comment]
Thanks, is it for "Mumbling"? Looks like the same issue.

**Comment by chrisdel101** [comment]
Yeah, that's the one.

**Comment by kazk** [comment]
If this happens again, please let me know by commenting on #1683.
