### ISSUE TITLE
Lots of timing out when translating a kata

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#342]
Submission timed out while communicating with our servers. This may infrequently happen if our servers are extremly busy. Please try again. If issues persist you can check status.codewars.com to see if server issues are being investigated.
Or: No tests were provided
Or: ... lots of (false) errors
Site status: everything is operational.

**Comment by GiacomoSorbi** [comment]
Mine is partially related (I got that a lot too), but I also got the fact that "lt" is not a valid operator, which seems quite strange in Ruby (or, well, any other language a bit more sophisticated than brainfuck)...

**Comment by jhoffner** [comment]
I'm looking into the timeout issues now. There is definitely an issue with the server reporting a timeout when it doesn't need to. However another issue seems to be that many kata tend to do things like 
```ruby
10000.times do 
  Test.assert_equals(true, some_method)
end
```

Which kills performance because you end up writing 10k "Test Passed" lines of output, which kills execution performance, plus it has to be transmitted (twice) and parsed and then rendered. 10k Test Passed messages aren't very useful, so instead better practice would be to do things like:

```ruby
results = 10000.times.map
  !!some_method
end

failed = results.select {|v| !v}
Test.expect(failed == 0, "#{failed} random tests failed");
```

**Comment by GiacomoSorbi** [comment]
IIRC I took the same structure of the Python tests, but, yeah, you are right and that makes absolutely sense - I should just stop using auto-pilot when translating katas at night.

Thanks, Jake!

**Comment by jhoffner** [comment]
Please verify that this is no longer an issue. it should have been fixed since last week.

**Comment by g964** [comment]
I think it is fixed now.
