### ISSUE TITLE
Always has to log in again and again

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#382]
Even to open a CW link in a new tab you have to log in each time, same thing when you refresh the page... It's painful...

**Comment by javatlacati** [comment]
+1 I think it was from server migration. Some time the site seemed to be down I only got cloudflare page.

**Comment by jhoffner** [comment]
Yeah this is annoying. It just started happening to me. I deployed some changes which brought all of the server errors down to zero, but there are still a number of front-end related issues, like apparently this one, that I am investigating now.

**Comment by jhoffner** [comment]
@g964 Is it when publishing a kata that this usually happens for you? Thats how I am able to pretty easily reproduce, so far no where else though.

**Comment by g964** [comment]
It did happen when trying to publish but not only, also when changing page or refreshing.

BTW thanks for the change to the 500+ katas that now can be republished by language!!!

**Comment by r080te4** [comment]
When I leave work, the browser has several tabs with opened kata (all tabs from logged in session).
When I come in the morning and try to refresh a single tab, I have message:
"The kata failed to load. Please try reloading the page."
When I refresh the page, I see the sign in modal and do the login.
(Maybe kick is because of connection loss)

It will kick me of again if I'll try to refresh any of several tabs (opened yesterday) after my re-login.
It wil not kick if I copy url and paste it to the new tab. This problem was detected more, then 6 days ago.
But yesterday and today I detected it also affected new opened tabs (from time to time) - the same link was kicked and then was not kicked with the same action.

**Comment by jhoffner** [comment]
Please verify that this is no longer an issue

**Comment by g964** [comment]
I think it is fixed now.
