### ISSUE TITLE
Translations example test cases don't get checked

### ISSUE THREAD

**Issue by bkaestner** [codewars/codewars.com#39]
When I publish a kata, my solution needs to pass both the hidden and the example tests (if they've been provided). However, if I publish a translation, only the hidden test cases get checked, not the example ones, so it's possible to publish a translation with completely wrong example test cases.

┆Issue is synchronized with this [Clickup ](https://app.clickup.com/t/2me1ef9) by [Unito](https://www.unito.io)

**Comment by GiacomoSorbi** [comment]
I noticed that one too, as I once forgot to rename a example test function in another language following the proper case for it. I suppose it can get a bit troublesome to check, though, unless you force each creator/translator to put at least one good example test case in his/her work.

Which could be taking two birds with a stone, if you ask me, but let's see what the staff thinks about it.

**Comment by bkaes** [comment]
> I suppose it can get a bit troublesome to check, though, unless you force each creator/translator to put at least one good example test case in his/her work.

Well, that's not necessary. After all, a kata can be published without any example test cases at all. So that shouldn't be a problem. But _if_ those example test cases have been provided, the translation should follow the same rules as the normal kata publishing. 

That being said, I like the translation editor a whole lot more, since it enables me to run all four combinations ([solution, initial sulution] x [hidden test cases, example test cases]).

**Comment by GiacomoSorbi** [comment]
Oh, the creation editor does not allow for that? Never tried, mh...

And I know that an empty field could solve things, but what if the author still wants to write something in the example test cases, but there is no positive testing outcome from it? Rather rare, I think, but still...

**Comment by VanessaGreene** [comment]
@bkaestner @GiacomoSorbi Is this issue still present? If so I'd be happy to reopen this issue.
