### ISSUE TITLE
Cannot reply on my kata

### ISSUE THREAD

**Issue by aryan-firouzian** [Codewars/codewars.com#410]
I have a kata named "subtract the sum". Some people made issues. I want to resolve the issue and reply them but my comment never get published. I tried different browsers and devices. It should be a server side problem. The page wants to be loaded again but my comment never show up there.
[Here is a link to the my kata](https://www.codewars.com/kata/subtract-the-sum/discuss#5764d8e005404b205d00007b)

**Comment by aryan-firouzian** [comment]
Actually I cannot reply to ThomasJazz there. He made two issues there.

**Comment by DonaldKellett** [comment]
I think I've encountered a similar problem here: https://github.com/Codewars/codewars.com/issues/409

**Comment by Nivrad00** [comment]
I've encountered a similar problem on https://www.codewars.com/kata/list-to-array/discuss/javascript

I tried to reply further to the conversation gabrielkunkel and I were having, but the site didn't refresh automatically, and when refreshed manually my reply hadn't shown up. I tried submitting a reply several times more and got the same effect. I was on mobile, but eventually I moved to my computer and the problem persisted.

After refreshing for a while, all four responses showed up, though not at the same time. Next I tried deleting them, but again they won't go away. (The strange formatting on my responses are due to mistakes on my part, by the way, not the bug)

Strangest of all, when I continue refreshing, the site alternates between showing three of the new responses and showing none of my new responses. Once it showed me all four, but currently it seems to be alternating between three and zero again. 

I've tried using mobile, different browsers, and clearing browsing data.

**Comment by jhoffner** [comment]
Thanks @Nivrad00 for the report. That will be very helpful in tracking down the issue. I have been working on some issues related to this. I think a recent forced database upgrade caused both this and a few other issues to start happening. I'm working on a fix.

@DonaldKellett I do believe this issues are related. In some rare cases a few comments may have been lost because of it (or at least not saved when they seemed to be)

**Comment by jhoffner** [comment]
Comment issues should be resolved now. There is a very low level ORM issue that was causing issues when updating data that I pushed a workaround for. Some content may be lost if it was created over the last week. The majority of comments should work, just a small percentage of edited comments caused the data issues after the fact.

Leaving open for the time being in-case issues remain.

**Comment by jhoffner** [comment]
I take that back, removing comments still causes issues - I will wait to close this bug until the official (non-workaround) fix is found.

**Comment by jhoffner** [comment]
Official fix has been deployed
