### ISSUE TITLE
Webhooks not working

### ISSUE THREAD

**Issue by BradZzz** [Codewars/codewars.com#419]
The webhook (attached to the user profile) isn't currently working. My endpoint is working just fine when curled, but nothing comes in to that same endpoint when a user's profile is update / kata completed.

**Comment by jhoffner** [comment]
Hi @BradZzz. Due to a number of configured endpoints constantly failing and causing performance penalties, I recently implemented a feature that counted the number of request failures and after a certain threshold would disable the webhook. That may be what is happening if your hook was working before. If so, you can try re-adding the hook and seeing if that re-enables it for you. Either way, let me know the specifics of your situation so that I can debug further. It was a quickly implemented feature to try to quit down the number of exceptions being logged so I'm sure it can use some more attention.

**Comment by jhoffner** [comment]
I was able to reproduce this issue. A fix is implemented and is going out in the next push.

**Comment by BradZzz** [comment]
It's working now! Thanks for the help!

**Comment by brianbud** [comment]
Hi

I cannot find the webhook link, am I missing something? 
Help is much appreciated. 

![image](https://user-images.githubusercontent.com/79291561/214459636-e17f7fee-70b6-41ae-a54e-96ae55228978.png)

**Comment by Madjosz** [comment]
You can fill in a link to _your_ endpoint and then that url gets notified on certain events. You have to host this yourself (or use some online service for receiving webhooks).
