### ISSUE TITLE
Elixir error

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#428]
Kata: <https://www.codewars.com/kata/is-my-friend-cheating/elixir>.
@hencethus published a post on CW this morning about this kata:
................................
```
=INFO REPORT==== 1-Jul-2016::02:07:26 ===
application: logger
exited: {{shutdown,{failed_to_start_child,'Elixir.GenEvent',undef}},
{'Elixir.Logger.App',start,[normal,[]]}}
type: temporary
RemovenbTest
remov_nb
Test Passed
random
Finished!
Test Passed
fixture:44: warning: random:uniform/1: the 'random' module is deprecated; use the 'rand' module instead
fixture:70: warning: random:seed/1: the 'random' module is deprecated; use the 'rand' module instead
2 Passed
0 Failed
0 Errors
Process took 1191ms to complete
```
Tests pass, but still fails.
................................
I replaced "random" by "rand" but now when trying the kata I get:
```
=INFO REPORT==== 1-Jul-2016::06:52:32 ===
application: logger
exited: {{shutdown,{failed_to_start_child,'Elixir.GenEvent',undef}},
{'Elixir.Logger.App',start,[normal,[]]}}
type: temporary
```
Did you make changes at Elixir or at OTP? On CW Elixir is '1.2.4'. Elixir is now 1.2.5 and even 1.3.1. Are you using OTP 18 or 19?

**Comment by g964** [comment]
It seems that all Elixir katas are concerned by:
```
=INFO REPORT==== 1-Jul-2016::06:52:32 ===
application: logger
exited: {{shutdown,{failed_to_start_child,'Elixir.GenEvent',undef}},
{'Elixir.Logger.App',start,[normal,[]]}}
type: temporary
```

**Comment by jhoffner** [comment]
Yeah it looks like OTP 19 got set since a specific version was not specified in the Docker file. I'm working on a new image and will have it deployed soon.

**Comment by g964** [comment]
Might it be better to keep OTP 19 and to avoid - if possible - the warnings since they prevent the users to pass their katas despite a working code.

**Comment by jhoffner** [comment]
I would love to keep OTP 19 (especially since I'm having problems getting a properly installed OTP 18 installed and working correctly). However I'm not experienced with either Elixir or Erlang and have so far failed at figuring out how to suppress the warnings. Any ideas?

**Comment by jhoffner** [comment]
I'm reverting to an older image that does not have these changes. It doesn't look like there is a relevant code change since then that should affect Elixir. Obviously until the image on the CLI project can get fixed, any additional updates to the runner will not propagate to elixir since the image is now frozen (along with the Haskell image for the same reasons)

**Comment by g964** [comment]
Yes might be good to revert to an older image but now that I have made (minor) changes for some Elixir katas (`rand` module instead of `random`module which is now deprecated with (I think?) OTP 19 , hence suppression of `random:seed` which was not anymore needed) what about these changes? I would like to help you but I am not an expert in the depth of Elixir or Erlang and I don't know how to suppress the warnings:-(

**Comment by jhoffner** [comment]
I just deployed so you can go ahead and check your kata if they need to be reverted. Ideally the current OTP 18 & Elixir 1.2.4 image will get updated to work with those versions, so that we can continue to support older kata, and then newer versions are supported either on the same image or a separate one - so that both versions can be supported within CW at the same time.

Hopefully some additional OS contributions will be made by someone to the CLI project to help get us there, in the meantime this should hold us over.

**Comment by g964** [comment]
Thanks a lot for your wonderfull work!
