### ISSUE TITLE
Can't unpublish kata translation

### ISSUE THREAD

**Issue by GiacomoSorbi** [Codewars/codewars.com#44]
The kata author for [this one](http://www.codewars.com/kumite/552fe082184399e0bc00002b?sel=552fe082184399e0bc00002b) and me had some issue while trying to approve the translation (you can read it in more detail in the relevant discussion).

I have tried to unpublish it, but the button doesn't seem to do a thing.

I also tried creating a new translation, but it refuses to make me create another Python version: that is surely wanted, but isn't it a bit dangerous? Suppose user X goes around publishing poor and/or not working of everything with language Y, de facto preventing other users to translate a kata in Y again, and you get a nasty picture.

Wouldn't it be better to have a warning if you try to translate a given kata in a language that has already a pending (of course, not an approved) translation?

Finally, I would like a way to permanently delete my translation drafts (I created one of the same kata in Coffeescript while trying stuff around this issue and it has no meaning to me, of course).

Thanks again for your kind attention :)

**Comment by jhoffner** [comment]
I just ran into an issue with publish not doing anything, it was an expired token issue which I was able to workaround by clearing my cookies and re-logging in. Its not clear to me that this is the same issue as yours. 

We don't allow multiple root level translations for the same language, because then there would be all kinds of conflicts. Additional translations can be added by forking an existing translation of the same language. 

if you are unable to create a new python translation because the old one is not shown (possibly rejected) then that would definitely be an issue.

**Comment by GiacomoSorbi** [comment]
Hi Jake and thanks,

we ultimately succeeded indeed by forking the kata. I get your point on not allowing more translation, though forking an existing translation I think I may feel a bit like a thief, but I think I'll deal with it if such a situation ever arises.

All clear for now on this front \m/
