### ISSUE TITLE
submission timed out

### ISSUE THREAD

**Issue by kimesth** [Codewars/codewars.com#447]
Trying to open codewars account, but after fixing and submitting code, submission timed out even though http://status.codewars.com/ says all systems operational.

"Submission timed out while communicating with our servers. This may infrequently happen if our servers are extremly busy. Please try again. If issues persist you can check status.codewars.com to see if server issues are being investigated."

**Comment by keithwins** [comment]
I have been on codewars for a few days (and LOVE it), but I have had the same "submission timeout" or, if I minimize my code to nothing (i.e. return 1), I might be "no test cases submitted". In both cases it takes 5-10 SECONDS to load every  screen, every time, which makes it extraordinarily painful since it doesn't remember any presets so I have to reselect my search parameters every time to select the next kata. Pretty much unworkable...
