### ISSUE TITLE
multibyte string functions unavailable in PHP

### ISSUE THREAD

**Issue by deadowl** [Codewars/codewars.com#458]
I got a kumite translation to one of my kata that includes UTF-8 encoded strings. It doesn't have the same test cases. I challenged the kumite using mbstring functions. Unfortunately I get the error, "Call to undefined function mb_internal_encoding()"

I'm guessing that multibyte string functions aren't in the PHP core for some reason. Would it be possible to install that package? Every other solution is particularly hacky.

**Comment by jhoffner** [comment]
Your best bet is to contribute the update within the [Runner](https://github.com/Codewars/codewars-runner-cli) project. Right now there is an `alt-runner` docker image that has PHP in it but its probably best to break it out into its own runner, so that composer & additional packages can be installed more easily. 

I'm closer here since this is runner related.
