### ISSUE TITLE
Can we replace back to the older output interface ?

### ISSUE THREAD

**Issue by myjinxin2015** [Codewars/codewars.com#474]
Two reasons:
first reason is the new interface often failed:
when I submit a solution, if not through (red border), then I can not be submitted again unless I refresh the page. I am now in a Kata refresh the page 50 times, every time to paste the code (because the refresh page does not save my code, I need to copy it in advance)

second reason is I can not use chrome with this interface, you know ;-)

My advice is to restore the old input interface, You can add your new features on the basis of it, It should not be difficult to do so

**Comment by jhoffner** [comment]
We did more than just replace the interface. The way that we run code has changed, which is why it is now far faster than before. The iframe handles both the request and the response, removing a bunch of middleware that slowed down the process. So this isn't going to go back to the way it was before. Instead we just need to work to resolve any outstanding issues with the new design.

The SSL issues I'm aware of. Its odd though that you are not able to submit the tests again. What is the behavior exactly? Do the run/submit buttons stay disabled? If you reload the iframe (without reloading the entire page) does that fix it? Is there any sort of error message or anything that shows up in your Chrome console?

**Comment by SteffenVogel79** [comment]
I use chrome with the new interface without any problems...
