### ISSUE TITLE
Unable to edit approved katas

### ISSUE THREAD

**Issue by the-zebulan** [Codewars/codewars.com#496]
Anytime I click `Edit Kata` on an approved kata, I get the same 500 error.

![500error](https://cloud.githubusercontent.com/assets/7484300/17376493/0deb94f4-5973-11e6-9caa-6330bc913a5a.png)

I understand that we shouldn't be breaking hundreds (or thousands) of solutions with changes to test cases and such if there aren't major issues with them. Sometimes it's just small things in the descriptions like spelling/grammar issues or bad examples.

**Comment by the-zebulan** [comment]
* https://www.codewars.com/kata/calculator/python

In this kata, the `actual` and `expected` values of the `assert_equals` are reversed, causing the error message to be confusing to users. 6 out of 7 open issues are for this same minor problem.

This would be such a simple fix but I cannot edit this kata to make this change. The last comment from the katas author was 2 years ago.

**Comment by anter69** [comment]
I have the same issue: wanted to add a test case to an approved kata ([this one](https://www.codewars.com/kata/esolang-ticker)) but I get the 500 error.

I randomly tried to edit a bunch of approved katas (from my completed katas list), and it happens with all of them.

**Comment by lechevalier** [comment]
Linked with this issue https://github.com/Codewars/codewars.com/issues/796

**Comment by omegahm** [comment]
@kazk Just wanted to show a case, where this is a problem: https://www.codewars.com/kata/numbers-to-objects/discuss/ruby.

Nightim's suggestion here is 5 months old at the time of writing. It's a simple fix, to just replace `numObj` with `num_obj`, however I can't edit this myself.

@jhoffner Would it make sense to have an approvement system for kata edits? So that I can edit, and people can approve, and then when it's approvement rating is high enough, it'll get merged?

**Comment by kazk** [comment]
@omegahm I've seen many like this.
I don't know much about translations, but what happens if you fork the [translation](https://www.codewars.com/kumite/57e01eeaf5ec1668f200011d?sel=57e01eeaf5ec1668f200011d)? If that doesn't work, maybe leaving a comment in there will notify the translator.
One of the problems is that translators don't get notifications from kata discourse page.

There have been many discussions related to this topic and some proposals were made. We should probably organize/consolidate them before continuing further discussions.

**Comment by 10XL** [comment]
@kazk that is a possible solution unless the language was added directly from the kata editor, where no 'kumite' is created and doesn't appear under `/translations`. [I forked the ruby translation of that kata and change the function name.](https://www.codewars.com/kata/57ced2c1c6fdc22123000316/discuss#58cc8414c3071fe1210000c8). From previous experience, I noticed that you might have to 'reset' the kata to get the new example test cases.

**Comment by kazk** [comment]
Thanks @10XL. So your fork will override the old one once the author approves it?
This might be a *good enough* solution for the case where the translator is inactive and the author is active.

---

@jhoffner 
How about moving everything into Kumite style (even the original language) and creating a new privilege to administrate them? If I remember correctly, Kumite can be turned into Kata and I'm assuming there're already some connection. Is making Kata into a group of Kumite possible? i.e., exporting the languages directly entered in Kata editor to Kumite and treating them similar to translations.

```
Current                                   Kata as group of Kumite
             +---- Kumite ---+            +- Kata (Kumites) -+
+- Kata --+  | [Python]      |            | +[JavaScript]    |
| [JS]    |--| [Haskell]     |            | +[Ruby]          |
| [Ruby]  |--| [C]           |            | +[Python]        |
+---------+  | [Go]          |            | +[Haskell]       |
Approved by  +---------------+            | +[C]             |
moderators    Approved by the author      | +[Go]            |
                                          +------------------+
                                          Approved by moderators
```

Some benefits that I can think of at the moment:

- Improves collaboration
  - Easier to see who made what changes
  - Easily propose changes
    - Possibly allow lower privilege to approve depending on the area edited. e.g., typo
  - Has dedicated discourse for review and discussion per language
    - Need to add spoiler flags (#821)
- Improves management
  - Doesn't rely on single user
  - Approval is more uniform (allow translation approval #855)
  - Easy revert by re-approving the parent
- Less work?
  - Can be built on top of existing translation approval process?

Some things to consider:
- May increase noise and this might get annoying for authors/moderators
- Kumite fork tree depths
- Allow PR style contribution (changes gets merged to the parent)
- Cleanup stale Kumite

**Comment by 10XL** [comment]
@kazk According to this [fork](https://www.codewars.com/kumite/575e152f306ac0572900015a?sel=578af6f37c77f5e9cd000020), yes.

**Comment by jhoffner** [comment]
Approving a translation fork to a root translation that was already approved didn't actually update the changes. There was actually a bug that caused 2 languages in some cases to show up. I've fixed this in preview and will soon push to production so that you can continue to improve a kata via additional kumite forks. 

@kazk As for exporting all languages added directly via the kata editor as translations, so that they can be improved. Its an interesting idea. I had wanted to phase out the kata editor anyway since its not a great UX. Adding languages should ideally be done directly via kumite/translations and then approved, even if you are the other. Its the recommended approach. Having the single kata editor interface is still nice for managing small tweaks. 

I'm in the process of creating a new kata/challenge UI from scratch, which will be shared between both Qualified and Codewars. I'm not likely to get too deep into changing anything else until I start to connect that UI to Codewars. I need to assess how easy I can hook it up and then determine if a kumite only approach makes the most sense.

**Comment by kazk** [comment]
Closing old issue. I believe this doesn't happen anymore.
