### ISSUE TITLE
C# compilation issue while trying to make a translation

### ISSUE THREAD

**Issue by jhoffner** [Codewars/codewars.com#5]
Error: Command failed: /tmp/csharp115224-22-lt0wpn/setup.cs(3,21): error CS0101: The namespace global::' already contains a definition forKata'
/tmp/csharp115224-22-lt0wpn/code.cs(3,21): (Location of the symbol related to previous error)

Trying to make a C# translation of an existing Kata in Kumite, continue to get this error. I can name my class anything in the world, will get the same error (definition for )

http://imgur.com/kUEU88e
Change class name:
http://imgur.com/ykcQ34m

(originally filed on CW by parabola949)

**Comment by parabola949** [comment]
Guess I could tell you the kumite ID
5511c2185090637b43000580

**Comment by highlanderkev** [comment]
Also seeing this issue/error (below) when trying to translate a Kata to C#. 

Error: Command failed: /tmp/csharp115315-20-w8j4uq/setup.cs(4,14): error CS0101: The namespace `global::' already contains a definition for `MorseCodeDecoderFinal'
/tmp/csharp115315-20-w8j4uq/code.cs(4,14): (Location of the symbol related to previous error)

It seems be happening due to compilation on the solution code. No matter what names I give the class in the Solution Setup or Solution it stills throws an error on the class name in the Solution section. I also tried separating the classes into different namespaces and this doesn't fix the issue.

My best guess is that the Solution code is getting compiled twice, first in the code.cs file then in the again in the setup.cs, which is why it is throwing the error.

**Comment by parabola949** [comment]
@jhoffner It appears to be working now for me, not sure what you did, but good work :)
