### ISSUE TITLE
Timeouts when running any tests.

### ISSUE THREAD

**Issue by SteffenVogel79** [Codewars/codewars.com#519]
At the moment I get only timeouts when running any tests.

**Comment by smoleniuch** [comment]
I have the same problem on firefox and microsoft edge.

**Comment by apelsin83** [comment]
I have the same problem on Chrome.

**Comment by myjinxin2015** [comment]
I have the same problem on any browser ;-)

**Comment by dsasov** [comment]
The same for me +1

**Comment by Voya100** [comment]
I have the same problem - I haven't managed to do any successful tests or submits today (on Firefox, language: Javascript). I always get: 
"Server Execution Error:
Request Timeout: The server timed out waiting for the request to be processed. This may be due to high server load. Please try your request again."

I have had this very often during the past 2-3 days, but they have eventually succeeded after a few tries. I'm a new user, so I'm not sure how common these usually are, but they are starting to get quite annoying.

**Comment by SteffenVogel79** [comment]
At the moment there are problems. But generally CodeWars works fine.
But consider: It is a beta plattform and is improving from time to time.

**Comment by avimar** [comment]
I have only been able to run 2/6 tests or so, with the choice of node 6.0.0 if that makes a difference.

**Comment by seanwbarry** [comment]
same problem. all tests/solution submissions timing out for the past 30 minutes.

**Comment by Maxim-Bernasevsky** [comment]
Join the above. I hope this will be fixed in very soon.

**Comment by SteffenVogel79** [comment]
Jake will fix it soon. He is working very hard for CodeWars.
I use this time for thinking about ne katas. :-)

**Comment by gregwoods247** [comment]
Also same problem on Chrome (Linux).

**Comment by S7eve** [comment]
oh well, guess I'm not the only one here :)

**Comment by SteffenVogel79** [comment]
For approximately 3 hours all tests work without problems.
