### ISSUE TITLE
Crystal request

### ISSUE THREAD

**Issue by g964** [Codewars/codewars.com#575]
Crystal needs a "BigInt" library.

**Comment by jhoffner** [comment]
This should be added to the [cli](github.com/Codewars/codewars-runner-cli) repo. @g964, since you are a power user, I would also recommend getting familiar with that library. You could add libraries as you need them and then the only thing you would have to wait for is for me to test and push out the changes.

**Comment by g964** [comment]
Thanks but <https://github.com/Codewars/codewars.com/issues/github.com/Codewars/codewars-runner-cli> is not valid:-(

**Comment by jhoffner** [comment]
https://github.com/Codewars/codewars-runner-cli/issues
