### ISSUE TITLE
Kata description does not load when not logged into Codewars

### ISSUE THREAD

**Issue by jbampton** [Codewars/codewars.com#576]
When you are not logged into Codewars the kata description for each kata does not load.

Just says -> Loading description.

None of my non-Codewars friends can see what I am solving.

**Comment by jjstreet** [comment]
The issue is more nuanced than that.

If someone has never been to Codewars before, following a link to a particular kata will not work and descriptions of the kata and comments are not visible due to a clientId not being null or a number.

However, if you first visit the katas list page, I think the clientId is then set, and you can visit any kata deep link with no issues.
