### ISSUE TITLE
Feature: Users with high kyu can approve translations

### ISSUE THREAD

**Issue by suic86** [Codewars/codewars.com#591]
Hi,

**Status quo:** Only the author of a kata or an administrator can approve a translation.

**Suggestion**: Users with high rank in a language (e. g. 4th kyu and higher) could approve translations in that language. For example a user with 3rd kyu in Python would be able to approve Python translations.

**Rationale:**

Users having high kyu in a language are usually proficient users of that particular language (e. g. Python). It can be presumed that these users are qualified to review and approve a translation in that language (e. g. Python).

On the other hand, the author of a kata can be proficient in the original language (e. g. JavasScript) but a beginner or nescient of the language of translation (e. g. Haskell). In this case, the author has two options. Either not to approve or to approve without reviewing the translation. None of these options are optimal.

**Examples:**
1. I usually approve Ruby translations of katas authored by me even if my Ruby knowledge is limited, as I trust the authors of the translations.
2. It happened to me that the author didn't want to approve my Python translation as he didn't know Python. I think that this was a valid point.

Thanks,

suic

**Comment by nomennescio** [comment]
As an extra incentive for this feature: MANY katas are abandoned by their authors, and therefore translations cannot get approved, as most admins are too busy. Therefore, being able to support qualified users (maybe even 2 Kyu, 1 Kyu ones? Although for some languages it is yet impossible to reach that target due to a lack of enough Katas) to approve translations, will greatly enhance the Kata translations.

**Comment by kazk** [comment]
https://github.com/Codewars/codewars.com/issues/1065
