### ISSUE TITLE
Server Execution Error

### ISSUE THREAD

**Issue by seialkali** [Codewars/codewars.com#612]
Getting the following error when trying to run tests in Kata:

"Server Execution Error:
Request Timeout: aggregate error"

**Comment by mayurpande** [comment]
I am also getting the same error, been happening for the last 45 minutes now. Except my error says;

"Server Execution Error"

**Comment by GCa** [comment]
Hi, I'm getting the same error.
I got the following several times, while trying to submit a solution in Javascript and Node 6.6:
"Server Execution Error"
"The server attempted to execute your code but there was an issue with the request. This should be a rare issue. Please try running your code again. If the issue persists, please contact us. "

When I tried using Javascript and Node 0.10.33 I got a cloudflare page with:
Error 504 : Gateway Timeout
runner.codewars.io 
Host Error
Ray ID: 2ed971df57e93dcb • 2016-10-06 13:26:27 UTC
and at the bottom of the page "This error was caused due to an issue processing the web request, not because of an issue executing your code. Please try again."

**Comment by vatson** [comment]
I got the same error
![Uploading Screen Shot 2016-10-06 at 15.31.46.png…]()

**Comment by cloud1230** [comment]
I got this one: Request Timeout: Process did not exit cleanly

**Comment by mayurpande** [comment]
Now I am getting the:

Error 504 Gateway Timeout

It keeps going back and forth between this and the "Server Execution Error"

**Comment by lnuic123** [comment]
i also can't execute my code, its always a different error

**Comment by Backhage** [comment]
The status page (https://codewars.statuspage.io/) shows all systems operational, which is obviously incorrect. Bug report on the status page?

**Comment by seanwbarry** [comment]
I am getting the following errors:
"
Request Timeout: Process did not exit cleanly
"

"
Server Execution Error:
Request Timeout: aggregate error
"

"
504 gateway timeout
"

**Comment by sigma-z** [comment]
I'm also getting various error message mentioned above.

**Comment by rollietikes** [comment]
Same errors as others seems to be a nagging issue at this point.

**Comment by aliasfoxkde** [comment]
I'm receiving the same error though https://codewars.statuspage.io/ shows 'All Systems Operational'..

**Comment by mayurpande** [comment]
they have finally put up an error message, saying "code runner: major outage"
![cw](https://cloud.githubusercontent.com/assets/6522456/19160127/9bf2cdf8-8be6-11e6-973c-16b457b81dbd.png)

**Comment by aliasfoxkde** [comment]
A little slow but working for me now.

**Comment by jhoffner** [comment]
Well that was a disaster. The servers are still performing really sluggish but the system has been stable for the last couple of hours now.
