### ISSUE TITLE
Running code (timeout error)

### ISSUE THREAD

**Issue by Adam-Morris** [Codewars/codewars.com#638]
Request Timeout: The server timed out running the request. This may be due to an issue with the backend server. Please try again.

Almost everytime I run my code. I am using Haskell and I am using the website from Australia.

**Comment by jhoffner** [comment]
Is this still happening? We had an outage yesterday I'm not sure if this is related.

**Comment by mgallion** [comment]
I'm seeing this issue this morning, trying to run tests in JavaScript though.

**Comment by oliver3** [comment]
Wanted to do a kata since long, and I got this issue with a TypeScript kata just now

Response for 

POST https://runner.codewars.io/run

form:
language:typescript
code: some code
fixture: some code
setup:IGx0piBpdzEcuO6SzVbfLDZYQqJkoK4Hgzj1r89NEIs=
--wcDY8zagoSpgWtBlXtk6QQ==--u
testFramework:mocha
languageVersion:1.8.x
relayId:581313e5ef51e87589000084
ciphered:setup
channel:runner:08c755e3-2eb1-b9b8-1c7e-70cfabbfa526

is 

`{"type":"run_timeout","message":"The server timed out running the request. This may be due to an issue with the backend server. Please try again.","stderr":"","setupTime":null,"totalTime":23011,"receivedAt":1477645574251,"responseAt":1477645597262,"languageVersion":"1.8.x","workerId":"i-27be34b4","result":{"serverError":true,"completed":false,"output":[],"passed":0,"failed":0,"errors":1,"error":"","timedOut":false},"token":"*hidden*"}`
