### ISSUE TITLE
Ordering Kata Solutions by Execution Speed

### ISSUE THREAD

**Issue by djdenton** [codewars/codewars.com#651]
Option to order Kata Solutions by execution speed rather than by count of best practice flags.

It may be that the execution speed is too variable to rely on, but I (and possibly others) would learn more by being able to review the most optimal solutions.

**Comment by jhoffner** [comment]
I'll leave this as an enhancement but its not likely to happen anytime soon. The result are just too inconsistent to rely on and if its not reliable, there is no point to having it. As we expand the system features we may make it possible to do multiple runs at once so that we can take the best result, which would be better but still not perfect.

**Comment by djdenton** [comment]
Thanks. Perhaps a relative measurement would make sense?

e.g. A small program A runs at the same time as the program being tested B and you express the execution speed as the ratio of the execution speeds (B/A).

If solution execution speeds are expressed as a multiple of A then it should be consistent (ish). Assuming that the ration of execution speeds B/A is constant

**Comment by kazk** [comment]
Closing because it's duplicated by #959 and that one has more comments.
