### ISSUE TITLE
Every time "Request Timeout" (same as #638)

### ISSUE THREAD

**Issue by dinglemouse2250** [Codewars/codewars.com#656]
Exact same problem as #638 

Submitting JavaScript solution always times out

> Server Execution Error:
> Request Timeout: The server timed out waiting for the request to be processed. This may be due to high server load. Please try your request again.

Been like this at least last 12hrs. 

"preview" site same.

**Comment by jhoffner** [comment]
Same kata that is causing this issue for you? I have very limited internet access right now but was able to test JS kata just fine, and the stats logs look good. Tons of successful requests have been coming through all day without any service interruptions. 

Any additional information you can find to help understand the issue would be helpful. Thanks.

**Comment by dinglemouse2250** [comment]
This one fails to submit for me every single time https://www.codewars.com/kata/find-grid-position/train/javascript

**Comment by dinglemouse2250** [comment]
FYI I've successfully some other JavaScript Kata today. So it seems the problem is isolated to that single Kata in the previous comment.

**Comment by ckrailo** [comment]
I've been having trouble with Elixir katas, saying the backend server is timing out (after getting the request received message). Usually, I can click "Run Suite" again (or maybe a couple times) and it'll finally work, but not this time. https://www.codewars.com/kata/easy-diagonal/train/elixir

**Comment by mattdanskey** [comment]
I and several people I work with have been having the timeout issue with this kata: https://www.codewars.com/kata/dead-ants/train/typescript

**Comment by Robin-Law** [comment]
Can confirm previous comment. Many ant deaths are going uncounted.

**Comment by jhoffner** [comment]
Thats odd, I just tried running all 3 kata posted here about 10 times each, each without a flaw (and pretty fast results). I tried running both the initial solution (default code when you start the kata) and the author's solution without any issues. Can you guys give me more info?

- Does the code timeout even if you run the initial given solution?
- What does the Status say? (Executing, Assigning Server, etc)
- Have you confirmed that other kata work fine?
- Does the kata having the issue run fine in other languages?
- Are there any loops or anything in your solution that might cause an infinite loop or otherwise slow response?
- Anything else you can think of that might be helpful?

**Comment by mattdanskey** [comment]
* Initial solution does not timeout, but takes at least five seconds to get back to me.
* Usually the status is Request received until it times out.
* Just confirmed https://www.codewars.com/kata/beginner-lost-without-a-map/fsharp works
* The kata is way more responsive for JavaScript than Typescript. I converted my solution to JavaScript and was actually able to see how wrong I was :) 

For TypeScript, even just changing the starting code to return "" (empty string) instead of 0 causes the timeout.

* I do have some regular expressions, but the same ones don't bog down the JavaScript version.
* I'm In the United States on the west coast.
* Connection speed should be way more than enough for this.

**Comment by mattdanskey** [comment]
I fixed my TS version from the insights the JS tests gave me, and got it to submit! Looks like the timeouts are what happen when there's any compilation issues.

**Comment by jhoffner** [comment]
I was just about to say the same thing. The `0 -> ""` change did the trick for me. Awesome, this has been a lot of help. I will be looking into this more tomorrow. Happy Halloween!

**Comment by jhoffner** [comment]
Issue should be resolved. Everyone please verify that your specific problem is fixed.

**Comment by mattdanskey** [comment]
👍 It tells me what errors my old broken 'solution' had in a reasonable time, as well as the error when altering the initial code to return "". Good work 😄

**Comment by g964** [comment]
I was able to publish it but when published always the same error:
```
/// <reference path="/runner/typings/main/ambient/mocha/index.d.ts" ></reference>
/// <reference path="/runner/typings/main/ambient/chai/index.d.ts" ></reference>
```
instead of
```
/// <reference path="/runner/typings/main/ambient/mocha/index.d.ts" />
/// <reference path="/runner/typings/main/ambient/chai/index.d.ts" />
```
so nobody will be able to dot the TS kata:-(

**Comment by dinglemouse2250** [comment]
mine working OK now. thanks.

**Comment by oliverjam** [comment]
I've been having this exact issue on Javascript Kata for the last few days. They consistently won't run the tests, instead responding with

> Server Execution Error:
> Request Timeout: The server timed out running the request. This may be due to an issue with the backend server. Please try again.

This morning I've been stuck trying to submit [this Kata](https://www.codewars.com/kata/growth-of-a-population/train/javascript) for hours to no avail.

- Does the code timeout even if you run the initial given solution?
Yes
- What does the Status say? (Executing, Assigning Server, etc)
It gets stuck at "Assigning a server..."
- Have you confirmed that other kata work fine?
I submitted another Javascript kata fine beforehand, but other JS kata have had this issue previously.
- Does the kata having the issue run fine in other languages?
I tested C++ and Java, both of which failed with the same error.
- Are there any loops or anything in your solution that might cause an infinite loop or otherwise slow response?
There is a while loop, but it runs perfectly fine anywhere else I test my code.
- Which country are you in?
United Kingdom
- How fast is your connection speed?
Pretty slow to be fair. Speed tested at 4MB/s
- Anything else you can think of that might be helpful?
Nope, sorry

**Comment by matthewmoppett** [comment]
Same problem here with a Java kata: https://www.codewars.com/kata/whitespace-interpreter/train/java. It times out even after I reset the problem and try to submit the initial "toy" solution. It gets stuck on "Request received" and then says "Server execution error: Request Timeout: The server timed out running the request. This may be due to an issue with the backend server. Please try again."

**Comment by AlexK89** [comment]
I can't submit any of katas. each time I got an error The server timed out waiting for the request to be processed. This may be due to high server load. Please try your request again.
I already tried different browsers and wifi's

**Comment by ayubov** [comment]
@AlexK89 I'm having the same trouble.

**Comment by ayubov** [comment]
it's not the first time. Can we get any downtime prediction in such cases?

**Comment by ayubov** [comment]
Different browsers, IP's, ISP's, same problem.
