### ISSUE TITLE
Lost 3000 honor

### ISSUE THREAD

**Issue by bkaestner** [Codewars/codewars.com#692]
Well, the issue is in the title. I had about 13000 honor and was therefore # 9 in the leaderboard. Today, I've noticed that I have only 10000 honor left. [site-events](https://www.codewars.com/users/bkaes/site-events) are inconclusive.

**Comment by rgvn** [comment]
I'm assuming you've done some translations and all the honor from them has vanished... because there's no translation row on your site-events. That's what happened for me too.

**Comment by SteffenVogel79** [comment]
Maybe this happened with the DB-Migration....

**Comment by jhoffner** [comment]
Good call @rn542, it looks like its possible for translation "site-events" to get lost in a special circumstance. The good news is that these events are basically just cached query results so its easy to restore them (they are designed to be restored, thats actually the issue here, these events were not being restored if a full rebuild was issued). 

A number of users with approved translations will likely see their honor go up once i pushed this fix out.

**Comment by jhoffner** [comment]
Changes are deployed, though the script that is running through users and updating them will take a while to finish.

**Comment by SteffenVogel79** [comment]
Now there is a new problem. It seems the counting of blue katas is wrong. Several users have to much points. Me too.
I have solved 60 approved blue katas. (Proved by the kata search). But in Site-events there is 167 solved blue katas.
And at the moment none of my approved published katas is blue. But i have points for 3 published blue katas.
It seems only the values for blue katas are wrong. Maybe a problem in the script?

**Comment by jhoffner** [comment]
Good catch! Found the cause, its been an issue apparently for just about ever. More honor updates coming.

**Comment by SteffenVogel79** [comment]
Great!
Now I am at place 6 again... ;-) But I will do my very best to get your place #5. :-)
