### ISSUE TITLE
Cannot use CodeWars since this morning.

### ISSUE THREAD

**Issue by SteffenVogel79** [Codewars/codewars.com#715]
Only 500er errors with my profile.
Since this morning (approx. for 6 hours)

![500](https://cloud.githubusercontent.com/assets/20505967/21049959/19b2d2c0-be18-11e6-8975-8b4ab5ed0151.PNG)

Status-Site says there are problems:
https://codewars.statuspage.io/

But other warriors can use CodeWars without problems....

My username is: SteffenVogel_79

**Comment by g964** [comment]
Same problem here for 8 hours (since 06:00 GMT)

**Comment by jhoffner** [comment]
Should be good now. Sorry about that.

**Comment by SteffenVogel79** [comment]
Thanks, Jake. Now it works for me.

What was the problem? Do g964 and I use other servers than the most warriors?

**Comment by jhoffner** [comment]
No it was actually just that your accounts were throwing errors when loading notifications.

Ironically it was due to a change that only both of you brought up, which was to stop showing old notifications. Turns out for some reason you had a few that were missing created_at time stamps.

Thanks,

--
Jake Hoffner
Sent with Airmail
