### ISSUE TITLE
Indication on the Kata Page if the Kata Has Been Solved

### ISSUE THREAD

**Issue by suic86** [codewars/codewars.com#727]
## Enhancement

For solved katas show a little tick sign next to the kata name on the kata page ([example](https://www.codewars.com/kata/help-bob-count-letters-and-digits)). 

## Rationale

Currently there's no indication on kata page if the kata has been solved or not.

**Comment by the-zebulan** [comment]
What about indicating specific languages the kata has been solved with instead of just a single solved indicator?

Sometimes I want to solve katas in JavaScript but many of them don't show up (in the search page) since I have already solved them in Python. The katas already show which languages are available with icons, maybe the solved languages could be highlighted different and some sort of filter option so you could see katas that you have solved in one language but are looking to solve in another language.

I thought I remembered reading a similar issue a while ago but I couldn't find it (only did a quick search). I'll make sure to edit my comment if I come across it.

**Comment by azwarners** [comment]
I completely agree with the-zebulan. I'm new at Codewars and I'd like to use it as a platform to practice multiple languages. It's frustrating not being able to see which ones you've completed in any given language without clicking all the way through to the Past Solutions tab. There really should be an easier way. I wonder if this has been made into its own issue yet.
