### ISSUE TITLE
Stats refreshes appear to take hours to complete

### ISSUE THREAD

**Issue by DonaldKellett** [Codewars/codewars.com#731]
One thing I've noticed recently is that stats refreshes appear to take hours to complete.  Seeing as this (stats refreshing) appears to be the major cause of publishing timeouts and weird fonts all over the website (etc.) (correct me if I am wrong), I find this to be a major inconvenience.  Perhaps something can be done to shorten the time taken to refresh?  If not, then perhaps stats refreshes could be done less often (e.g. once ever 24 hrs instead of once every 6 hours or less)?

**Comment by jhoffner** [comment]
Stats and Publishing both happen in the queue processor but publishing is a higher priority (and a different queue). The site processes 100k background jobs a day, stats are only a small part of that so its not the stats that are affecting publishing. 

The issue is that the background processing just goes down sometimes (it doesn't usually, but it has happened twice in the last 10 days). I'll keep this ticket open until I feel like its fully resolved.

**Comment by DonaldKellett** [comment]
Many thanks for your attention and reply on this issue :smile:  It seems that the background processes for Kata publishing are down yet once again.  This occurred after I published around 7-8 changes in rapid succession this morning (I was updating the common portions of the Kata Descriptions for all my Kata in one of my Series which contains 10 Kata in total) so it appears that a recent update to the Codewars website has caused the background processes to fail every day once a certain number of Kata publishes have been performed.  For some weird reason, the Stats also appear to refresh indefinitely for my profile when this happens (publishing timeouts).

**Comment by jhoffner** [comment]
Sidekiq (our backend processor) has gotten really flimsy with their recent updates - it seems that if they run out of RAM then they just kind of stop doing work without dying. At least this issue happens when on Docker. Whatever the case, I increased the RAM since the last occurrence of this and things **seem** to be good now.
