### ISSUE TITLE
Feauture: Untick up- or downvote + Question

### ISSUE THREAD

**Issue by suic86** [Codewars/codewars.com#754]
**Current Status:** There's no way to "untick" a down- or upvote.
**Suggestion:** When one clicks on up/downvote the up/downvote is removed.

**Question:** What is the point of the ability to vote for one's own solution? IMO this should be disabled :)

**Comment by jhoffner** [comment]
You don't have the ability to uncheck your own up vote? Please provide repo steps, this isn't a feature request this is a bug.

**Comment by suic86** [comment]
Alright, now it works. I've tried on a different machine (Win 7) and with a different browser (Chrome). I also thought that this has probably been caused my heavy customization of Firefox but even with Firefox is OK. I tried other browsers too and couldn't repro this behaviour. Therefore I close the issue. 

Thanks,

suic

P. S.: What about my question? :)

**Comment by jhoffner** [comment]
For the question. I think it's a carry over from comments (which have automatic up votes). 

It does make some sense the way it is though. Unlike a comment, You may not think your solution is that great. If you do, there are two options. If you think it's a clever/no compared to others then it's fair to favor your own solution. 

In theory it has a value, though obviously it makes it easier for some to get more attention by abusing it. You don't get honor for your own up vote though. 

I've definitely used it before (responsibly). I can see the argument for changing it though.

**Comment by dinglemouse2250** [comment]
> I've definitely used it before (responsibly). 

Ditto (responsibly 😉 ) Because often a solution gets a lot of votes simply because it was already at top of the list of best practices and then other sheeple come along and also tick it as well just out of a habit of agreeing with a popular choice. The result can be that sometimes a snowball gets rolling for a good  solution while your (possibly better) solution never gets a look-in. In this scenario ticking your own solution is really the only way to get it onto the bottom of the "Best Practices" list where it has any chance of being noticed at all. (It is good to not get any honour for a self-vote though)
