### ISSUE TITLE
"View Solution" renders incorrectly if code contains angle brackets

### ISSUE THREAD

**Issue by dinglemouse2250** [Codewars/codewars.com#765]
The "Discourse" page lets you "View Solution" of the person whose comment you are reading.

Occasionally the expanded "View Solution" does not render correctly and some code line are missing. OTOH everything looks fine if you go to the actual "Solutions" page to look at it.

For example http://www.codewars.com/kata/spaghetti-code-number-2-hard/discuss/javascript see View Solution of @myjinxin2015

I am using Chrome browser.

**Comment by jhoffner** [comment]
Please provide screenshots. Thanks.

**Comment by dinglemouse2250** [comment]
SPOILER!

Notice there is a big slab of code missing where the arrow is pointing in the following screenshot.

![issue-765](https://cloud.githubusercontent.com/assets/22114719/21844968/d1a88fd2-d844-11e6-8a9a-2578798b0c81.PNG)

The *real* code solution looks like this.

```
var spaghettiCode = function(plate) {
  var r="",max=0
  for(var i=0;i<plate.length;i++)for(var j=0;j<plate[0].length;j++)if(/[A-Z]/.test(plate[i][j])) {
    var c=plate[i][j],t=fill(i,j,c)
    if(t.length>max) [max,r]=[t.length,t.join("").replace(/S/g,"")||"S"]
  }
  return r
  function fill(i,j,c){
    if(i<0||j<0||i>=plate.length||j>=plate[0].length||!/[A-Z]/.test(plate[i][j])) return []
    var cc=plate[i][j]
    plate[i][j]=cc.toLowerCase()
    return [cc].concat(fill(i-1,j,c),fill(i+1,j,c),fill(i,j-1,c),fill(i,j+1,c))
  }
}
```

So you can see it has omitted everything **<plate..... length>** which I guess got misinterpreted as a tag or something

**Comment by brendanvos** [comment]
I'm having this issue occur when I use "view solution" on _some_ comments for java solutions.
![cutoff-1](https://cloud.githubusercontent.com/assets/11360165/22575985/05b0d3ae-e987-11e6-8977-885faac5f71d.PNG)
![cutoff-2](https://cloud.githubusercontent.com/assets/11360165/22575986/05b0f8e8-e987-11e6-9b97-e163f584b5aa.PNG)

You can see that the issue begins where a '<' would otherwise be, indicating that the rest of the code is being consumed an improper html tag (which may or may not close within the code if it has a matching '>'). 
It seems to happen quite often to the for statements in the style of (int i=0; i<=num; i++).... except when it doesn't:
![not-cutoff-2](https://cloud.githubusercontent.com/assets/11360165/22576676/e574b386-e98a-11e6-9253-c68c53d1cd6c.PNG)

@jhoffner Is more information still needed?

**Comment by Voileexperiments** [comment]
This is still happening:

https://www.codewars.com/kata/react-with-jsx/discuss/javascript

I recall seeing the same problem a few days back, so my natural instinct tells me to go look at the React with JSX kata, and indeed every comment's view solution shows code with all the html tags in the code stripped.

**Comment by Chrono79** [comment]
I know this is closed, but it's still happening here: https://www.codewars.com/kata/59f44c7bd4b36946fd000052/discuss#5df386d97a3644001942f5fe

**Comment by kazk** [comment]
Deployed the fix

**Comment by FArekkusu** [comment]
Now all HTML symbols are escaped when comparing your own solutions to others.

![image](https://user-images.githubusercontent.com/31668662/72476934-25de5900-37f7-11ea-8e14-18d963ced71d.png)

**Comment by kazk** [comment]
WTF :man_facepalming:

That's from the list of solutions right? It seems to work fine if you go to its own page and compare.

**Comment by kazk** [comment]
I think I found the cause (data from the server is escaped only on that page) so I'll deploy it soon. Thanks for letting me know.

**Comment by kazk** [comment]
Deployed
