### ISSUE TITLE
up arrow on ipad

### ISSUE THREAD

**Issue by snackycracky** [Codewars/codewars.com#802]
hey,
codewars is great! Keep up the good work on adding languages.
My issue is the following: I have an Ipad and a wireless mac-keyboard connected. I can use your editor fine but only the up-arrow-key does not work :/ i know that this is a strange setup but well... its a bug that bugged me today ;)

**Comment by snackycracky** [comment]
same with the ESC key in Vim mode.

**Comment by snackycracky** [comment]
ping

**Comment by kazk** [comment]
This is most likely CodeMirror issue. Google search shows some issues in their repo and stackoverflow questions.

If you're using vim mode, how about `K` and `Control+[`?

**Comment by kazk** [comment]
The second part of #606 seems to be the same issue.

**Comment by snackycracky** [comment]
K and Control+[ didn't working for me either.

**Comment by kazk** [comment]
How does the official CodeMirror demos work for you?

- [basic demo](http://codemirror.net/)
- [vim demo](http://codemirror.net/demo/vim.html)

**Comment by snackycracky** [comment]
Hey, sorry for the late reply. So the vim and the basic demo work fine with the up-arrow key (iPad with mac-keyboard).

**Comment by kazk** [comment]
Good :) Maybe updating CodeMirror to more recent version will fix this issue then.

I couldn't find one mentioning iOS specifically, but there're several [releases](https://github.com/codemirror/CodeMirror/releases) containing bug fixes since  [5.19.0](https://github.com/codemirror/CodeMirror/releases/tag/5.19.0) (`CodeMirror.version`).

/cc @jhoffner

**Comment by kazk** [comment]
Sorry for the lack of updates. CodeMirror was updated to 5.24.4, so it should work if it demo worked in 2017-05-22.
