### ISSUE TITLE
API endpoints for completed & authored challenges not working

### ISSUE THREAD

**Issue by mn113** [Codewars/codewars.com#806]
I can't seem to access many of the endpoints listed on dev.codewars.com. I have tried with and without my API key for all the below. So far I am just trying them in the browser location bar.
```
https://www.codewars.com/api/v1/users/mn113?access_key=<my_key> // works
http://www.codewars.com:3000/api/v1/users/mn113/code_challenges/completed  // not found
http://www.codewars.com:3000/api/v1/users/mn113/code_challenges/authored  // not found
https://www.codewars.com/api/v1/users/mn113/code_challenges/authored  // not found
https://www.codewars.com/api/v1/code-challenges/valid-braces  // works
```
Is the documentation wrong, or are those particular endpoints (challenges authored & challenges completed) simply not running/working right now?

**Comment by adrianeyre** [comment]
I'm having the same problem, it's simply timing out.

**Comment by 10XL** [comment]
Just noticed that documentation was updated today, https://github.com/Codewars/codewars-api-docs/pull/6/commits/928797a2ef6f4e112d8bef3cbcf9df4ac9c50c99.
Use `http://www.codewars.com/api/v1/users/some_user/code-challenges/`.

**Comment by adrianeyre** [comment]
Yeah, sorry I forgot to update this ticket. I spoke to @noLan yesterday and he sorted it for me. It didn't need the port number and needed to be code-challenges. Both authored and completed now work if you pass your api key.

**Comment by kazk** [comment]
Closing this because the documentation has been updated.

- https://dev.codewars.com/#get-user:-authored-challenges
- https://dev.codewars.com/#get-user:-completed-challenges


@mn113 

- https://www.codewars.com/api/v1/users/mn113/code-challenges/authored
- https://www.codewars.com/api/v1/users/mn113/code-challenges/completed
  - This endpoint is now paginated and returns `200` completed kata per page. Use `totalPages` to find the number of pages and request further using the `page` parameter, e.g., `?page=1`.
