### ISSUE TITLE
Kata Output : mangled/discarded ASCII output

### ISSUE THREAD

**Issue by nomennescio** [Codewars/codewars.com#831]
Hi,

When printing data to stdout in C using 'puts', (cr_log_info is NOT available), output is discarded and/or mangled. When I output the following string:

`<~1I4T&>9Z0Y6[EH-:*h&<,bD_-$<EM;d=<a<CLh<@lZ/,3(HGC~>`

the Kata Output pane only shows:

`<~1I4T&>9Z0Y6[EH-:*h&<,bD_-$`

Maybe this has to with escape character being interpreted by the output pane?

**Comment by jhoffner** [comment]
Yeah this is being interpreted as HTML. You can directly tell the output to unescape HTML output using `<LOG:ESC:><~1I4T&>9Z0Y6[EH-:*h&<,bD_-$<EM;d=<a<CLh<@lZ/,3(HGC~>`. 

If it wasn't for breaking changes I would reverse this so that you needed a special prefix to unescape - but I think we might be stuck with this for now. 

However I could possibly add a new type of config setting/mode switch that changes the default behavior - so that the prefix isn't necessary.

**Comment by jhoffner** [comment]
It was a mistake of the original design to allow for HTML by default within the log output. As a way to try to deal with that design flaw, I'm adding some auto-detection to try to determine if content contains any HTML and if not, it will render the content escaped. 

I will be releasing this change today.
