### ISSUE TITLE
Server Execution Error "Unexpected token { in JSON at position 1240339"

### ISSUE THREAD

**Issue by simonvpe** [Codewars/codewars.com#843]
I get these errors a lot. Sometimes only on the "Run Examples" build, and sometimes on the "Attempt" build. If i change a line, or add/remove a write to stdout it changes to either not appear at all, or to appear on only one of the builds.

Sometimes I get HTTP 5xx errors or timeouts saying that I write too much to stdout (even though I don't).

This Kata is runs very heavy optimization tests so it's kind of taxing on the servers, is this the issue? Should there be more robust error handling when the server can't cope with the load?

I might add that I can build about one in tweny times so it is very time consuming and ruins the experience completely!

BR Simon

**Comment by menip** [comment]
I'm having the same issue with the [longest_palindrome](https://www.codewars.com/kata/54bb6f887e5a80180900046b/train/python) kata. My code:
```python
def longest_palindrome (s):
    longest = 0
    for i in range(len(s)):
        si = s[i:]
        for j in range(len(si)):
            sj = si[:j+1]
            if sj == sj[::-1] and longest < len(sj): 
                    longest = len(sj)
    return longest
```

**Comment by ioncrash** [comment]
I've been getting similar errors continuously for about an hour. Position number seems to be different every time I run it

**Comment by Khanthulhu** [comment]
I'm getting a similar error on Simple Fun #27: Rectangle Rotation.
My code is as follows.
`class Line
  attr_reader :slope, :b
  def initialize(point_x, point_y, slope)
    @b = point_y - point_x * slope
    @slope = slope
  end
  def y_value(x)
    @slope * x + @b
  end
end

# rectangle abcd is made with lengths ab, bc, cd, ad
def rectangle_rotation(side_1, side_2)
  a = [side_1, side_2].max
  b = [side_1, side_2].min
  
  # equation for diagnal line
  # length for diangal found with pythagorean theorum
  diagnal_length = Math::sqrt(a ** 2 + b ** 2)
  half_diagnal_length = diagnal_length / 2.0
  puts diagnal_length
  # slope = (rise of ab + rise of bc) / (run of ab + run of bc)
  side_ab_delta_x = a * Math::sqrt(2) / 2
  side_ab_delta_y = - 1 * a * Math::sqrt(2) / 2
  side_bc_delta_x = b * Math::sqrt(2) / 2
  side_bc_delta_y = b * Math::sqrt(2) / 2
  line_ac_slope = (side_ab_delta_x + side_bc_delta_x) / (side_ab_delta_y + side_bc_delta_y)
  line_ac = Line.new(0, 0, line_ac_slope)
  # knowing the slope of the line and length of the line we can calculate the location of the point
  # create a triangle with half the diagnal as the hypotenuse, the delta y as side a and delta x as side b
  # a / b = slope
  # a**2 + b**2 = c**2
  # solve slope equation for a and substitute
  # a = slope * b
  # (slope * b)**2 + b**2 = c**2
  # solving for be we get b = sqrt(c**2 / (slope**2 + 1))
  # plugging in be we get a = slope * sqrt(c**2 / (slope**2 + 1))
  # since the origin is 0,0 that means those are the coordinates for points a b
  point_a_x_coordinate = Math::sqrt(half_diagnal_length**2 / (line_ac.slope**2 + 1))
  point_a_y_coordinate = line_ac.slope * Math::sqrt(half_diagnal_length**2 / (line_ac.slope**2 + 1))
  line_ab = Line.new(point_a_x_coordinate, point_a_y_coordinate, -1)
  # the coordinates we discovered for line ab are the point where ab intersects with ad and therefore can be used in both
  line_ad = Line.new(point_a_x_coordinate, point_a_y_coordinate, 1)
  # due to the symmetry of rectangles, the opposite number is the coordinate for the intersection of bc and cd
  line_bc = Line.new(-1 * point_a_x_coordinate, -1 * point_a_y_coordinate, 1)
  line_cd = Line.new(-1 * point_a_x_coordinate, -1 * point_a_y_coordinate, -1)
  puts "#{a}, #{b}"
  puts "y = #{line_ab.slope}x + #{line_ab.b}"
  puts "y = #{line_bc.slope}x + #{line_bc.b}"
  puts "y = #{line_cd.slope}x + #{line_cd.b}"
  puts "y = #{line_ad.slope}x + #{line_ad.b}"
  count = 0
  (-1 * diagnal_length.floor).upto(diagnal_length.ceil) do |x|
    (-1 * diagnal_length.floor).upto(diagnal_length.ceil) do |y|
    #puts "(#{x}, #{y}):#{y > line_ab.y_value(x)} #{y > line_ad.y_value(x)} #{y < line_bc.y_value(x)} #{y < line_cd.y_value(x)}"
      if y > line_ab.y_value(x) && y > line_ad.y_value(x)
        if y < line_bc.y_value(x) && y < line_cd.y_value(x)
        puts "(#{x}, #{y})"
          count += 1
        end
      end
    end
  end
  count
end`

**Comment by Khanthulhu** [comment]
Having the same problem with Simple Fun #27: Rectangle Rotation. The position changes each time I submit.

**Comment by jhoffner** [comment]
Issue moved to [Codewars/codewars-runner-cli #398](https://github.com/Codewars/codewars-runner-cli/issues/398) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jhoffner** [comment]
I've moved this to the CLI repo
