### ISSUE TITLE
Editing Kata : server error "User is not permitted to save"

### ISSUE THREAD

**Issue by nomennescio** [Codewars/codewars.com#847]
Apparently I should be able to edit Kata.
I encountered a Kata for which the author did not respond for over 2 years to correct a small error which makes the Kata unsolvable for Haskell.
However, when trying to edit I get an error message:

server error 500 

"User is not permitted to save"

What's going on? Is this a real permission error, then please improve error reporting, if not, please solve the failing permissions.

**Comment by javatlacati** [comment]
Same here with this link: https://www.codewars.com/kata/find-the-smallest-integer-in-the-array/edit/csharp

**Comment by omegahm** [comment]
I get the same on every kata that I try to edit. I know I have previously been able to edit katas, so why not now?

**Comment by nomennescio** [comment]
Kata still has this error:
https://www.codewars.com/kata/classic-hello-world/edit/python

**Comment by nomennescio** [comment]
And this one too:
https://www.codewars.com/kata/ascii85-encoding-and-decoding/edit/python

**Comment by javatlacati** [comment]
@nomennescio I can edit the first but not the second perhaps because I'm the author of the first

**Comment by kazk** [comment]
As far as I know, approved katas are only editable by the author and contributors. And tests are locked once the number of submitted solutions is above the threshold (`500`?).

@omegahm were you able to edit **approved** kata that you had never contributed before?

---

@jhoffner I think it's really confusing how "Edit Kata" is visible even if you're not allowed to edit.

This *looks* like I'm allowed to edit:
![image](https://cloud.githubusercontent.com/assets/639336/23935567/c85d69b6-0909-11e7-9631-d3befc627785.png)

When I click, I see this:
![image](https://cloud.githubusercontent.com/assets/639336/23935618/02714712-090a-11e7-8a3f-29b51591f314.png)

This message makes the situation worse because it looks like it's an error that I can't edit.

### Suggestions

- Show "Edit Kata" only if the user is allowed to edit, or
- Improve the error message

**Comment by omegahm** [comment]
@kazk I can't remember. Might have been unapproved katas, that I edited.

How can I contribute to the kata, if I can't edit it?
All I want to do, is fix various test cases, or even add additional ones, since the author might have forgot some corner cases.

---

I think that the edit link should be removed, if I'm not allowed to edit. It seems very weird to have the link, just to say I'm not allowed in.

**Comment by g964** [comment]
See post #851: I can't translate one of my own kata... Server error.

**Comment by kazk** [comment]
@omegahm I usually make a comment labeled "Suggestion". I do this even for Beta katas if I don't know the author. I think the problem with katas with inactive authors should be discussed separately. I found #496.

@g964 Do you see "User is not permitted to save"? I think your issue is different from this one because you've been able to translate other katas?

**Comment by jhoffner** [comment]
I'm deployed some changes. Can someone test on preview.codewars.com and tell me if the edit link no longer shows up where it was before?

**Comment by kazk** [comment]
@jhoffner confirmed on preview.codewars.com.

![image](https://cloud.githubusercontent.com/assets/639336/23973248/71613532-0992-11e7-9082-ca2b6e665166.png)

Maybe also hide that "|"?

**Comment by javatlacati** [comment]
Trying it on preview and then.,...

>5xx: Server Error
>
>This doesn't happen often, but it looks like something is broken. Hitting the back button and trying >again might be your best bet. If that doesn't work you can head back to the homepage.
>
>There might be more information on our status page.
>
>Additional Details:
>Web server is returning an unknown error
>
>There is an unknown connection issue between Cloudflare and the origin web server. As a result, the >web page can not be displayed.
>
>    Ray ID: 3403265a798b58bb
>    Your IP address: 200.34.164.101
>    Error reference number: 520
>   Cloudflare Location: Dallas

**Comment by nomennescio** [comment]
Still see this issue. I encountered it multiple times:
https://www.codewars.com/kata/my-smallest-code-interpreter-aka-brainf-star-star-k/edit/python
https://www.codewars.com/kata/evaluate-mathematical-expression/edit/ruby
https://www.codewars.com/kata/simpler-interactive-interpreter/edit/python

These are all Katas I completed, but I did not contribute to them.

I'm not sure if I should or should not be able to edit them (cannot think of a reason why as a moderator you're not allowed to edit?)

**Comment by kazk** [comment]
@nomennescio @10XL was able to fix some other kata by [forking the problematic translation](https://github.com/Codewars/codewars.com/issues/496#issuecomment-287504379).

I think editing privilege for approved kata is highly debatable and there have been many discussions before.
For now, try contacting the translator by commenting on the translation or fork:

- [Python translation of "My smallest code interpreter (aka Brainf**k)"](https://www.codewars.com/kumite/546fbcdb54af40445b00047f?sel=546fbcdb54af40445b00047f)
- [Ruby translation of "Evaluate mathematical expression"](https://www.codewars.com/kumite/5565638aaba4db3d66000144?sel=5565638aaba4db3d66000144)

Unfortunately "[Simpler Interactive Interpreter](https://www.codewars.com/kata/simpler-interactive-interpreter)" doesn't have Python under `/translations` so we can't use this workaround. Also [the author](https://www.codewars.com/users/Wintermute) is inactive, last seen on March 2016, so even if the translation was available fork won't get approved.

**Comment by nomennescio** [comment]
It currently looks I have less ability to edit Katas.
The following Kata is abandoned, and has an error in it, which I could perfectly edit to make the Kata solvable again. Suddenly I do not even see the 'edit' button on this kata:
https://www.codewars.com/kata/hit-count/c

I'm not sure this is the correct way to handle moderation...

**Comment by kazk** [comment]
> The following Kata is abandoned

Both the translator and the author are last seen Mar 2017?
Can you try the workaround I commented above? Try commenting [the C translation](https://www.codewars.com/kumite/581fafb855c3d28e20000013?sel=581fafb855c3d28e20000013), if the translator doesn't respond, fork it and ask the author to approve it.

I understand the frustration and inconvenience, but I don't think it's easy to fix this as it appears and I think there're more issues being worked on with higher priority. At least there's a  possible workaround and hiding the "Edit Kata" prevents further confusion about ability to edit. If you don't see it you can't edit.
