### ISSUE TITLE
Ramda `converge` is not working

### ISSUE THREAD

**Issue by afhole** [Codewars/codewars.com#854]
I am able to import and use Ramda, but the `converge` function is broken:

"Error: First argument to arity must be a non-negative integer no greater than ten"

See here:
https://www.codewars.com/kata/reviews/54cd002407ba21e38f00000f/groups/58c04f0e22a273878e002869

**Comment by piet-v** [comment]
Multiple functions are missing (such as R.Until) due to an older version version of Ramda. Seems to be before version 0.18.0? (currently 0.23.0)

**Comment by kazk** [comment]
Rambda is not [officially supported](https://github.com/Codewars/codewars-runner-cli/blob/cf7a91e7ba90239c51cf550a61189c17ff8c1205/documentation/environments/node.md). 
Rambda 0.15.1 is installed because `union-type@0.1.6` depends on it.

Subtree of `npm ls --dev --prod`:

```
+-- deku@2.0.0-rc16
| +-- dift@0.1.12
| | `-- bit-vector@0.1.6
| +-- index-of@0.2.0
| +-- is-svg-element@1.0.1
| +-- setify@1.0.3
| | `-- natural-selection@1.0.0
| +-- svg-attribute-namespace@2.1.0
| +-- uid@0.0.2
| `-- union-type@0.1.6
|   `-- ramda@0.15.1
```

**Comment by leighman** [comment]
Can we get it officially supported somehow?

**Comment by kazk** [comment]
I'm closing this because Ramda is currently not officially supported and this should be a feature request on [Codewars/codewars-runner-cli](https://github.com/Codewars/codewars-runner-cli).

@leighman you can open an issue on [Codewars/codewars-runner-cli](https://github.com/Codewars/codewars-runner-cli) requesting it.
