### ISSUE TITLE
If username contains forward slash links to the users profile wont work

### ISSUE THREAD

**Issue by Doublecaster** [Codewars/codewars.com#86]
I changed my username to //Sami and now all links to my profile show 404 page. It seems to ignore all / characters as //sami shows another users profile. I fixed this problem by directly entering %2F%2F to the url instead of the //.

Current profile links that show 404 error: http://www.codewars.com/users///Sami
Links to user "sami" profile: http://www.codewars.com/users///sami
Links correctly to my profile: http://www.codewars.com/users/%2F%2FSami

**Comment by bkaes** [comment]
While we're at it, couldn't we replace the current non-permanent links with permanent ones? There were/are several issues with the current system, e.g. renaming stuff usually leads to 404, or to inconsistencies.

StackOverflow does a pretty good job at it by introducing the human-readable variant after the ID, for example:

    http://stackoverflow.com/questions/21959851/how-do-i-use-the-same-slugs-for-custom-post-types-and-taxonomies-in-wordpress
    http://stackoverflow.com/questions/21959851/ (redirect to the link above)
That way, @Doublecaster's profile page would be

    http://www.codewars.com/users/4325af24324/Sami

**Comment by Doublecaster** [comment]
Is it possible that some of the inconsistencies have something to do that the user urls are case sensitive and that you dont escape/forbid special characters that interfere with generated urls? (Like the forward slashes).

**Comment by bkaes** [comment]
> Is it possible that some of the inconsistencies have something to do that the user urls are case sensitive and that you dont escape/forbid special characters that interfere with generated urls? (Like the forward slashes).

That's not really solving the problem:

- escaped generated URLs aren't really that human-friendly anymore,
- forbidden special characters in name isn't really user-friendly anymore,
- neither of both solutions will help if the user changes his name.

After all, names can (and __will__) change. This does not only affect user pages, but also katas. Katas change their name during their beta frequently, which invalidates their URL completely, not only in comments, but also in your bookmarks. Real permanent links would solve this problem altogether. IIRC the first version of Codewars actually used the MongoDB instead of the user-friendly name.

I think I've posted something along this already in the old bug-report forum. Either way, escaping the user links would be a first measurement, but probably not the last.

**Comment by Doublecaster** [comment]
That does make sense and it seems to be a good solution overall. Are you intending to ignore all characters after users/id/? Stackoverflow almost ignores everything after the id but not everything. http://stackoverflow.com/questions/21959851/asd/asd/asd/ seems to lead 404 page.

**Comment by bkaes** [comment]
> http://stackoverflow.com/questions/21959851/asd/asd/asd/

AFAIK SO's URL scheme is `domain/question/question-id/human-readable/answer-id`, and non-id-like things get ignored in the ID part. It depends on Jake's decision whether the scheme will get changed and to what result. Also, I'm not sure whether the result will be easy: SO uses a relational DB, Codewars a document-oriented (which is probably the reason for all the invalidated links).

> Are you intending to ignore all characters after users/id/?

That's up to Jake, I guess. I'm just contributing to the discussion ;).

**Comment by jhoffner** [comment]
Sounds like we are talking about two issues here:

### Permalinks
We do support permalink URLs. Either the slug (human readable id) or the actual Mongodb ID can be used to lookup a record. I could implement a mechanism so that the system will match to old slugs if a username or kata get renamed. Kata should have already been doing this as a part of the slug field module I am using, but something may not be working or enabled. For users the collection is much larger so in order to keep performance optimal I will have to implement a custom optimized mechanism and will probably only track the most recent name change.

### Name Changes
For this it looks like my regex to restrict usernames could use some tweaking.

**Comment by jhoffner** [comment]
Forward slashes are no longer allowed. Closing since this is the main topic
