### ISSUE TITLE
High Priority: A bug in the PHP Testcases that set all TestCases as passed

### ISSUE THREAD

**Issue by osofem** [Codewars/codewars.com#880]
Just discovered a bug in the PHP testcase that let any code pass once it extend the Testcase class. For example this kata (https://www.codewars.com/kata/55911ef14065454c75000062) as Testcases like 

<code>
class MultiplyStringsTest extends TestCase {
  public function testBigExamples() {
    $this->assertEquals("5619135910", multiply("98765", "56894"));
    $this->assertEquals("2830869077153280552556547081187254342445169156730", multiply("1020303004875647366210", "2774537626200857473632627613"));
    $this->assertEquals("444625839871840560024489175424316205566214109298", multiply("58608473622772837728372827", "7586374672263726736374"));
    $this->assertEquals("81129638414606663681390495662081", multiply("9007199254740991", "9007199254740991"));
  }
}</code>

All I have to put in my solution to pass this kata is
<code>
class Multiply extends TestCase {
  function multiply(string $a, string $b) {
  echo "whatever";
}
}</code>

I confirmed with two other random PHP katas, all I have to do to pass the kata is to extend the Testcase in my solution and my solution is marked as correct.

**Comment by DonaldKellett** [comment]
That sounds like a very serious bug indeed, many thanks for reporting it.  All the PHP Kata and Translations that I author contain a large number of both fixed and random tests in an attempt to minimize the chances of a user cheating but if that's all that's needed to bypass all the existing tests then my anti-cheat measures become pretty much useless.  @jhoffner Just giving you a heads up, you might want to really look into this one :smile:

**Comment by DonaldKellett** [comment]
By the way I think that this problem arises because when PHPUnit is executed, it only executes the test cases in the first class that extends `TestCase` instead of executing all classes that happen to extend it.  Since the user solution always comes before the Test Cases, such a cheat is guaranteed to pass.  A potential solution to this cheat might be to implement some sort of regex check on the user solution in the PHP Coderunner itself to ban the keyword sequence `extends TestCase` before it is concatenated with everything else and executed.  Cheers :smile:

**Comment by jhoffner** [comment]
There are all kinds of ways to cheat, especially for the scripted languages. I'm not going to try to bulletproof them all. We have some scripts which help detect scripts in the background, and the code is out in the open so if someone gets caught they will eventually get reported and flagged (if our background scripts don't do it for us). I can think of 10 different ways to cheat PHP. 

The only thing that really concerns me here is was this a mistake that caused you to pass unintentionally? If that's the case then maybe its worth trying to patch. If we do try to patch this then we should close the bug here and open it within the [cli repo](https://github.com/Codewars/codewars-runner-cli). Since either way it should be closed here I'm going to do it now.

**Comment by osofem** [comment]
@jhoffner You get you right, you are saying it won't be fixed?

**Comment by DonaldKellett** [comment]
@osofem No, he means that if you want to get this bug fixed then you should open it at https://github.com/Codewars/codewars-runner-cli instead since this is a runner-specific Issue and not a generic Site "Issue".

**Comment by kazk** [comment]
@osofem you can open an issue and/or submit PR on [Codewars/codewars-runner-cli](https://github.com/Codewars/codewars-runner-cli). There're many ways to cheat and it's not even hidden because it's open source.

**Comment by kazk** [comment]
@DonaldKellett

> All the PHP Kata and Translations that I author contain a large number of both fixed and random tests in an attempt to minimize the chances of a user cheating but if that's all that's needed to bypass all the existing tests then my anti-cheat measures become pretty much useless.

Your tests can be cheated, but they're not useless at all. Your test coverage is always great and it's helpful. I highly respect your work :)
I don't think the focus should be "anti-cheat". I never understand why people cheat :/

**Comment by osofem** [comment]
Oh ok, my heart skipped when I thought he meant it won't be fixed. Thanks guys for the response. Submitted to https://github.com/Codewars/codewars-runner-cli

**Comment by DonaldKellett** [comment]
Great point @kazk, the purpose of full test coverage is and always has been to ensure that a submitted solution has no logical flaws :smile:  Cheaters are gonna cheat no matter how good the anti-cheat is :p
