### ISSUE TITLE
Setup GitHub Pages for Codewars documentation

### ISSUE THREAD

**Issue by jhoffner** [Codewars/codewars.com#881]
http://progrium.viewdocs.io/viewdocs/ should be used with this repo to eventually replace the documentation shown on Codewars. This would allow the community to help keep documentation up-to-date through pull requests.

**Comment by kazk** [comment]
Are you working on this now? If you haven't started, I can start and open a PR with `/docs`.

![image](https://cloud.githubusercontent.com/assets/639336/24771822/e41e8542-1ac3-11e7-9e5c-f7c348f90964.png)

(I had to fix the `previewdocs.go` because it required `origin` to end with `.git`.)

**Comment by jhoffner** [comment]
Go for it. I added the task as a placeholder. If we can get the ball rolling I bet others will join in pretty quickly.

**Comment by kazk** [comment]
Ok, I'll start working on this.

**Comment by jhoffner** [comment]
Thanks @kazk!

**Comment by kazk** [comment]
@jhoffner does this have to be ViewDocs? I've been trying things out and found some issues.

> The viewdocs.io server only serves markdown files. Static files such as javascript, image, css, etc. must be served from an alternate location. 
> <http://progrium.viewdocs.io/viewdocs/custom-layouts/>

Later it shows how to workaround using GitHub Pages and `git` hooks which is annoying to setup.

The most popular project I've found using ViewDocs uses `cdn.rawgit.com` for static files, i.e., `https://cdn.rawgit.com/Codewars/codewars.com/TAG/docs/assets/FILE`. `TAG` is necessary because `cdn.rawgit.com` is permanent.

---

I've looked for alternatives and simply using GitHub Pages seems to work.
`/docs` on `master` branch can be configured as the source and the documentation will be available on `https://codewars.github.io/codewars.com` (and optionally on a custom domain).

> You can configure GitHub Pages to publish your site's source files from `master`, `gh-pages`,
> or a `/docs` folder on your master branch for Project Pages and other Pages sites that meet certain criteria.
> [Configuring a publishing source for GitHub Pages](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages)

See [Publish Your Project Documentation with GitHub Pages](https://github.com/blog/2233-publish-your-project-documentation-with-github-pages).

Another benefit is that, I think, it's also possible to have `_data/environments.yml` and generate the table of supported environments for the documentation using a template.

**Comment by jhoffner** [comment]
I haven't done a lot of research yet. I had just saw another project using this one and thought to add the issue as a placeholder. I'm open to whatever we think will be the easiest to collaborate on and functional enough to be effective. 

Gitter also has a new topics feature coming out so between that and the new documentation site, we will be able to kill both the custom CW forum and Docs (which are way past their expiration date)

**Comment by kazk** [comment]
Can you take a look at <https://kazk.github.io/codewars-docs-test/>?
I haven't worked on styling, but I'm trying to make this easy to maintain. The source is [here](https://github.com/kazk/codewars-docs-test).

![image](https://cloud.githubusercontent.com/assets/639336/24821026/149befe2-1ba1-11e7-9ce9-28ce49d114b4.png)


![image](https://cloud.githubusercontent.com/assets/639336/24820967/d047d95a-1ba0-11e7-8124-cab52b351037.png)
![image](https://cloud.githubusercontent.com/assets/639336/24820981/e1adc39e-1ba0-11e7-9ebb-5b69f5408e40.png)

**Comment by kazk** [comment]
- Contributors can just edit the content in YAML and use markdown in it
- Each definition and headers get `id` so it can be used to point to specific part of the documentation
- Easy to change overall structure because it's just data

**Comment by jhoffner** [comment]
This is pretty great! I say we go with this. A few thoughts: 

- We should support markdown document as well, for anything that doesn't need a structure (such as test documentation), markdown would be more flexible. 
- Some of the yml files in the documentation repo could probably by reference by other projects, including the CLI. Right now we are maintaining different config files for multiple projects.

**Comment by kazk** [comment]
> - We should support markdown document as well, for anything that doesn't need a structure (such as test documentation), markdown would be more flexible.

Markdown is supported by default :)
See <https://kazk.github.io/codewars-docs-test/this-is-markdown/> and [source](https://github.com/kazk/codewars-docs-test/blob/e6bd83e40c2829ee14a40ed30cbaa649637932b0/docs/_pages/this-is-markdown.md).
I haven't tried, but it should be possible to make `@user`, `#issue`, `repo#issue`, `:emoji:` to work like in this comment.

> - Some of the yml files in the documentation repo could probably by reference by other projects, including the CLI. Right now we are maintaining different config files for multiple projects.

Do you mean to also move the docs from CLI? I was thinking about adding the API section by updating the information from 'codewars-api-docs'.

**Comment by jhoffner** [comment]
> Do you mean to also move the docs from CLI?

I actually meant just that Codewars, Qualified, [Codecasts](codecast.qualified.io) and the CLI all to some level or another have a config file within each repository explaining which languages are available to be used (less so the CLI). When a new language is added all of these configs needs to be updated. That might be ok though, we support different languages at different times within the products. 

As far as moving the docs from the CLI. I'll have to think about that. Its nice having it in that repository because when someone adds a new feature/language its a little easier to identify that as being missing (though keeping up with it hasn't worked much so far). Having everything here would require 2 separate PR's to 2 different repos but it would keep documentation together.

>  I was thinking about adding the API section by updating the information from 'codewars-api-docs'.

Interesting. So you would embed [Slate](https://github.com/lord/slate) within Jekyll?

**Comment by kazk** [comment]
> Its nice having it in that repository because when someone adds a new feature/language its a little easier to identify that as being missing (though keeping up with it hasn't worked much so far). Having everything here would require 2 separate PR's to 2 different repos but it would keep documentation together.

I agree, I didn't consider CLI because of this. We can also setup GitHub Pages on CLI repo and add a link from this one.

> So you would embed Slate within Jekyll?

I was just thinking that it might make sense to merge 'api-docs' into this and wasn't sure how to do it. I found [slogsdon/slate-for-jekyll](https://github.com/slogsdon/slate-for-jekyll) by googling and it says it works by swapping the static site generator component of Slate, replacing `Middleman` with `Jekyll`. Maybe we can look into embedding Slate within Jekyll after setting this up.

**Comment by kazk** [comment]
Is there a set of assets (images, icon fonts, css, used colors, etc.) that I can use for the documentation? I got the logo from 'api-docs' and have been looking at the source for colors.

---

I noticed that the profile badge svg uses much darker gray `#333` and I think it should be `#999` like others. I don't know if this is related, but `App.consts.colors.ranks.black` is also `#333`.

Profile badge (`#333`):
![image](https://cloud.githubusercontent.com/assets/639336/24824989/9fc04464-1bca-11e7-9dd7-d47c5ab897da.png)

About/Docs (`#999`):
![image](https://cloud.githubusercontent.com/assets/639336/24825000/b3dfc8ca-1bca-11e7-809a-1399b462fdb1.png)

Top right (`#999`):
![image](https://cloud.githubusercontent.com/assets/639336/24825059/c7abc7d6-1bcb-11e7-805e-0bba922cc659.png)

**Comment by DonaldKellett** [comment]
Nothing to do with the actual Issue at hand but regarding the Dan badges, I personally think that those presented in the Docs look more natural (and therefore better in general).  May I suggest that the Dan badge for the user profile be edited to use the same grey as in the Docs? :smile:

**Comment by kazk** [comment]
@jhoffner can I use the subset of icons used on Codewars for the documentation? I made a subset from svg font and adjusted class names to make it easier to use with templates.

![image](https://cloud.githubusercontent.com/assets/639336/24938045/975213f8-1ee9-11e7-923f-54e59c2199cb.png)

**Comment by jhoffner** [comment]
Yaaay icomoon! Love that tool. 

Yes you can of course. Thanks!

>  May I suggest that the Dan badge for the user profile be edited to use the same grey as in the Docs

Yes that is a bug that its not matching the docs.

**Comment by jhoffner** [comment]
@kazk we should formalize what the repo will be for the documentation. Where you think we would eventually make this the repo or have a separate one? Probably makes sense to do it here unless  you have any objections. 

I'm asking now because I want to start logging issues for all of the areas that CW is missing documentation.

**Comment by kazk** [comment]
@jhoffner
I agree, `/docs` in this repository makes sense.

---

I'm still unsure about how to deal with the CLI documentation.
I took a look at them and some of them are really outdated or not documented at all.

> Its nice having it in that repository because when someone adds a new feature/language its a little easier to identify that as being missing (though keeping up with it hasn't worked much so far). Having everything here would require 2 separate PR's to 2 different repos but it would keep documentation together.

I was also concerned about having to do 2 PR's, but that's a one time inconvenience when adding a new language. I'm now leaning towards merging them into this. What do you think?

---

For the API documentation, embedding slate in Jekyll seems possible, but not really easy. I think we should keep them separate for now.
How are they hosted? [dev.codewars.com](https://dev.codewars.com) is not synced.

**Comment by jhoffner** [comment]
> I'm now leaning towards merging them into this. What do you think?

My main concern is that Qualified should be leveraging those CLI docs as well. We actually were maintaining separate docs over there which is not very efficient. We have a custom Angular-based KB app but it's all tied into our complex build system. At some point I could see both products using this system which is much simpler to contribute to, but if not then ideally the Angular app could pull data down from Github as either part of its build process or using AJAX.

BTW the current structure of that app is 
```
languages/
  «language-key».md
  «language-key»/
    «framework-key».md
  «language-key2».md
  «language-key2»/
    «framework-key».md
    «framework-key2».md
```

Another thing is that if the documentation was going to be shared, then the CLI stuff would need to remain application neutral and try not to mention either one. Seems doable.

IDK I'm kind of rambling here and think I might be causing more questions than answering. 

@OverZealous built the KB app for Qualified. @OverZealous have you checked out @kazk's https://github.com/kazk/docs.codewars.com repo yet? Any feedback? Here is the prototype documentation site: https://kazk.github.io/docs.codewars.com/

**Comment by kazk** [comment]
> Another thing is that if the documentation was going to be shared, then the CLI stuff would need to remain application neutral and try not to mention either one.

I think it's possible to switch contexts using the template. See [_config.yml#L4-L13](https://github.com/kazk/docs.codewars.com/blob/64994bf1f1038a351680647c8c9583c90e78917c/docs/_config.yml#L4-L13).

**Comment by jhoffner** [comment]
oh that could definitely be useful.

@kazk BTW if you haven't seen the Q docs yet: https://www.qualified.io/kb/

**Comment by OverZealous** [comment]
I'm really busy at the moment, but at a glance, it's pretty similar. It's missing some of the content we have (i.e., the `karma` test frameworks), but that's easy enough to add.

Really, whatever we choose, I'll end up having to manually parse and convert it for Qualified, because I don't want to rewrite the way the KB works too much for this. I'd rather just have a script to sync them once in a while, since it's not really that important to be exactly synced up. I'd probably just make my life easier for now and write it back out to the Markdown I'm already using.

We'll also have to filter which languages are supported, anyway, since CW supports a lot more languages than Q (and probably always will).

**Comment by jhoffner** [comment]
Thats a good point about applications supporting different languages. CW supports more languages, Q supports more frameworks. Once we start supporting project mode one application will likely support it before the other (probably Qualified first). So that could make storing documentation within the CLI tricky. 

@kazk how much control do we have over the Jekyll build process? I wonder if we can break content out into parts within the CLI and then stitch them into CW / Q as needed.

**Comment by kazk** [comment]
> how much control do we have over the Jekyll build process?

Currently we have almost no control. We're limited by GitHub Pages, requiring specific setup and only whitelisted gems can be used. The advantage of this setup is that the changes go live quickly and automatically without configuring.

---

For building Qualified docs out of this, you can do anything that Jekyll is capable of and have a separate configuration.

```
jekyll build --config _qualified_config.yml --destination _qualified_docs
```

There might be a useful Jekyll plugin filtering the pages to generate depending on the metadata. I haven't looked into Jekyll plugins much because GitHub Pages only allows few.
The configuration can be also used to *ignore* some pages by listing them in the `excludes` array.

We can also do this for Codewars documentation and push the generated static site to GitHub Pages. But this will require additional build step in order to reflect the contributed changes to go live. I think this is what's happening for the API docs (not updating `gh-pages` branch). It should be possible to automate this using CI services, but I haven't tried.

Another option is to keep the source here and host it somewhere else. Build using CI or web hooks so the changes to the repository triggers the build automatically. This allows us to use full Jekyll without additional build step, but requires more configuration.

**Comment by kazk** [comment]
It's relatively easy to *hide* the page by excluding from the navigation.

The page can have YAML front matter:
```yaml
supported_by: [Codewars, Qualified]
```

And the link to it can be skipped. The page is still generated.

**Comment by kazk** [comment]
@jhoffner For the API docs, I wrote a quick [OpenAPI specification](https://github.com/kazk/docs.codewars.com/blob/a1a1b484d11809a549fd99b3ad5c2447db32a737/docs/api/swagger.yml) and used [ReDoc](https://github.com/Rebilly/ReDoc)
 to generate the [documentation](https://kazk.github.io/docs.codewars.com/api).
Let me know what you think. I made it because I wanted to play with OpenAPI (Swagger), but it was really easy to embed.

![image](https://cloud.githubusercontent.com/assets/639336/25755424/e186e28c-3177-11e7-95ee-e90922d3efa5.png)

![image](https://cloud.githubusercontent.com/assets/639336/25755463/05c6c07c-3178-11e7-8721-3d1aae124c58.png)

**Comment by jhoffner** [comment]
That is some good looking API documentation.

**Comment by kazk** [comment]
This setup using OpenAPI 2.0 (Swagger) with ReDoc:

- Changes will be reflected and will go live as soon as it's merged to `master` just like other documentations.
- ReDoc is just generating a page from OpenAPI spec, so it's easy to update or replace with other tool.
- Has Slate's features except "Slate is just Markdown". Descriptions can be written in markdown inside YAML.
- API clients can be generated from the spec.
- Converting to other formats (I/O Docs, API Blueprint, Google API Discovery, RAML, WADL) is possible if needed.
- There are "Swagger to Slate" tools, but I haven't seen the reverse.

Current codewars-api-docs:

- Changes are not reflected automatically.
- Proprietary format.
- Slate is hard to update. I tried to update following their docs, but I gave up after having to deal with many merge conflicts :(
