### ISSUE TITLE
Draft Kata visibility

### ISSUE THREAD

**Issue by dinglemouse2250** [Codewars/codewars.com#885]
Why are "Draft" Kata descriptions visible to anyone but the *author* prior to Kata publication?

I had been using this draft mechanism to jot down ideas for future Kata as they occur to me... but my draft thoughts are not meant for public exposure until I **publish** them...

**Comment by kazk** [comment]
If you're talking about "Wise drunk man" kata, that **was published** earlier. The author unpublished all of his/her authored kata. I can access them from "Completed" tab, but it's not publicly listed.

I don't think "Draft" kata are visible to anyone but the author prior to Kata publication.

**Comment by kazk** [comment]
Actually, it might be possible for non-author to view a "Draft" kata that's never been published if you *know* the `slug` or `id` of the kata somehow. For example, maybe a friend authored a kata and sent you a link asking for your opinion.

If you're suggesting to completely restrict the access whenever the status is "Draft", I'm not sure if that's a good idea. I've helped authors to resolve issues in "Draft". It's useful to prevent unnecessary down votes while fixing the issue.

**Comment by dinglemouse2250** [comment]
> If you're talking about "Wise drunk man" kata, that was published earlier. 

Not specifically - that was the one that prompted the question though. When  I looked at https://www.codewars.com/users/AwelEshetu/authored I could see quite a few "Draft" Kata from that author. I was surprised that I could see them all. Are you saying I could see them all because they had once all been published? Anyway - now there is nothing there at all. Looks like they removed the whole lot (???)

I also have a number of "Draft" Kata which might turn into real Kata one day or maybe not. Are you able to see them or not? 
https://www.codewars.com/users/dinglemouse/authored

**Comment by DonaldKellett** [comment]
@dinglemouse2250 I am currently not logged in to Codewars but I just clicked on your link and I can't see a single "Draft" Kata.  Hope that addresses your concern :smile:

**Comment by kazk** [comment]
> Are you saying I could see them all because they had once all been published?

No, I just meant that they were published earlier today and unpublished not too long ago. You probably saw them because it was still being unpublished.

> Are you able to see them or not?

I don't see any "Draft" and the total published kata is `27`.
![image](https://cloud.githubusercontent.com/assets/639336/24835566/696ad06e-1cba-11e7-85f6-1a750a599986.png)

**Comment by dinglemouse2250** [comment]
I got muddled looking at all those other Draft ones that apparently were being being changed at the same time I was looking at them. I am still confused exactly what happened... 
* I guess I could see the Draft ones only because they had _previously_ been published?
* I guess I can't see anything now because the have been deleted?

Anyway and long as draft/unpublished is not visible there is no issue here. Closing this. Sorry for the confusion

**Comment by kazk** [comment]
@dinglemouse2250

> I guess I could see the Draft ones only because they had previously been published?

Like I said, I think they were still **being unpublished**. Maybe it took longer to be fully unpublished because of the background job queue issue. I don't know the details of how jobs are handled, but the stats aren't refreshing for the past few days. The publishing job has higher priority according to #731.

Also, people can access the Draft if they know the `slug` or `id` of the kata. This is what my second comment was about. So I wouldn't assume secrecy if it was once published and was seen by others. Google seems to know about it too.

![image](https://cloud.githubusercontent.com/assets/639336/24840246/81eecbae-1d1e-11e7-80fd-0efc4168cdef.png)

If Google search shows your Draft that's never published, I'd open a new issue.

---

> I guess I can't see anything now because they have been deleted?

They're not deleted. I can still access them from my "Completed" tab. "Wise drunk man" is back to Beta.
