### ISSUE TITLE
Cannot View own solutions page.

### ISSUE THREAD

**Issue by plasticbottle** [Codewars/codewars.com#944]
I get this message instead: undefined method `code_challenge_review' for nil:NilClass

The culprit may have been that I have solved a Beta Kata and the page does not know how to handle it, but that is just a wild guess. My username is the same as here.

**Comment by plasticbottle** [comment]
#252

**Comment by St3f4n** [comment]
It seems I'm having the same issue since yesterday. Everything works smooth expect for the solutions tab on my profile page which returns server 500.
@plasticbottle I saw your comment on issue #829 : "#944 I should have googled better :( I have the same issue exactly as here". 
I think that issue is a little different, since it's about not being able to open solutions page of a certain kata after solving it, while this one is about being unable to open solutions tab on own profile.

**Comment by St3f4n** [comment]
Update: Everything seems fine as of today.

**Comment by plasticbottle** [comment]
As for me, the link "https://www.codewars.com/users/plasticbottle/completed_solutions" still results in undefined method `code_challenge_review' for nil:NilClass

**Comment by kkorus** [comment]
@plasticbottle Have you found fix for that?

**Comment by plasticbottle** [comment]
The issue seems to be that I solved a Kata in a language that was subsequently removed. However, I don't think that this can be solved by anyone other than the Kata author, who could re-enable the removed language.

**Comment by error256** [comment]
@plasticbottle What is the kata where it happened? What happens if you try to set satisfaction rating for that kata? I suspect it might be rekated to #1291 because I have 3 bugged katas and 3 bugged pages in the solution list.

**Comment by plasticbottle** [comment]
@error256 I was able to rate satisfaction, the kata itself still works, but it's just that one of the languages is now gone.

**Comment by kazk** [comment]
This should be fixed. See #1627 and #1013.
