### ISSUE TITLE
IE 11 Support

### ISSUE THREAD

**Issue by nomennescio** [Codewars/codewars.com#963]
Cannot "Run Example Tests" nor "Attempt", on both Chrome (latest) and IE 11
for
https://www.codewars.com/kata/break-the-pieces/train/javascript
https://www.codewars.com/kata/functional-binary-trees/train/javascript
https://www.codewars.com/kata/integers-recreation-one/train/c

Also tried this on preview.codewars.com, which failed too.

Button "Run Example Tests" does not give any reaction.
Button "Attempt" will result in some "business", but without any result.

https://codewars.statuspage.io/
shows all systems are operational.

**Comment by Voileexperiments** [comment]
I think it's still a duplicate of #928.

Please check what the browser console (Ctrl+Alt+J in chrome and Ctrl+Alt+K in Firefox) says and what error it is giving (e.g 404 or 500).

**Comment by nomennescio** [comment]
Are the following relevant?

https://cdn.ably.io/lib/ably.min.js
The Ably CDN URL you are using is deprecated because it does not contain a version number. Please see https://support.ably.io/solution/articles/3000063698

https://cr.codewars.com/static/js/app.3bfa012eae6f99459fca.js
Uncaught TypeError: t.find is not a function

**Comment by kazk** [comment]
@nomennescio
Ably CDN warning should be irrelevant, it's been there for a while. (I do think it should be taken care of before it breaks anything.)

> Uncaught TypeError: t.find is not a function
>
> No mentioning of HTTP errors, only JS errors.

Seems different from #928.
I only found single `t.find` in `app.3bfa012eae6f99459fca.js`.

```js
function d(e, t) {
  return!!t.find(function(t){return new RegExp(t+"$").test(e)})
}
```

The input seems to be the following:

```js
e = "https://www.codewars.com"
t = ["codewars.com", "codewars.io", "qualified.io", "localhost(:\\d+)?"]
```

and called in:

```js
var w = ["codewars.com", "codewars.io", "qualified.io", "localhost(:\\d+)?"];
n.i(d.a)("message", function(e) {
  n.i(m.f)(e.origin, w) && (e.data.method ? window.store.dispatch("bridge.notifyReceipt", e.data) : e.data.source && -1 !== e.data.source.indexOf("devtools") || console.log("Message received with data", e.data))
}),
// `n.i(m.f)` is `d` from above
```

Since the input array `t` in `d(e, t)` seems to be always `w`, I think the issue here is that your browser doesn't support `Array.prototype.find`.
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find), IE 11 doesn't have it.
What is your Chrome version? If you are using older OS, the latest can be outdated. Google Chrome seems to support Windows 7+.

**Comment by nomennescio** [comment]
Windows 7, Chrome Version 44.0.x.x, IE 11.0.x.x

**Comment by kazk** [comment]
[Google Chrome 44.0.2403.130](https://chromereleases.googleblog.com/2015/08/stable-channel-update.html) is from `2015-08-04`. I think the latest stable is `58.0.x.x`.

I don't know why it's not updating for you because Windows 7 seems to be supported :/
I'm on macOS, but I can see download links available for Windows 7 in [download page](https://www.google.com/chrome/browser/desktop/).
![image](https://cloud.githubusercontent.com/assets/639336/26029350/d1e79ed6-37e7-11e7-8e83-232cb87216ae.png)

I'd recommend looking into this because outdated browsers can be a security risk.

**Comment by kazk** [comment]
I didn't see your edited comment.

> A couple of weeks ago everything was working OK

I'm not sure about the browser support status, but the output panel was updated recently.

**Comment by nomennescio** [comment]
A major change in Chrome 45 was the removal of the NPAPI, which is needed by e.g. Java.
Maybe Chrome is not updating because it detects such a dependency for the extensions, I don't know.

However, using IE 11.0 should be working with the website too, doesn't it?

I recognise your remark that the output panel was recently updated. Isn't it feasible to roll that back, or integrate the older solution into it?

**Comment by kazk** [comment]
> I recognise your remark that the output panel was recently updated. Isn't it feasible to roll that back, or integrate the older solution into it?

This issue can be fixed by not using `Array.prototype.find` or adding a [polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#Polyfill). This needs to be done for *every* method that IE 11 doesn't support.

We need to wait for @jhoffner to comeback from vacation to discuss this further.

**Comment by jhoffner** [comment]
I got a chance to add the `Array.prototype.find` polyfill and deploy early this morning (Hong Kong time). If that was enough to fix please test and close. 

I'm traveling again today so won't know when my next chance to take another stab at this will be.

**Comment by nomennescio** [comment]
Thanks for the adding of the polyfill. However, when running in IE 11 I got the same issue, but now in

https://cr.codewars.com/static/js/app.c2e1bcc6ff5655238fdd.js

Object doesn't support property or method 'find'

**Comment by jhoffner** [comment]
Full babel-polyfill was added and I've tested. Should be good now.
