### ISSUE TITLE
Server Execution Error with STDERR containing "write unix /var/run/docker.sock: broken pipe"

### ISSUE THREAD

**Issue by Voileexperiments** [Codewars/codewars.com#978]
Submitting kata frequently gives me this message since around 10-30 minutes ago.

![image](https://cloud.githubusercontent.com/assets/14909989/26484410/87cd4c96-4224-11e7-965c-c47bd649d064.png)

This only happens when submitting code against the real tests. Running against sample tests do not have this problem.

**Comment by Andrew32bit** [comment]
it seems to be that codewars never answered lol

**Comment by kazk** [comment]
@Voileexperiments is this still happening? If so, can you provide more details (which kata, how often, anything special)?
I couldn't reproduce this trying few katas.

**Comment by Voileexperiments** [comment]
@kazk It's from myjinxin's new beta kata:
https://www.codewars.com/kata/one-line-task-super-even/train/javascript
Submitting the code causes that error like 2 out of 3 times?

**Comment by kazk** [comment]
@Voileexperiments Is that the only kata you saw the error? I submitted 5 times and all of them passed fine :/ I also tried while logged out (no RED) and on forked kumite.
If the issue is network related, our locations might be the reason why I can't reproduce.

---

I had never seen an error message mentioning `/var/run/docker.sock`, but I think I've seen `The server was unable to process the request. Please try again.`.
Maybe the recent update on `#runner_frame` started to show `stderr` for server errors?

**Comment by Voileexperiments** [comment]
Unfortunately the problem seems to have disappeared since I'd approved it. I guess we'll have to wait for the stars to align again.

But yeah, that's a new and very rare kind of error. I seem to recall seeing it some other time recently but I have no idea where and how I'd be able to reproduce this again.

**Comment by Voileexperiments** [comment]
This hasn't occurred again for a long time. Closing.
