### ISSUE TITLE
Stop gninnipS My sdroW! I dont understand why my function  doenst working in Kata, i cant submit it.In python IDLE all works correctly.whats wrong with my code?

### ISSUE THREAD

**Issue by Andrew32bit** [Codewars/codewars.com#979]
def spin_words(sentence):
    x = sentence[0:sentence.find(' ')]
    y = sentence[sentence.find(' '):sentence.find(' ',sentence.find(' ')+1)]
    w=sentence[sentence.find(' ',sentence.find(' ')+1):sentence.rfind(' ')]
    f = sentence[sentence.rfind(' '):]
    x = sentence[0:sentence.find(' ')]
    if ' ' not in sentence:
        print(sentence[::-1])
    elif len(x)>=5:
        print(x[::-1]+y+w+f)
    elif len(y)>=5 and len(w)>=5:
        print(x +" "+y[::-1]+w+f)
    elif len(w)>=5:
        print(x+y+" "+w[::-1]+f)
    elif len(f)>=5:
        print(x+y+w+" "+f[::-1])
    else:
        print(x+y+w+f)#

**Comment by kazk** [comment]
Please ask questions specific to kata on it's own discourse page.

**Comment by kazk** [comment]
I don't know which kata this is for, and I can't read your code because it's not formatted, but I'm pretty sure your code need to `return` something.
If that's not the issue, then make sure you're not modifying the input.

Also, try formatting your code using triple backticks like the following when asking questions on the discourse and don't forget to mark your comment as a spoiler :)

<pre>
```python
def spin_words(sentence):
  pass
```
</pre>

This will show your code formatted like this

```python
def spin_words(sentence):
  pass
```

**Comment by Andrew32bit** [comment]
Thank you,i passed it.Just replace "Print" and return functions.
